In [ ]:
#!pip install arch

In [1]:
from arch import arch_model
import pandas as pd
import wrds
import numpy as np

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
nasbramlidb =\
(
    wrds
    .Connection()
)

Enter your WRDS username [nasruddinislambinramli]:nasbramli
Enter your password:········
WRDS recommends setting up a .pgpass file.
Create .pgpass file now [y/n]?: y
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

In [3]:
fama_french_query =\
(
    """
    SELECT date, mktrf, smb, hml, rf 
    FROM ff.factors_monthly
    WHERE date >= '2000-01-01' AND date < '2024-01-01'
    """
)

In [4]:
ff_df =\
(
    db
    .raw_sql(fama_french_query)
)

In [5]:
(
    ff_df
    .to_csv('fama_french.csv', index = False)
)

In [6]:
fama_french =\
(
    pd
    .read_csv('fama_french.csv')
)

In [7]:
fama_french

           date   mktrf     smb     hml      rf
0    2000-01-01 -0.0474  0.0577 -0.0188  0.0041
1    2000-02-01  0.0245  0.2136 -0.0959  0.0043
2    2000-03-01  0.0520 -0.1720  0.0813  0.0047
3    2000-04-01 -0.0640 -0.0668  0.0726  0.0046
4    2000-05-01 -0.0442 -0.0605  0.0475  0.0050
..          ...     ...     ...     ...     ...
283  2023-08-01 -0.0239 -0.0320 -0.0108  0.0045
284  2023-09-01 -0.0524 -0.0249  0.0145  0.0043
285  2023-10-01 -0.0318 -0.0388  0.0019  0.0047
286  2023-11-01  0.0883 -0.0003  0.0166  0.0044
287  2023-12-01  0.0487  0.0636  0.0492  0.0043

[288 rows x 5 columns]

In [8]:
fama_french["Date"]=\
(
    fama_french
    .date
    .apply(lambda x: str(x)
          )
)

fama_french["Date"]=\
(
    pd
    .to_datetime(fama_french.Date,
                 format="%Y-%m-%d"
                )
)

fama_french =\
(
    fama_french
    .set_index("Date", inplace = False)
)

In [9]:
fama_french =\
(
    fama_french
    .drop(columns=['date'])
)

In [10]:
fama_french

             mktrf     smb     hml      rf
Date
2000-01-01 -0.0474  0.0577 -0.0188  0.0041
2000-02-01  0.0245  0.2136 -0.0959  0.0043
2000-03-01  0.0520 -0.1720  0.0813  0.0047
2000-04-01 -0.0640 -0.0668  0.0726  0.0046
2000-05-01 -0.0442 -0.0605  0.0475  0.0050
...            ...     ...     ...     ...
2023-08-01 -0.0239 -0.0320 -0.0108  0.0045
2023-09-01 -0.0524 -0.0249  0.0145  0.0043
2023-10-01 -0.0318 -0.0388  0.0019  0.0047
2023-11-01  0.0883 -0.0003  0.0166  0.0044
2023-12-01  0.0487  0.0636  0.0492  0.0043

[288 rows x 4 columns]

In [11]:
fama_french =\
(
    fama_french[['smb', 'hml']]
)

In [12]:
fama_french

               smb     hml
Date
2000-01-01  0.0577 -0.0188
2000-02-01  0.2136 -0.0959
2000-03-01 -0.1720  0.0813
2000-04-01 -0.0668  0.0726
2000-05-01 -0.0605  0.0475
...            ...     ...
2023-08-01 -0.0320 -0.0108
2023-09-01 -0.0249  0.0145
2023-10-01 -0.0388  0.0019
2023-11-01 -0.0003  0.0166
2023-12-01  0.0636  0.0492

[288 rows x 2 columns]

In [13]:
file_path =\
(
    'all_tickers_time_series.hf5'
)

with pd.HDFStore(file_path, 'r') as hdf_file:
    keys =\
    (
        hdf_file.keys()
    )

In [14]:
russell = {}

for key in keys:
    
    data =\
    (
        pd
        .read_hdf('all_tickers_time_series.hf5', 
                  key=key)
    )
    
    if isinstance(data, pd.Series):
        
        data =\
        (
            data
            .to_frame()
        )
        
    data =\
    (
        data
        .drop_duplicates()
    )
    
    data =\
    (
        data
        .dropna()
    )
    
    if isinstance(data, pd.DataFrame) and 'date' in data.columns:
        data['Date'] =\
        (
            pd
            .to_datetime(data['date'], 
                         format="%Y-%m-%d")
        )
        
        data =\
        (
            data
            .drop(columns=['date'])
        )
        
        data =\
        (
            data
            .set_index('Date')
        )
    
    
    russell[key] = data

In [15]:
stock_data = {}

In [16]:
for ticker, data in russell.items():

    df =\
    (
        pd
        .DataFrame(data)
    )

    print(f"Columns for {ticker}: {df.columns.tolist()}")
    
    if 'prc' in df.columns:
        
        df['returns'] =\
        (
            np.log(df['prc']
                   /
                   df['prc'].shift(1)
                  )
        )
        
        df['r_vol'] =\
        (
            df['returns']
            .rolling(window = 252)
            .std()
            *
            np
            .sqrt
            (252)
        )
        
        
        stock_data[ticker] = df
    else:
        print(f"'prc' column not found for {ticker}. Available columns: {df.columns.tolist()}")

Columns for /A: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AAL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AAON: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AAP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AAPL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ABBV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ABNB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ABT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ACGL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ACHC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ACI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ACM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ACN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ADBE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ADC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ADI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ADM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ADP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ADSK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ADT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AEE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AEP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AES: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AFG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AFL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AFRM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AGCO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AGNC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AGO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AGR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AIG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AIZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AJG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AKAM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALAB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALGM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALGN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALLE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALLY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALNY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ALSN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMAT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMCR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AME: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMED: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMGN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMKR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AMZN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ANET: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ANSS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AON: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AOS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APLS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APPF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /APTV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ARE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ARES: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ARMK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ARW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ASH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ATI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ATO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ATR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AVB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AVGO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AVT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AVTR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AVY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AWI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AWK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AXON: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AXP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AXS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AXTA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AYI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AZEK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AZO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AZPN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /AZTA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BAC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BAH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BALL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BAX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BBWI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BBY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BDX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BEPC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BERY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BFAM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BHF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BIIB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BILL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BIO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BIRK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BJ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BKNG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BKR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BLD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BLDR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BLK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BMRN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BMY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BOKF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BPOP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BRBR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BRKR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BRO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BROS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BRX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BSX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BSY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BURL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BWA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BWXT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BXP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /BYD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /C: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CACC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CACI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CAG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CAH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CAR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CARR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CART: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CASY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CAT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CAVA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CBOE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CBRE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CBSH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CCCS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CCI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CCK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CCL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CDNS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CDW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CEG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CELH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CERT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CFG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CFLT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CFR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CGNX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CHD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CHDN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CHE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CHH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CHK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']

Columns for /CHRD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CHRW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CHTR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CIEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CINF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CIVI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CLF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CLH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CLVT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CLX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CMA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CMCSA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CME: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CMG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CMI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CMS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CNA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CNC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CNH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CNM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CNP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CNXC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COHR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COIN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COKE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COLB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COLD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COLM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /COTY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CPB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CPNG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CPRI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CPRT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CPT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CRBG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CRH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CRI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CRL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CRM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CROX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CRUS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CRWD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CSCO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CSGP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CSL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CSX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CTAS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CTLT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CTRA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CTSH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CTVA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CUBE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CUZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CVNA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CVS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CVX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CWEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CXT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /CZR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /D: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DAL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DAR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DASH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DAY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DBX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DCI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DDOG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DDS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DECK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DELL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DFS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DGX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DHI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DHR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DINO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DIS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DJT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DKNG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DKS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DLB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DLR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DLTR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DNB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DOC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DOCS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DOCU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DOV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DOW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DOX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DPZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DRI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DTE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DTM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DUK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DUOL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DVA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DVN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DXC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /DXCM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EBAY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ECL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ED: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EEFT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EFX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EGP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EHC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EIX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ELAN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ELF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ELS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ELV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EME: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EMN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EMR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ENOV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ENPH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ENTG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EOG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EPAM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EPR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EQH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EQIX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EQR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EQT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ES: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ESAB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ESI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ESS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ESTC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ETN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ETR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ETSY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EVR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EVRG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EWBC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EXAS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EXC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EXEL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EXP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EXPD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EXPE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /EXR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /F: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FAF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FANG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FAST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FBIN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FCN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FCNCA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FCX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FDS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FDX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FERG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FFIV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FHB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FHN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FICO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FIS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FITB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']

Columns for /FNF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FOUR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FOX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FOXA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FRPT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FRT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FSLR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FTI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FTNT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FTRE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FTV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FWONA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FWONK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /FYBR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /G: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GAP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GDDY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GEHC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GEV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GFS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GGG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GILD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GIS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GLOB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GLPI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GLW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GME: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GMED: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GNRC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GNTX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GOOG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GOOGL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GPC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GPK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GPN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GRMN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GTES: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GTLB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GWRE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GWW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /GXO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /H: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HAL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HAS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HAYW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HBAN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HCA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HCP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HEI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HES: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HHH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HIG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HII: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HIW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HLI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HLT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HOG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HOLX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HON: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HOOD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HPE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HPQ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HRB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HRL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HSIC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HSY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HUBB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HUBS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HUM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HUN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HWM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /HXL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IAC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IBKR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IBM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ICE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IDA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IDXX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IEX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IFF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ILMN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /INCY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /INFA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /INGR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /INSP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /INTC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /INTU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /INVH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IONS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IPG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IPGP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IQV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IRDM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IRM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ISRG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ITCI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ITT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ITW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /IVZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /J: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JAZZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JBHT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JBL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JCI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JEF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JHG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JKHY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JLL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JNJ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JNPR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JPM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /JWN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /K: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KBR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KDP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KEX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KEY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KEYS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KHC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KIM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KKR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KLAC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KMB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KMI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KMPR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KMX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KNSL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KNX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KRC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KSS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /KVUE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /L: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LAD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LAMR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LAZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LBRDA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LBRDK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LBTYA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LBTYK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LCID: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LDOS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LEA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LECO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LEG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LFUS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LHX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LII: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LIN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LINE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LITE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LKQ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LLY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LLYVA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LLYVK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LMT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LNC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LNG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LNT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LNW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /LOPE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']

Columns for /MRK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MRNA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MRO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MRVL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MSA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MSCI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MSFT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MSGS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MSI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MSM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MSTR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTCH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTDR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTSI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MTZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /MUSA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NBIX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NCLH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NCNO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NDAQ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NDSN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NEE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NEM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NET: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NEU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NFE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NFG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NFLX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NKE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NLY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NNN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NOC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NOV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NOW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NRG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NSA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NSC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NTAP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NTNX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NTRA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NTRS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NUE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NVDA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NVR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NVST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NVT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NWL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NWS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NWSA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NXST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /NYT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /O: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ODFL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OGE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OGN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OHI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OKE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OKTA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OLED: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OLLI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OLN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OMC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OMF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ON: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ONTO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ORCL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ORI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ORLY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OSK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OTIS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OVV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OWL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OXY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /OZK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PAG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PANW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PARA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PARAA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PATH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PAYC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PAYX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PCAR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PCG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PCOR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PCTY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PEG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PEGA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PENN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PEP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PFE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PFG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PFGC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PGR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PHM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PII: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PINC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PINS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PKG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PLD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PLNT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PLTK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PLTR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PNC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PNFP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PNR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PNW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PODD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /POOL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /POST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PPC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PPG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PPL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PRGO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PRI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PRU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PSA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PSN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PSTG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PSX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PTC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PVH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PWR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PYCR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /PYPL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /QCOM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /QDEL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /QGEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /QRVO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /QS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /R: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RARE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RBA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RBC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RBLX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RCL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RCM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /REG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /REGN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /REXR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /REYN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RGA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RGEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RGLD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RHI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RITM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RIVN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RJF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RKT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RLI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RMD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RNG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RNR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ROIV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ROK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ROKU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ROL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ROP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ROST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RPM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RPRX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']

Columns for /RVTY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RYAN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /RYN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /S: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SAIA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SAIC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SAM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SBAC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SBUX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SCCO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SCHW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SCI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SEB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SEE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SEG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SEIC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SHC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SHW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SIRI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SITE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SJM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SKX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SLB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SLGN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SLM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SMAR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SMCI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SMG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SNA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SNDR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SNOW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SNPS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SNV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SNX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SOFI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SON: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SPB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SPG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SPGI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SPOT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SPR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SQ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SRCL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SRE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SRPT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SSD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SSNC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /STAG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /STE: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /STLD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /STT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /STWD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /STZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SUI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SWK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SWKS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SWN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SYF: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SYK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /SYY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /T: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TAP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TDC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TDG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TDY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TEAM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TECH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TER: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TFC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TFSL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TFX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TGT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /THC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /THG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /THO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TJX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TKO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TKR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TMO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TMUS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TNL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TOL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TOST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TPG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TPL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TPR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TPX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TREX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TRGP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TRIP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TRMB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TROW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TRU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TRV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TSCO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TSLA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TSN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TTC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TTD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TTEK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TTWO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TWLO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TXG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TXN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TXRH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TXT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /TYL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /U: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UAA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UAL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UBER: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UDR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UGI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UHAL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UHS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ULTA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UNH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UNM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UNP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UPS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /URI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /USB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /USFD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UTHR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /UWMC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /V: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VAC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VEEV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VFC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VICI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VIRT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VKTX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VLO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VLTO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VMC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VMI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VNO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VNOM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VNT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VOYA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VRSK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VRSN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VRT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VRTX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VSTS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VTR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VTRS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VVV: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /VZ: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /W: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WAB: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WAL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WAT: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WBA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WBD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WBS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WCC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WDAY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WDC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WEC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WEN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WEX: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WFC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WFRD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WHR: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WING: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WLK: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']

Columns for /WSO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WST: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WTFC: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WTM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WTRG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WTW: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WU: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WWD: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /WYNN: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /X: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /XEL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /XOM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /XP: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /XPO: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /XRAY: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /XYL: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /YETI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /YUM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /Z: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZBH: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZBRA: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZG: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZI: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZION: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZM: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZTS: ['ticker', 'openprc', 'askhi', 'bidlo', 'prc', 'vol', 'dlstdt', 'dlstcd', 'nextdt', 'dlprc']
Columns for /ZTS/meta/values_block_0/meta: [0]
'prc' column not found for /ZTS/meta/values_block_0/meta. Available columns: [0]
Columns for /ZS/meta/values_block_0/meta: [0]
'prc' column not found for /ZS/meta/values_block_0/meta. Available columns: [0]
Columns for /ZM/meta/values_block_0/meta: [0]
'prc' column not found for /ZM/meta/values_block_0/meta. Available columns: [0]
Columns for /ZION/meta/values_block_0/meta: [0]
'prc' column not found for /ZION/meta/values_block_0/meta. Available columns: [0]
Columns for /ZI/meta/values_block_0/meta: [0]
'prc' column not found for /ZI/meta/values_block_0/meta. Available columns: [0]
Columns for /ZG/meta/values_block_0/meta: [0]
'prc' column not found for /ZG/meta/values_block_0/meta. Available columns: [0]
Columns for /ZBRA/meta/values_block_0/meta: [0]
'prc' column not found for /ZBRA/meta/values_block_0/meta. Available columns: [0]
Columns for /ZBH/meta/values_block_0/meta: [0]
'prc' column not found for /ZBH/meta/values_block_0/meta. Available columns: [0]
Columns for /Z/meta/values_block_0/meta: [0]
'prc' column not found for /Z/meta/values_block_0/meta. Available columns: [0]
Columns for /YUM/meta/values_block_0/meta: [0]
'prc' column not found for /YUM/meta/values_block_0/meta. Available columns: [0]
Columns for /YETI/meta/values_block_0/meta: [0]
'prc' column not found for /YETI/meta/values_block_0/meta. Available columns: [0]
Columns for /XYL/meta/values_block_0/meta: [0]
'prc' column not found for /XYL/meta/values_block_0/meta. Available columns: [0]
Columns for /XRAY/meta/values_block_0/meta: [0]
'prc' column not found for /XRAY/meta/values_block_0/meta. Available columns: [0]
Columns for /XPO/meta/values_block_0/meta: [0]
'prc' column not found for /XPO/meta/values_block_0/meta. Available columns: [0]
Columns for /XP/meta/values_block_0/meta: [0]
'prc' column not found for /XP/meta/values_block_0/meta. Available columns: [0]
Columns for /XOM/meta/values_block_0/meta: [0]
'prc' column not found for /XOM/meta/values_block_0/meta. Available columns: [0]
Columns for /XEL/meta/values_block_0/meta: [0]
'prc' column not found for /XEL/meta/values_block_0/meta. Available columns: [0]
Columns for /X/meta/values_block_0/meta: [0]
'prc' column not found for /X/meta/values_block_0/meta. Available columns: [0]
Columns for /WYNN/meta/values_block_0/meta: [0]
'prc' column not found for /WYNN/meta/values_block_0/meta. Available columns: [0]
Columns for /WY/meta/values_block_0/meta: [0]
'prc' column not found for /WY/meta/values_block_0/meta. Available columns: [0]
Columns for /WWD/meta/values_block_0/meta: [0]
'prc' column not found for /WWD/meta/values_block_0/meta. Available columns: [0]
Columns for /WU/meta/values_block_0/meta: [0]
'prc' column not found for /WU/meta/values_block_0/meta. Available columns: [0]
Columns for /WTW/meta/values_block_0/meta: [0]
'prc' column not found for /WTW/meta/values_block_0/meta. Available columns: [0]
Columns for /WTRG/meta/values_block_0/meta: [0]
'prc' column not found for /WTRG/meta/values_block_0/meta. Available columns: [0]
Columns for /WTM/meta/values_block_0/meta: [0]
'prc' column not found for /WTM/meta/values_block_0/meta. Available columns: [0]
Columns for /WTFC/meta/values_block_0/meta: [0]
'prc' column not found for /WTFC/meta/values_block_0/meta. Available columns: [0]
Columns for /WST/meta/values_block_0/meta: [0]
'prc' column not found for /WST/meta/values_block_0/meta. Available columns: [0]
Columns for /WSO/meta/values_block_0/meta: [0]
'prc' column not found for /WSO/meta/values_block_0/meta. Available columns: [0]
Columns for /WSM/meta/values_block_0/meta: [0]
'prc' column not found for /WSM/meta/values_block_0/meta. Available columns: [0]
Columns for /WSC/meta/values_block_0/meta: [0]
'prc' column not found for /WSC/meta/values_block_0/meta. Available columns: [0]
Columns for /WRB/meta/values_block_0/meta: [0]
'prc' column not found for /WRB/meta/values_block_0/meta. Available columns: [0]
Columns for /WPC/meta/values_block_0/meta: [0]
'prc' column not found for /WPC/meta/values_block_0/meta. Available columns: [0]
Columns for /WOLF/meta/values_block_0/meta: [0]
'prc' column not found for /WOLF/meta/values_block_0/meta. Available columns: [0]
Columns for /WMT/meta/values_block_0/meta: [0]
'prc' column not found for /WMT/meta/values_block_0/meta. Available columns: [0]
Columns for /WMS/meta/values_block_0/meta: [0]
'prc' column not found for /WMS/meta/values_block_0/meta. Available columns: [0]
Columns for /WMB/meta/values_block_0/meta: [0]
'prc' column not found for /WMB/meta/values_block_0/meta. Available columns: [0]
Columns for /WM/meta/values_block_0/meta: [0]
'prc' column not found for /WM/meta/values_block_0/meta. Available columns: [0]
Columns for /WLK/meta/values_block_0/meta: [0]
'prc' column not found for /WLK/meta/values_block_0/meta. Available columns: [0]
Columns for /WING/meta/values_block_0/meta: [0]
'prc' column not found for /WING/meta/values_block_0/meta. Available columns: [0]
Columns for /WHR/meta/values_block_0/meta: [0]
'prc' column not found for /WHR/meta/values_block_0/meta. Available columns: [0]
Columns for /WH/meta/values_block_0/meta: [0]
'prc' column not found for /WH/meta/values_block_0/meta. Available columns: [0]
Columns for /WFRD/meta/values_block_0/meta: [0]
'prc' column not found for /WFRD/meta/values_block_0/meta. Available columns: [0]
Columns for /WFC/meta/values_block_0/meta: [0]
'prc' column not found for /WFC/meta/values_block_0/meta. Available columns: [0]
Columns for /WEX/meta/values_block_0/meta: [0]
'prc' column not found for /WEX/meta/values_block_0/meta. Available columns: [0]
Columns for /WEN/meta/values_block_0/meta: [0]
'prc' column not found for /WEN/meta/values_block_0/meta. Available columns: [0]
Columns for /WEC/meta/values_block_0/meta: [0]
'prc' column not found for /WEC/meta/values_block_0/meta. Available columns: [0]
Columns for /WDC/meta/values_block_0/meta: [0]
'prc' column not found for /WDC/meta/values_block_0/meta. Available columns: [0]
Columns for /WDAY/meta/values_block_0/meta: [0]
'prc' column not found for /WDAY/meta/values_block_0/meta. Available columns: [0]
Columns for /WCC/meta/values_block_0/meta: [0]
'prc' column not found for /WCC/meta/values_block_0/meta. Available columns: [0]
Columns for /WBS/meta/values_block_0/meta: [0]
'prc' column not found for /WBS/meta/values_block_0/meta. Available columns: [0]
Columns for /WBD/meta/values_block_0/meta: [0]
'prc' column not found for /WBD/meta/values_block_0/meta. Available columns: [0]
Columns for /WBA/meta/values_block_0/meta: [0]
'prc' column not found for /WBA/meta/values_block_0/meta. Available columns: [0]
Columns for /WAT/meta/values_block_0/meta: [0]
'prc' column not found for /WAT/meta/values_block_0/meta. Available columns: [0]
Columns for /WAL/meta/values_block_0/meta: [0]
'prc' column not found for /WAL/meta/values_block_0/meta. Available columns: [0]
Columns for /WAB/meta/values_block_0/meta: [0]
'prc' column not found for /WAB/meta/values_block_0/meta. Available columns: [0]
Columns for /W/meta/values_block_0/meta: [0]
'prc' column not found for /W/meta/values_block_0/meta. Available columns: [0]
Columns for /VZ/meta/values_block_0/meta: [0]
'prc' column not found for /VZ/meta/values_block_0/meta. Available columns: [0]
Columns for /VVV/meta/values_block_0/meta: [0]
'prc' column not found for /VVV/meta/values_block_0/meta. Available columns: [0]
Columns for /VTRS/meta/values_block_0/meta: [0]
'prc' column not found for /VTRS/meta/values_block_0/meta. Available columns: [0]
Columns for /VTR/meta/values_block_0/meta: [0]
'prc' column not found for /VTR/meta/values_block_0/meta. Available columns: [0]
Columns for /VSTS/meta/values_block_0/meta: [0]
'prc' column not found for /VSTS/meta/values_block_0/meta. Available columns: [0]
Columns for /VST/meta/values_block_0/meta: [0]
'prc' column not found for /VST/meta/values_block_0/meta. Available columns: [0]
Columns for /VRTX/meta/values_block_0/meta: [0]
'prc' column not found for /VRTX/meta/values_block_0/meta. Available columns: [0]
Columns for /VRT/meta/values_block_0/meta: [0]
'prc' column not found for /VRT/meta/values_block_0/meta. Available columns: [0]
Columns for /VRSN/meta/values_block_0/meta: [0]
'prc' column not found for /VRSN/meta/values_block_0/meta. Available columns: [0]
Columns for /VRSK/meta/values_block_0/meta: [0]
'prc' column not found for /VRSK/meta/values_block_0/meta. Available columns: [0]
Columns for /VOYA/meta/values_block_0/meta: [0]
'prc' column not found for /VOYA/meta/values_block_0/meta. Available columns: [0]
Columns for /VNT/meta/values_block_0/meta: [0]
'prc' column not found for /VNT/meta/values_block_0/meta. Available columns: [0]
Columns for /VNOM/meta/values_block_0/meta: [0]
'prc' column not found for /VNOM/meta/values_block_0/meta. Available columns: [0]
Columns for /VNO/meta/values_block_0/meta: [0]
'prc' column not found for /VNO/meta/values_block_0/meta. Available columns: [0]
Columns for /VMI/meta/values_block_0/meta: [0]
'prc' column not found for /VMI/meta/values_block_0/meta. Available columns: [0]
Columns for /VMC/meta/values_block_0/meta: [0]
'prc' column not found for /VMC/meta/values_block_0/meta. Available columns: [0]
Columns for /VLTO/meta/values_block_0/meta: [0]
'prc' column not found for /VLTO/meta/values_block_0/meta. Available columns: [0]
Columns for /VLO/meta/values_block_0/meta: [0]
'prc' column not found for /VLO/meta/values_block_0/meta. Available columns: [0]
Columns for /VKTX/meta/values_block_0/meta: [0]
'prc' column not found for /VKTX/meta/values_block_0/meta. Available columns: [0]
Columns for /VIRT/meta/values_block_0/meta: [0]
'prc' column not found for /VIRT/meta/values_block_0/meta. Available columns: [0]
Columns for /VICI/meta/values_block_0/meta: [0]
'prc' column not found for /VICI/meta/values_block_0/meta. Available columns: [0]
Columns for /VFC/meta/values_block_0/meta: [0]
'prc' column not found for /VFC/meta/values_block_0/meta. Available columns: [0]
Columns for /VEEV/meta/values_block_0/meta: [0]
'prc' column not found for /VEEV/meta/values_block_0/meta. Available columns: [0]
Columns for /VAC/meta/values_block_0/meta: [0]
'prc' column not found for /VAC/meta/values_block_0/meta. Available columns: [0]
Columns for /V/meta/values_block_0/meta: [0]
'prc' column not found for /V/meta/values_block_0/meta. Available columns: [0]
Columns for /UWMC/meta/values_block_0/meta: [0]
'prc' column not found for /UWMC/meta/values_block_0/meta. Available columns: [0]
Columns for /UTHR/meta/values_block_0/meta: [0]
'prc' column not found for /UTHR/meta/values_block_0/meta. Available columns: [0]
Columns for /USFD/meta/values_block_0/meta: [0]
'prc' column not found for /USFD/meta/values_block_0/meta. Available columns: [0]
Columns for /USB/meta/values_block_0/meta: [0]
'prc' column not found for /USB/meta/values_block_0/meta. Available columns: [0]
Columns for /URI/meta/values_block_0/meta: [0]
'prc' column not found for /URI/meta/values_block_0/meta. Available columns: [0]
Columns for /UPS/meta/values_block_0/meta: [0]
'prc' column not found for /UPS/meta/values_block_0/meta. Available columns: [0]
Columns for /UNP/meta/values_block_0/meta: [0]
'prc' column not found for /UNP/meta/values_block_0/meta. Available columns: [0]
Columns for /UNM/meta/values_block_0/meta: [0]
'prc' column not found for /UNM/meta/values_block_0/meta. Available columns: [0]
Columns for /UNH/meta/values_block_0/meta: [0]
'prc' column not found for /UNH/meta/values_block_0/meta. Available columns: [0]
Columns for /ULTA/meta/values_block_0/meta: [0]
'prc' column not found for /ULTA/meta/values_block_0/meta. Available columns: [0]
Columns for /UI/meta/values_block_0/meta: [0]
'prc' column not found for /UI/meta/values_block_0/meta. Available columns: [0]
Columns for /UHS/meta/values_block_0/meta: [0]
'prc' column not found for /UHS/meta/values_block_0/meta. Available columns: [0]
Columns for /UHAL/meta/values_block_0/meta: [0]
'prc' column not found for /UHAL/meta/values_block_0/meta. Available columns: [0]
Columns for /UGI/meta/values_block_0/meta: [0]
'prc' column not found for /UGI/meta/values_block_0/meta. Available columns: [0]
Columns for /UDR/meta/values_block_0/meta: [0]
'prc' column not found for /UDR/meta/values_block_0/meta. Available columns: [0]
Columns for /UBER/meta/values_block_0/meta: [0]
'prc' column not found for /UBER/meta/values_block_0/meta. Available columns: [0]
Columns for /UAL/meta/values_block_0/meta: [0]
'prc' column not found for /UAL/meta/values_block_0/meta. Available columns: [0]
Columns for /UAA/meta/values_block_0/meta: [0]
'prc' column not found for /UAA/meta/values_block_0/meta. Available columns: [0]
Columns for /UA/meta/values_block_0/meta: [0]
'prc' column not found for /UA/meta/values_block_0/meta. Available columns: [0]
Columns for /U/meta/values_block_0/meta: [0]
'prc' column not found for /U/meta/values_block_0/meta. Available columns: [0]
Columns for /TYL/meta/values_block_0/meta: [0]
'prc' column not found for /TYL/meta/values_block_0/meta. Available columns: [0]
Columns for /TXT/meta/values_block_0/meta: [0]
'prc' column not found for /TXT/meta/values_block_0/meta. Available columns: [0]
Columns for /TXRH/meta/values_block_0/meta: [0]
'prc' column not found for /TXRH/meta/values_block_0/meta. Available columns: [0]
Columns for /TXN/meta/values_block_0/meta: [0]
'prc' column not found for /TXN/meta/values_block_0/meta. Available columns: [0]
Columns for /TXG/meta/values_block_0/meta: [0]
'prc' column not found for /TXG/meta/values_block_0/meta. Available columns: [0]
Columns for /TWLO/meta/values_block_0/meta: [0]
'prc' column not found for /TWLO/meta/values_block_0/meta. Available columns: [0]
Columns for /TW/meta/values_block_0/meta: [0]
'prc' column not found for /TW/meta/values_block_0/meta. Available columns: [0]
Columns for /TTWO/meta/values_block_0/meta: [0]
'prc' column not found for /TTWO/meta/values_block_0/meta. Available columns: [0]
Columns for /TTEK/meta/values_block_0/meta: [0]
'prc' column not found for /TTEK/meta/values_block_0/meta. Available columns: [0]
Columns for /TTD/meta/values_block_0/meta: [0]
'prc' column not found for /TTD/meta/values_block_0/meta. Available columns: [0]
Columns for /TTC/meta/values_block_0/meta: [0]
'prc' column not found for /TTC/meta/values_block_0/meta. Available columns: [0]
Columns for /TT/meta/values_block_0/meta: [0]
'prc' column not found for /TT/meta/values_block_0/meta. Available columns: [0]
Columns for /TSN/meta/values_block_0/meta: [0]
'prc' column not found for /TSN/meta/values_block_0/meta. Available columns: [0]
Columns for /TSLA/meta/values_block_0/meta: [0]
'prc' column not found for /TSLA/meta/values_block_0/meta. Available columns: [0]
Columns for /TSCO/meta/values_block_0/meta: [0]
'prc' column not found for /TSCO/meta/values_block_0/meta. Available columns: [0]
Columns for /TRV/meta/values_block_0/meta: [0]
'prc' column not found for /TRV/meta/values_block_0/meta. Available columns: [0]
Columns for /TRU/meta/values_block_0/meta: [0]
'prc' column not found for /TRU/meta/values_block_0/meta. Available columns: [0]
Columns for /TROW/meta/values_block_0/meta: [0]
'prc' column not found for /TROW/meta/values_block_0/meta. Available columns: [0]
Columns for /TRMB/meta/values_block_0/meta: [0]
'prc' column not found for /TRMB/meta/values_block_0/meta. Available columns: [0]
Columns for /TRIP/meta/values_block_0/meta: [0]
'prc' column not found for /TRIP/meta/values_block_0/meta. Available columns: [0]
Columns for /TRGP/meta/values_block_0/meta: [0]
'prc' column not found for /TRGP/meta/values_block_0/meta. Available columns: [0]
Columns for /TREX/meta/values_block_0/meta: [0]
'prc' column not found for /TREX/meta/values_block_0/meta. Available columns: [0]
Columns for /TPX/meta/values_block_0/meta: [0]
'prc' column not found for /TPX/meta/values_block_0/meta. Available columns: [0]
Columns for /TPR/meta/values_block_0/meta: [0]
'prc' column not found for /TPR/meta/values_block_0/meta. Available columns: [0]
Columns for /TPL/meta/values_block_0/meta: [0]
'prc' column not found for /TPL/meta/values_block_0/meta. Available columns: [0]
Columns for /TPG/meta/values_block_0/meta: [0]
'prc' column not found for /TPG/meta/values_block_0/meta. Available columns: [0]
Columns for /TOST/meta/values_block_0/meta: [0]
'prc' column not found for /TOST/meta/values_block_0/meta. Available columns: [0]
Columns for /TOL/meta/values_block_0/meta: [0]
'prc' column not found for /TOL/meta/values_block_0/meta. Available columns: [0]
Columns for /TNL/meta/values_block_0/meta: [0]
'prc' column not found for /TNL/meta/values_block_0/meta. Available columns: [0]
Columns for /TMUS/meta/values_block_0/meta: [0]
'prc' column not found for /TMUS/meta/values_block_0/meta. Available columns: [0]
Columns for /TMO/meta/values_block_0/meta: [0]

In [17]:
# Check for duplicates in returns
for ticker, data in stock_data.items():
    
    r_vol =\
    (
        data['r_vol']
    )
    
    # Check for duplicates
    if r_vol.index.duplicated().any():
        
        print(f"Duplicates found in returns for {ticker}. Resolving...")
        
        r_vol =\
        (
            r_vol[~r_vol.index.duplicated(keep='first')]  # Keep the first occurrence
        )
        
    # Check for duplicates in Fama-French factors
    if fama_french.index.duplicated().any():
        
        print("Duplicates found in Fama-French factors. Resolving...")
        
        fama_french =\
        (
            fama_french[~fama_french.index.duplicated(keep='first')]  # Keep the first occurrence
        )

    # Align with Fama-French factors
    aligned_r_vol =\
    (
        r_vol
        .reindex(fama_french.index)
        .dropna()
    )
    
    aligned_factors =\
    (
        fama_french
        .loc[aligned_r_vol.index] # Align factors with returns
    )

    # Now both aligned_returns and aligned_factors have the same index
    print(f"Aligned returns for {ticker}:\n{aligned_r_vol.head()}")
    
    print(f"Aligned Fama-French factors:\n{aligned_factors.head()}")
    
    # Fit the GARCH-X model
    model =\
    (
        arch_model(aligned_r_vol,
                   vol='Garch',
                   p=1, 
                   q=1,
                   x=aligned_factors.values,
                   dist='Normal')
    )
    
    try:
        results =\
        (
            model
            .fit(disp='off')
        )
        
        print(f"Results for {ticker}:")
        
        print(results.summary())
        
    except Exception as e:
        
        print(f"Error fitting GARCH model for {ticker}: {e}")

Aligned returns for /A:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /A: first_obs and last_obs produce in an empty array.
Aligned returns for /AA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AA: first_obs and last_obs produce in an empty array.
Aligned returns for /AAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AAL: first_obs and last_obs produce in an empty array.
Aligned returns for /AAON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AAON: first_obs and last_obs produce in an empty array.
Aligned returns for /AAP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AAP: first_obs and last_obs produce in an empty array.
Aligned returns for /AAPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AAPL: first_obs and last_obs produce in an empty array.
Aligned returns for /ABBV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ABBV: first_obs and last_obs produce in an empty array.
Aligned returns for /ABNB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ABNB: first_obs and last_obs produce in an empty array.
Aligned returns for /ABT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ABT: first_obs and last_obs produce in an empty array.
Aligned returns for /ACGL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ACGL: first_obs and last_obs produce in an empty array.
Aligned returns for /ACHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ACHC: first_obs and last_obs produce in an empty array.
Aligned returns for /ACI:
Date
2001-02-01    0.707943
2001-03-01    0.734087
2001-05-01    0.704425
2001-06-01    0.595842
2001-08-01    0.639726
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /ACI:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                46.7552
Distribution:                  Normal   AIC:                          -85.5105
Method:            Maximum Likelihood   BIC:                          -74.6009
                                        No. Observations:                  113
Date:                Sun, Oct 13 2024   Df Residuals:                      112
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4941  1.192e-02     41.444      0.000 [  0.471,  0.517]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      8.8464e-04  7.705e-04      1.148      0.251 [-6.256e-04,2.395e-03]
alpha[1]       0.9937      0.221      4.494  7.002e-06      [  0.560,  1.427]
beta[1]    6.3050e-03  1.106e-02      0.570      0.569 [-1.537e-02,2.798e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /ACM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ACM: first_obs and last_obs produce in an empty array.
Aligned returns for /ACN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ACN: first_obs and last_obs produce in an empty array.
Aligned returns for /ADBE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ADBE: first_obs and last_obs produce in an empty array.
Aligned returns for /ADC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ADC: first_obs and last_obs produce in an empty array.
Aligned returns for /ADI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ADI: first_obs and last_obs produce in an empty array.
Aligned returns for /ADM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ADM: first_obs and last_obs produce in an empty array.
Aligned returns for /ADP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ADP: first_obs and last_obs produce in an empty array.
Aligned returns for /ADSK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ADSK: first_obs and last_obs produce in an empty array.
Aligned returns for /ADT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ADT: first_obs and last_obs produce in an empty array.
Aligned returns for /AEE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AEE: first_obs and last_obs produce in an empty array.
Aligned returns for /AEP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AEP: first_obs and last_obs produce in an empty array.
Aligned returns for /AES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AES: first_obs and last_obs produce in an empty array.
Aligned returns for /AFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AFG: first_obs and last_obs produce in an empty array.
Aligned returns for /AFL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AFL: first_obs and last_obs produce in an empty array.
Aligned returns for /AFRM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AFRM: first_obs and last_obs produce in an empty array.
Aligned returns for /AGCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AGCO: first_obs and last_obs produce in an empty array.
Aligned returns for /AGNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AGNC: first_obs and last_obs produce in an empty array.
Aligned returns for /AGO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AGO: first_obs and last_obs produce in an empty array.
Aligned returns for /AGR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AGR: first_obs and last_obs produce in an empty array.
Aligned returns for /AIG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AIG: first_obs and last_obs produce in an empty array.
Aligned returns for /AIZ:
Date
2001-02-01    0.509010
2001-03-01    0.520975
2001-05-01    0.489626
2001-06-01    0.463068
2001-08-01    0.431151
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /AIZ:

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.009579. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.003327. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.03701. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.09065. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                17.3883
Distribution:                  Normal   AIC:                          -26.7767
Method:            Maximum Likelihood   BIC:                          -23.9445
                                        No. Observations:                   15
Date:                Sun, Oct 13 2024   Df Residuals:                       14
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4291  8.528e-02      5.031  4.872e-07 [  0.262,  0.596]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      5.6416e-04  2.120e-03      0.266      0.790 [-3.590e-03,4.718e-03]
alpha[1]       1.0000      3.502      0.286      0.775      [ -5.864,  7.864]
beta[1]        0.0000      3.290      0.000      1.000      [ -6.448,  6.448]
=============================================================================

Covariance estimator: robust
Aligned returns for /AJG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AJG: first_obs and last_obs produce in an empty array.
Aligned returns for /AKAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AKAM: first_obs and last_obs produce in an empty array.
Aligned returns for /AL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AL: first_obs and last_obs produce in an empty array.
Aligned returns for /ALAB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALAB: first_obs and last_obs produce in an empty array.
Aligned returns for /ALB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALB: first_obs and last_obs produce in an empty array.
Aligned returns for /ALGM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALGM: first_obs and last_obs produce in an empty array.
Aligned returns for /ALGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALGN: first_obs and last_obs produce in an empty array.
Aligned returns for /ALK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALK: first_obs and last_obs produce in an empty array.
Aligned returns for /ALL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALL: first_obs and last_obs produce in an empty array.
Aligned returns for /ALLE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALLE: first_obs and last_obs produce in an empty array.
Aligned returns for /ALLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALLY: first_obs and last_obs produce in an empty array.
Aligned returns for /ALNY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALNY: first_obs and last_obs produce in an empty array.
Aligned returns for /ALSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ALSN: first_obs and last_obs produce in an empty array.
Aligned returns for /AM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AM: first_obs and last_obs produce in an empty array.
Aligned returns for /AMAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMAT: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /AMCR. Resolving...
Aligned returns for /AMCR:
Date
2001-02-01    0.477408
2001-03-01    0.458253
2001-05-01    0.365784
2001-06-01    0.354772
2001-08-01    0.335131
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /AMCR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                95.7810
Distribution:                  Normal   AIC:                          -183.562
Method:            Maximum Likelihood   BIC:                          -175.914
                                        No. Observations:                   50
Date:                Sun, Oct 13 2024   Df Residuals:                       49
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2475  2.302e-03    107.539      0.000 [  0.243,  0.252]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.6949e-05  6.080e-05      1.101      0.271 [-5.221e-05,1.861e-04]
alpha[1]       0.1998      0.126      1.583      0.114   [-4.763e-02,  0.447]
beta[1]        0.7792  3.663e-02     21.272 2.081e-100      [  0.707,  0.851]
=============================================================================

Covariance estimator: robust
Aligned returns for /AMD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMD: first_obs and last_obs produce in an empty array.
Aligned returns for /AME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AME: first_obs and last_obs produce in an empty array.
Aligned returns for /AMED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMED: first_obs and last_obs produce in an empty array.
Aligned returns for /AMG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMG: first_obs and last_obs produce in an empty array.
Aligned returns for /AMGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMGN: first_obs and last_obs produce in an empty array.
Aligned returns for /AMH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMH: first_obs and last_obs produce in an empty array.
Aligned returns for /AMKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMKR: first_obs and last_obs produce in an empty array.
Aligned returns for /AMP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMP: first_obs and last_obs produce in an empty array.
Aligned returns for /AMT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMT: first_obs and last_obs produce in an empty array.
Aligned returns for /AMZN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AMZN: first_obs and last_obs produce in an empty array.
Aligned returns for /AN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AN: first_obs and last_obs produce in an empty array.
Aligned returns for /ANET:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ANET: first_obs and last_obs produce in an empty array.
Aligned returns for /ANSS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ANSS: first_obs and last_obs produce in an empty array.
Aligned returns for /AON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AON: first_obs and last_obs produce in an empty array.
Aligned returns for /AOS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AOS: first_obs and last_obs produce in an empty array.
Aligned returns for /APA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /APA: first_obs and last_obs produce in an empty array.
Aligned returns for /APD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /APD: first_obs and last_obs produce in an empty array.
Aligned returns for /APG:
Date
2001-03-01    1.531621
2001-05-01    1.595551
2001-06-01    1.528926
2001-08-01    1.501291
2001-10-01    1.605932
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
2001-10-01  0.0748 -0.0765
Results for /APG:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                2.58292
Distribution:                  Normal   AIC:                           2.83415
Method:            Maximum Likelihood   BIC:                           3.62305
                                        No. Observations:                    9
Date:                Sun, Oct 13 2024   Df Residuals:                        8
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.6306      0.217      7.503  6.232e-14 [  1.205,  2.057]
                            Volatility Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
omega      2.6665e-03  8.932e-02  2.985e-02      0.976 [ -0.172,  0.178]
alpha[1]       0.0000      2.203      0.000      1.000 [ -4.317,  4.317]
beta[1]        1.0000      1.798      0.556      0.578 [ -2.523,  4.523]
========================================================================

Covariance estimator: robust
Aligned returns for /APH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /APH: first_obs and last_obs produce in an empty array.
Aligned returns for /APLS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /APLS: first_obs and last_obs produce in an empty array.
Aligned returns for /APO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /APO: first_obs and last_obs produce in an empty array.
Aligned returns for /APP:
Date
2007-05-01    0.263958
2007-06-01    0.279184
2007-08-01    0.302757
2007-10-01    0.338877
2007-11-01    0.341331
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2007-05-01  0.0024 -0.0065
2007-06-01  0.0075 -0.0105
2007-08-01 -0.0013 -0.0186
2007-10-01  0.0008 -0.0298
2007-11-01 -0.0293 -0.0094
Results for /APP:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                6.86448
Distribution:                  Normal   AIC:                          -5.72896
Method:            Maximum Likelihood   BIC:                           2.90657
                                        No. Observations:                   64
Date:                Sun, Oct 13 2024   Df Residuals:                       63
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8828  4.300e-02     20.530  1.173e-93 [  0.799,  0.967]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      4.3786e-03  6.414e-03      0.683      0.495 [-8.193e-03,1.695e-02]
alpha[1]       1.0000      0.684      1.461      0.144      [ -0.341,  2.341]
beta[1]        0.0000      0.631      0.000      1.000      [ -1.237,  1.237]
=============================================================================

Covariance estimator: robust
Aligned returns for /APPF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /APPF: first_obs and last_obs produce in an empty array.
Aligned returns for /APTV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /APTV: first_obs and last_obs produce in an empty array.
Aligned returns for /AR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AR: first_obs and last_obs produce in an empty array.
Aligned returns for /ARE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ARE: first_obs and last_obs produce in an empty array.
Aligned returns for /ARES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ARES: first_obs and last_obs produce in an empty array.
Aligned returns for /ARMK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ARMK: first_obs and last_obs produce in an empty array.
Aligned returns for /ARW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ARW: first_obs and last_obs produce in an empty array.
Aligned returns for /ASH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ASH: first_obs and last_obs produce in an empty array.
Aligned returns for /ATI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ATI: first_obs and last_obs produce in an empty array.
Aligned returns for /ATO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ATO: first_obs and last_obs produce in an empty array.
Aligned returns for /ATR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ATR: first_obs and last_obs produce in an empty array.
Aligned returns for /AVB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AVB: first_obs and last_obs produce in an empty array.
Aligned returns for /AVGO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AVGO: first_obs and last_obs produce in an empty array.
Aligned returns for /AVT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AVT: first_obs and last_obs produce in an empty array.
Aligned returns for /AVTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AVTR: first_obs and last_obs produce in an empty array.
Aligned returns for /AVY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []

Error fitting GARCH model for /AVY: first_obs and last_obs produce in an empty array.
Aligned returns for /AWI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AWI: first_obs and last_obs produce in an empty array.
Aligned returns for /AWK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AWK: first_obs and last_obs produce in an empty array.
Aligned returns for /AXON:
Date
2016-07-01    0.832911
2016-08-01    0.796160
2016-09-01    0.740765
2016-11-01    0.660786
2016-12-01    0.647598
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2016-07-01  0.0249 -0.0132
2016-08-01  0.0116  0.0318
2016-09-01  0.0212 -0.0124
2016-11-01  0.0571  0.0821
2016-12-01  0.0010  0.0353
Results for /AXON:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -13.6801
Distribution:                  Normal   AIC:                           35.3602
Method:            Maximum Likelihood   BIC:                           43.3895
                                        No. Observations:                   55
Date:                Sun, Oct 13 2024   Df Residuals:                       54
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.9813      0.117      8.365  6.001e-17 [  0.751,  1.211]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.6376e-03  1.100e-02      0.603      0.546 [-1.493e-02,2.821e-02]
alpha[1]       0.9983      0.322      3.102  1.920e-03      [  0.368,  1.629]
beta[1]    1.6628e-03  1.316e-02      0.126      0.899 [-2.413e-02,2.746e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /AXP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AXP: first_obs and last_obs produce in an empty array.
Aligned returns for /AXS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AXS: first_obs and last_obs produce in an empty array.
Aligned returns for /AXTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AXTA: first_obs and last_obs produce in an empty array.
Aligned returns for /AYI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AYI: first_obs and last_obs produce in an empty array.
Aligned returns for /AZEK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AZEK: first_obs and last_obs produce in an empty array.
Aligned returns for /AZO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AZO: first_obs and last_obs produce in an empty array.
Aligned returns for /AZPN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AZPN: first_obs and last_obs produce in an empty array.
Aligned returns for /AZTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /AZTA: first_obs and last_obs produce in an empty array.
Aligned returns for /BA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BA: first_obs and last_obs produce in an empty array.
Aligned returns for /BAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BAC: first_obs and last_obs produce in an empty array.
Aligned returns for /BAH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BAH: first_obs and last_obs produce in an empty array.
Aligned returns for /BALL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BALL: first_obs and last_obs produce in an empty array.
Aligned returns for /BAX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BAX: first_obs and last_obs produce in an empty array.
Aligned returns for /BBWI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BBWI: first_obs and last_obs produce in an empty array.
Aligned returns for /BBY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BBY: first_obs and last_obs produce in an empty array.
Aligned returns for /BC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BC: first_obs and last_obs produce in an empty array.
Aligned returns for /BDX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BDX: first_obs and last_obs produce in an empty array.
Aligned returns for /BEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BEN: first_obs and last_obs produce in an empty array.
Aligned returns for /BEPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BEPC: first_obs and last_obs produce in an empty array.
Aligned returns for /BERY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BERY: first_obs and last_obs produce in an empty array.
Aligned returns for /BFAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BFAM: first_obs and last_obs produce in an empty array.
Aligned returns for /BG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BG: first_obs and last_obs produce in an empty array.
Aligned returns for /BHF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BHF: first_obs and last_obs produce in an empty array.
Aligned returns for /BIIB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BIIB: first_obs and last_obs produce in an empty array.
Aligned returns for /BILL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BILL: first_obs and last_obs produce in an empty array.
Aligned returns for /BIO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BIO: first_obs and last_obs produce in an empty array.
Aligned returns for /BIRK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BIRK: first_obs and last_obs produce in an empty array.
Aligned returns for /BJ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BJ: first_obs and last_obs produce in an empty array.
Aligned returns for /BK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BK: first_obs and last_obs produce in an empty array.
Aligned returns for /BKNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BKNG: first_obs and last_obs produce in an empty array.
Aligned returns for /BKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BKR: first_obs and last_obs produce in an empty array.
Aligned returns for /BLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BLD: first_obs and last_obs produce in an empty array.
Aligned returns for /BLDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BLDR: first_obs and last_obs produce in an empty array.
Aligned returns for /BLK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BLK: first_obs and last_obs produce in an empty array.
Aligned returns for /BMRN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BMRN: first_obs and last_obs produce in an empty array.
Aligned returns for /BMY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BMY: first_obs and last_obs produce in an empty array.
Aligned returns for /BOKF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BOKF: first_obs and last_obs produce in an empty array.
Aligned returns for /BPOP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BPOP: first_obs and last_obs produce in an empty array.
Aligned returns for /BR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BR: first_obs and last_obs produce in an empty array.
Aligned returns for /BRBR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BRBR: first_obs and last_obs produce in an empty array.
Aligned returns for /BRKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BRKR: first_obs and last_obs produce in an empty array.
Aligned returns for /BRO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BRO: first_obs and last_obs produce in an empty array.
Aligned returns for /BROS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BROS: first_obs and last_obs produce in an empty array.
Aligned returns for /BRX:
Date
2001-02-01    1.774877
2001-03-01    1.870316
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
Results for /BRX:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                3.24696
Distribution:                  Normal   AIC:                           1.50609
Method:            Maximum Likelihood   BIC:                          -3.72132
                                        No. Observations:                    2
Date:                Sun, Oct 13 2024   Df Residuals:                        1
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.8226  5.359e-02     34.012 1.472e-253 [  1.718,  1.928]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.8314e-04  4.084e-05     16.729  8.035e-63  [6.031e-04,7.632e-04]
alpha[1]       0.0100  3.253e-02      0.307      0.759 [-5.376e-02,7.376e-02]
beta[1]        0.6900      0.397      1.737  8.230e-02   [-8.835e-02,  1.468]
=============================================================================

Covariance estimator: robust
Aligned returns for /BSX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BSX: first_obs and last_obs produce in an empty array.
Aligned returns for /BSY:
Date
2001-06-01    0.616888
2001-08-01    0.556224
2002-02-01    0.443440
2002-03-01    0.448809
2002-04-01    0.447160
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
2002-02-01 -0.0101  0.0216
2002-03-01  0.0421  0.0106
2002-04-01  0.0596  0.0388
Results for /BSY:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                63.0077
Distribution:                  Normal   AIC:                          -118.015
Method:            Maximum Likelihood   BIC:                          -109.318
                                        No. Observations:                   65
Date:                Sun, Oct 13 2024   Df Residuals:                       64
Time:                        22:28:01   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2731  1.731e-02     15.780  4.302e-56 [  0.239,  0.307]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      4.8494e-04  2.949e-04      1.645      0.100 [-9.302e-05,1.063e-03]
alpha[1]       1.0000      0.178      5.626  1.844e-08      [  0.652,  1.348]
beta[1]    5.3324e-12  1.355e-02  3.936e-10      1.000 [-2.655e-02,2.655e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /BURL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BURL: first_obs and last_obs produce in an empty array.
Aligned returns for /BWA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BWA: first_obs and last_obs produce in an empty array.
Aligned returns for /BWXT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BWXT: first_obs and last_obs produce in an empty array.
Aligned returns for /BX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BX: first_obs and last_obs produce in an empty array.

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.002277. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02052. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.04854. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.001861. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Aligned returns for /BXP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BXP: first_obs and last_obs produce in an empty array.
Aligned returns for /BYD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BYD: first_obs and last_obs produce in an empty array.
Aligned returns for /C:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /C: first_obs and last_obs produce in an empty array.
Aligned returns for /CACC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CACC: first_obs and last_obs produce in an empty array.
Aligned returns for /CACI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CACI: first_obs and last_obs produce in an empty array.
Aligned returns for /CAG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CAG: first_obs and last_obs produce in an empty array.
Aligned returns for /CAH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CAH: first_obs and last_obs produce in an empty array.
Aligned returns for /CAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CAR: first_obs and last_obs produce in an empty array.
Aligned returns for /CARR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CARR: first_obs and last_obs produce in an empty array.
Aligned returns for /CART:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CART: first_obs and last_obs produce in an empty array.
Aligned returns for /CASY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CASY: first_obs and last_obs produce in an empty array.
Aligned returns for /CAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CAT: first_obs and last_obs produce in an empty array.
Aligned returns for /CAVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CAVA: first_obs and last_obs produce in an empty array.
Aligned returns for /CB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CB: first_obs and last_obs produce in an empty array.
Aligned returns for /CBOE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CBOE: first_obs and last_obs produce in an empty array.
Aligned returns for /CBRE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CBRE: first_obs and last_obs produce in an empty array.
Aligned returns for /CBSH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CBSH: first_obs and last_obs produce in an empty array.
Aligned returns for /CC:
Date
2001-02-01    0.951103
2001-03-01    0.943813
2001-05-01    0.942430
2001-06-01    0.936315
2001-08-01    0.851864
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /CC:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                31.6617
Distribution:                  Normal   AIC:                          -55.3234
Method:            Maximum Likelihood   BIC:                          -47.0132
                                        No. Observations:                   59
Date:                Sun, Oct 13 2024   Df Residuals:                       58
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3675  2.137e-02     17.198  2.766e-66 [  0.326,  0.409]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      8.3767e-04  5.521e-04      1.517      0.129 [-2.444e-04,1.920e-03]
alpha[1]       1.0000      0.209      4.787  1.689e-06      [  0.591,  1.409]
beta[1]    3.8342e-09      0.242  1.586e-08      1.000      [ -0.474,  0.474]
=============================================================================

Covariance estimator: robust
Aligned returns for /CCCS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CCCS: first_obs and last_obs produce in an empty array.
Aligned returns for /CCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CCI: first_obs and last_obs produce in an empty array.
Aligned returns for /CCK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CCK: first_obs and last_obs produce in an empty array.
Aligned returns for /CCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CCL: first_obs and last_obs produce in an empty array.
Aligned returns for /CDNS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CDNS: first_obs and last_obs produce in an empty array.
Aligned returns for /CDW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CDW: first_obs and last_obs produce in an empty array.
Aligned returns for /CE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CE: first_obs and last_obs produce in an empty array.
Aligned returns for /CEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CEG: first_obs and last_obs produce in an empty array.
Aligned returns for /CELH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CELH: first_obs and last_obs produce in an empty array.
Aligned returns for /CERT:
Date
2001-06-01    1.324206
2001-08-01    1.304222
2001-10-01    1.367372
2001-11-01    1.383116
2002-02-01    1.339929
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
2001-10-01  0.0748 -0.0765
2001-11-01 -0.0047  0.0221
2002-02-01 -0.0101  0.0216
Results for /CERT:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                13.9934
Distribution:                  Normal   AIC:                          -19.9869
Method:            Maximum Likelihood   BIC:                          -19.6691
                                        No. Observations:                    8
Date:                Sun, Oct 13 2024   Df Residuals:                        7
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.3236  1.367e-02     96.856      0.000 [  1.297,  1.350]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.0914e-04  1.634e-03  6.679e-02      0.947 [-3.093e-03,3.312e-03]
alpha[1]       0.0000      0.696      0.000      1.000      [ -1.364,  1.364]
beta[1]        1.0000      1.032      0.969      0.333      [ -1.023,  3.023]
=============================================================================

Covariance estimator: robust
Aligned returns for /CF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CF: first_obs and last_obs produce in an empty array.
Aligned returns for /CFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CFG: first_obs and last_obs produce in an empty array.
Aligned returns for /CFLT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CFLT: first_obs and last_obs produce in an empty array.
Aligned returns for /CFR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CFR: first_obs and last_obs produce in an empty array.
Aligned returns for /CG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CG: first_obs and last_obs produce in an empty array.
Aligned returns for /CGNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CGNX: first_obs and last_obs produce in an empty array.
Aligned returns for /CHD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CHD: first_obs and last_obs produce in an empty array.
Aligned returns for /CHDN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CHDN: first_obs and last_obs produce in an empty array.
Aligned returns for /CHE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CHE: first_obs and last_obs produce in an empty array.
Aligned returns for /CHH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CHH: first_obs and last_obs produce in an empty array.
Aligned returns for /CHK:
Date
2001-02-01    0.730042
2001-03-01    0.707885
2001-05-01    0.689540
2001-06-01    0.660812
2001-08-01    0.637983
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /CHK:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                67.8962
Distribution:                  Normal   AIC:                          -127.792
Method:            Maximum Likelihood   BIC:                          -115.804
                                        No. Observations:                  148
Date:                Sun, Oct 13 2024   Df Residuals:                      147
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3295  1.762e-02     18.703  4.654e-78 [  0.295,  0.364]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.8463e-04  1.369e-03      0.500      0.617 [-1.998e-03,3.367e-03]
alpha[1]       1.0000      0.487      2.052  4.015e-02    [4.495e-02,  1.955]
beta[1]    4.2723e-13      0.926  4.614e-13      1.000      [ -1.815,  1.815]
=============================================================================

Covariance estimator: robust
Aligned returns for /CHRD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CHRD: first_obs and last_obs produce in an empty array.
Aligned returns for /CHRW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CHRW: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /CHTR. Resolving...
Aligned returns for /CHTR:
Date
2001-02-01    0.880202
2001-03-01    0.926915
2001-05-01    0.969546
2001-06-01    0.971322
2001-08-01    0.766142
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06548. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01226. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /CHTR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                69.6722
Distribution:                  Normal   AIC:                          -131.344
Method:            Maximum Likelihood   BIC:                          -122.128
                                        No. Observations:                   74
Date:                Sun, Oct 13 2024   Df Residuals:                       73
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4670  8.536e-03     54.711      0.000 [  0.450,  0.484]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.8308e-04  1.325e-04      2.891  3.840e-03 [1.234e-04,6.428e-04]
alpha[1]       1.0000      0.431      2.321  2.029e-02     [  0.156,  1.844]
beta[1]        0.0000      0.352      0.000      1.000     [ -0.689,  0.689]
============================================================================

Covariance estimator: robust
Aligned returns for /CI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CI: first_obs and last_obs produce in an empty array.
Aligned returns for /CIEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CIEN: first_obs and last_obs produce in an empty array.
Aligned returns for /CINF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CINF: first_obs and last_obs produce in an empty array.
Aligned returns for /CIVI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CIVI: first_obs and last_obs produce in an empty array.
Aligned returns for /CL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CL: first_obs and last_obs produce in an empty array.
Aligned returns for /CLF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CLF: first_obs and last_obs produce in an empty array.
Aligned returns for /CLH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CLH: first_obs and last_obs produce in an empty array.
Aligned returns for /CLVT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CLVT: first_obs and last_obs produce in an empty array.
Aligned returns for /CLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CLX: first_obs and last_obs produce in an empty array.
Aligned returns for /CMA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CMA: first_obs and last_obs produce in an empty array.
Aligned returns for /CMCSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CMCSA: first_obs and last_obs produce in an empty array.
Aligned returns for /CME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CME: first_obs and last_obs produce in an empty array.
Aligned returns for /CMG:
Date
2001-02-01    0.637471
2001-03-01    0.636522
2001-05-01    0.666707
2001-06-01    0.648308
2001-08-01    0.642755
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /CMG:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                67.3702
Distribution:                  Normal   AIC:                          -126.740
Method:            Maximum Likelihood   BIC:                          -114.833
                                        No. Observations:                  145
Date:                Sun, Oct 13 2024   Df Residuals:                      144
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4775  7.534e-03     63.375      0.000 [  0.463,  0.492]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      8.1406e-04  4.819e-04      1.689  9.113e-02 [-1.304e-04,1.758e-03]
alpha[1]       1.0000      0.135      7.396  1.402e-13      [  0.735,  1.265]
beta[1]    8.7058e-06      0.116  7.532e-05      1.000      [ -0.227,  0.227]
=============================================================================

Covariance estimator: robust
Aligned returns for /CMI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CMI: first_obs and last_obs produce in an empty array.
Aligned returns for /CMS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CMS: first_obs and last_obs produce in an empty array.
Aligned returns for /CNA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CNA: first_obs and last_obs produce in an empty array.
Aligned returns for /CNC:
Date
2001-02-01    1.056399
2001-03-01    1.053785
2001-05-01    0.916625
2001-06-01    0.819267
2001-08-01    0.713136
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /CNC:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                10.1933
Distribution:                  Normal   AIC:                          -12.3867
Method:            Maximum Likelihood   BIC:                          -10.1269
                                        No. Observations:                   13
Date:                Sun, Oct 13 2024   Df Residuals:                       12
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.9091  3.291e-02     27.626 5.494e-168 [  0.845,  0.974]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      2.1432e-03  2.931e-03      0.731      0.465 [-3.601e-03,7.888e-03]
alpha[1]   8.5200e-16  1.133e-02  7.520e-14      1.000 [-2.221e-02,2.221e-02]
beta[1]        0.8051      0.266      3.031  2.440e-03      [  0.284,  1.326]
=============================================================================

Covariance estimator: robust
Aligned returns for /CNH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CNH: first_obs and last_obs produce in an empty array.
Aligned returns for /CNM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CNM: first_obs and last_obs produce in an empty array.
Aligned returns for /CNP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CNP: first_obs and last_obs produce in an empty array.
Aligned returns for /CNXC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CNXC: first_obs and last_obs produce in an empty array.
Aligned returns for /COF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COF: first_obs and last_obs produce in an empty array.
Aligned returns for /COHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COHR: first_obs and last_obs produce in an empty array.
Aligned returns for /COIN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COIN: first_obs and last_obs produce in an empty array.
Aligned returns for /COKE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COKE: first_obs and last_obs produce in an empty array.
Aligned returns for /COLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COLB: first_obs and last_obs produce in an empty array.
Aligned returns for /COLD:
Date
2002-10-01    0.868534
2003-07-01    0.885346
2003-10-01    1.035784
2004-06-01    1.347934
2004-07-01    1.330134
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2002-10-01 -0.0342 -0.0394
2003-07-01  0.0506 -0.0124
2003-10-01  0.0269  0.0197
2004-06-01  0.0226  0.0118
2004-07-01 -0.0382  0.0324
Results for /COLD:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:             -0.0852117
Distribution:                  Normal   AIC:                           8.17042
Method:            Maximum Likelihood   BIC:                           14.7208
                                        No. Observations:                   38
Date:                Sun, Oct 13 2024   Df Residuals:                       37
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7793  1.276e-02     61.055      0.000 [  0.754,  0.804]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      9.8785e-04  7.729e-04      1.278      0.201 [-5.269e-04,2.503e-03]
alpha[1]       1.0000      0.126      7.940  2.015e-15      [  0.753,  1.247]
beta[1]    3.1398e-17  1.075e-02  2.920e-15      1.000 [-2.107e-02,2.107e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /COLM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COLM: first_obs and last_obs produce in an empty array.
Aligned returns for /COO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COO: first_obs and last_obs produce in an empty array.
Aligned returns for /COP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COP: first_obs and last_obs produce in an empty array.
Aligned returns for /COR:
Date
2002-07-01    0.746987
2002-08-01    0.822922
2002-10-01    0.869867
2002-11-01    0.918095
2003-04-01    0.997172
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2002-07-01 -0.0528 -0.0385
2002-08-01 -0.0286  0.0328
2002-10-01 -0.0342 -0.0394
2002-11-01  0.0319 -0.0126
2003-04-01  0.0062  0.0115

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.05978. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /COR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                18.2974
Distribution:                  Normal   AIC:                          -28.5948
Method:            Maximum Likelihood   BIC:                          -20.4933
                                        No. Observations:                   56
Date:                Sun, Oct 13 2024   Df Residuals:                       55
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.0473  1.783e-02     58.750      0.000 [  1.012,  1.082]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      2.7279e-03  1.775e-03      1.537      0.124 [-7.506e-04,6.206e-03]
alpha[1]       1.0000      0.333      3.003  2.675e-03      [  0.347,  1.653]
beta[1]        0.0000      0.163      0.000      1.000      [ -0.319,  0.319]
=============================================================================

Covariance estimator: robust
Aligned returns for /COST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COST: first_obs and last_obs produce in an empty array.
Aligned returns for /COTY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /COTY: first_obs and last_obs produce in an empty array.
Aligned returns for /CPB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CPB: first_obs and last_obs produce in an empty array.
Aligned returns for /CPNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CPNG: first_obs and last_obs produce in an empty array.
Aligned returns for /CPRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CPRI: first_obs and last_obs produce in an empty array.
Aligned returns for /CPRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CPRT: first_obs and last_obs produce in an empty array.
Aligned returns for /CPT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CPT: first_obs and last_obs produce in an empty array.
Aligned returns for /CR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CR: first_obs and last_obs produce in an empty array.
Aligned returns for /CRBG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CRBG: first_obs and last_obs produce in an empty array.
Aligned returns for /CRH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CRH: first_obs and last_obs produce in an empty array.
Aligned returns for /CRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CRI: first_obs and last_obs produce in an empty array.
Aligned returns for /CRL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CRL: first_obs and last_obs produce in an empty array.
Aligned returns for /CRM:
Date
2001-06-01    3.159167
2001-08-01    3.133609
2001-10-01    3.130844
2001-11-01    3.098733
2002-04-01    0.857164
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
2001-10-01  0.0748 -0.0765
2001-11-01 -0.0047  0.0221
2002-04-01  0.0596  0.0388
Results for /CRM:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2.00387
Distribution:                  Normal   AIC:                           12.0077
Method:            Maximum Likelihood   BIC:                           12.7966
                                        No. Observations:                    9
Date:                Sun, Oct 13 2024   Df Residuals:                        8
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.0708      0.193      5.552  2.822e-08 [  0.693,  1.449]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      4.8402e-04  1.214e-02  3.986e-02      0.968 [-2.331e-02,2.428e-02]
alpha[1]       1.0000     10.466  9.555e-02      0.924      [-19.513, 21.513]
beta[1]    2.9294e-08      0.862  3.397e-08      1.000      [ -1.690,  1.690]
=============================================================================

Covariance estimator: robust
Aligned returns for /CROX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CROX: first_obs and last_obs produce in an empty array.
Aligned returns for /CRUS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CRUS: first_obs and last_obs produce in an empty array.
Aligned returns for /CRWD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CRWD: first_obs and last_obs produce in an empty array.
Aligned returns for /CSCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CSCO: first_obs and last_obs produce in an empty array.
Aligned returns for /CSGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CSGP: first_obs and last_obs produce in an empty array.
Aligned returns for /CSL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CSL: first_obs and last_obs produce in an empty array.
Aligned returns for /CSX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CSX: first_obs and last_obs produce in an empty array.
Aligned returns for /CTAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CTAS: first_obs and last_obs produce in an empty array.
Aligned returns for /CTLT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CTLT: first_obs and last_obs produce in an empty array.
Aligned returns for /CTRA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CTRA: first_obs and last_obs produce in an empty array.
Aligned returns for /CTSH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CTSH: first_obs and last_obs produce in an empty array.
Aligned returns for /CTVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CTVA: first_obs and last_obs produce in an empty array.
Aligned returns for /CUBE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CUBE: first_obs and last_obs produce in an empty array.
Aligned returns for /CUZ:
Date
2001-02-01    0.637471
2001-03-01    0.636522
2001-05-01    0.666707
2001-06-01    0.648308
2001-08-01    0.642755
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /CUZ:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                67.3702
Distribution:                  Normal   AIC:                          -126.740
Method:            Maximum Likelihood   BIC:                          -114.833
                                        No. Observations:                  145
Date:                Sun, Oct 13 2024   Df Residuals:                      144
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4775  7.534e-03     63.375      0.000 [  0.463,  0.492]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      8.1406e-04  4.819e-04      1.689  9.113e-02 [-1.304e-04,1.758e-03]
alpha[1]       1.0000      0.135      7.396  1.402e-13      [  0.735,  1.265]
beta[1]    8.7058e-06      0.116  7.532e-05      1.000      [ -0.227,  0.227]
=============================================================================

Covariance estimator: robust
Aligned returns for /CVNA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CVNA: first_obs and last_obs produce in an empty array.
Aligned returns for /CVS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CVS: first_obs and last_obs produce in an empty array.
Aligned returns for /CVX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CVX: first_obs and last_obs produce in an empty array.
Aligned returns for /CW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CW: first_obs and last_obs produce in an empty array.
Aligned returns for /CWEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CWEN: first_obs and last_obs produce in an empty array.
Aligned returns for /CXT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CXT: first_obs and last_obs produce in an empty array.
Aligned returns for /CZR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /CZR: first_obs and last_obs produce in an empty array.
Aligned returns for /D:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /D: first_obs and last_obs produce in an empty array.
Aligned returns for /DAL:
Date
2001-02-01    0.418388
2001-03-01    0.415557
2001-05-01    0.380793
2001-06-01    0.376230
2001-08-01    0.363144
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02463. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02688. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02441. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02552. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /DAL:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                29.3527
Distribution:                  Normal   AIC:                          -50.7054
Method:            Maximum Likelihood   BIC:                          -44.3714
                                        No. Observations:                   36
Date:                Sun, Oct 13 2024   Df Residuals:                       35
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7621  1.585e-02     48.083      0.000 [  0.731,  0.793]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.6212e-03  3.202e-03      0.506      0.613 [-4.655e-03,7.898e-03]
alpha[1]       0.9993      0.541      1.847  6.469e-02   [-6.089e-02,  2.059]
beta[1]    2.8099e-04  8.570e-02  3.279e-03      0.997      [ -0.168,  0.168]
=============================================================================

Covariance estimator: robust
Aligned returns for /DAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DAR: first_obs and last_obs produce in an empty array.
Aligned returns for /DASH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DASH: first_obs and last_obs produce in an empty array.
Aligned returns for /DAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DAY: first_obs and last_obs produce in an empty array.
Aligned returns for /DBX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DBX: first_obs and last_obs produce in an empty array.
Aligned returns for /DCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DCI: first_obs and last_obs produce in an empty array.
Aligned returns for /DD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DD: first_obs and last_obs produce in an empty array.
Aligned returns for /DDOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DDOG: first_obs and last_obs produce in an empty array.
Aligned returns for /DDS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DDS: first_obs and last_obs produce in an empty array.
Aligned returns for /DE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DE: first_obs and last_obs produce in an empty array.
Aligned returns for /DECK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DECK: first_obs and last_obs produce in an empty array.
Aligned returns for /DELL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DELL: first_obs and last_obs produce in an empty array.
Aligned returns for /DFS:
Date
2001-02-01    0.720486
2001-03-01    0.759028
2001-05-01    0.554367
2001-06-01    0.530705
2001-08-01    0.566921
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /DFS:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                42.4557
Distribution:                  Normal   AIC:                          -76.9114
Method:            Maximum Likelihood   BIC:                          -68.8100
                                        No. Observations:                   56
Date:                Sun, Oct 13 2024   Df Residuals:                       55
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4834  1.601e-02     30.198 2.524e-200 [  0.452,  0.515]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      5.0816e-04  6.877e-04      0.739      0.460 [-8.398e-04,1.856e-03]
alpha[1]       1.0000      0.108      9.274  1.785e-20      [  0.789,  1.211]
beta[1]        0.0000      0.117      0.000      1.000      [ -0.229,  0.229]
=============================================================================

Covariance estimator: robust
Aligned returns for /DG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DG: first_obs and last_obs produce in an empty array.
Aligned returns for /DGX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DGX: first_obs and last_obs produce in an empty array.
Aligned returns for /DHI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DHI: first_obs and last_obs produce in an empty array.
Aligned returns for /DHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DHR: first_obs and last_obs produce in an empty array.
Aligned returns for /DINO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DINO: first_obs and last_obs produce in an empty array.
Aligned returns for /DIS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DIS: first_obs and last_obs produce in an empty array.
Aligned returns for /DJT:
Date
2001-02-01    0.612917
2001-03-01    0.635783
2001-05-01    0.633854
2001-06-01    0.569852
2001-08-01    0.533976
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /DJT:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                17.1254
Distribution:                  Normal   AIC:                          -26.2507
Method:            Maximum Likelihood   BIC:                          -21.3752
                                        No. Observations:                   25
Date:                Sun, Oct 13 2024   Df Residuals:                       24
Time:                        22:28:02   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5935  5.523e-02     10.746  6.215e-27 [  0.485,  0.702]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.8386e-03  2.366e-03      1.622      0.105 [-7.988e-04,8.476e-03]
alpha[1]       0.7616      0.200      3.804  1.424e-04      [  0.369,  1.154]
beta[1]    3.9067e-11      0.348  1.121e-10      1.000      [ -0.683,  0.683]
=============================================================================

Covariance estimator: robust
Aligned returns for /DKNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DKNG: first_obs and last_obs produce in an empty array.
Aligned returns for /DKS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DKS: first_obs and last_obs produce in an empty array.
Aligned returns for /DLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DLB: first_obs and last_obs produce in an empty array.
Aligned returns for /DLR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DLR: first_obs and last_obs produce in an empty array.
Aligned returns for /DLTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DLTR: first_obs and last_obs produce in an empty array.
Aligned returns for /DNB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DNB: first_obs and last_obs produce in an empty array.
Aligned returns for /DOC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DOC: first_obs and last_obs produce in an empty array.
Aligned returns for /DOCS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DOCS: first_obs and last_obs produce in an empty array.
Aligned returns for /DOCU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DOCU: first_obs and last_obs produce in an empty array.
Aligned returns for /DOV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DOV: first_obs and last_obs produce in an empty array.
Aligned returns for /DOW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DOW: first_obs and last_obs produce in an empty array.
Aligned returns for /DOX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DOX: first_obs and last_obs produce in an empty array.
Aligned returns for /DPZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DPZ: first_obs and last_obs produce in an empty array.
Aligned returns for /DRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DRI: first_obs and last_obs produce in an empty array.
Aligned returns for /DT:
Date
2001-02-01    0.613568
2001-03-01    0.593936
2001-05-01    0.586756
2001-06-01    0.554126
2001-08-01    0.516149
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231

Results for /DT:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                76.5629
Distribution:                  Normal   AIC:                          -145.126
Method:            Maximum Likelihood   BIC:                          -136.075
                                        No. Observations:                   71
Date:                Sun, Oct 13 2024   Df Residuals:                       70
Time:                        22:28:02   Df Model:                            1
                                Mean Model
==========================================================================
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
mu             0.2142  8.847e-02      2.421  1.546e-02 [4.082e-02,  0.388]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.0032e-04  2.113e-03  4.748e-02      0.962 [-4.041e-03,4.241e-03]
alpha[1]       1.0000     16.291  6.138e-02      0.951      [-30.929, 32.929]
beta[1]        0.0000     16.782      0.000      1.000      [-32.891, 32.891]
=============================================================================

Covariance estimator: robust
Aligned returns for /DTE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DTE: first_obs and last_obs produce in an empty array.
Aligned returns for /DTM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DTM: first_obs and last_obs produce in an empty array.
Aligned returns for /DUK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DUK: first_obs and last_obs produce in an empty array.
Aligned returns for /DUOL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DUOL: first_obs and last_obs produce in an empty array.
Aligned returns for /DV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DV: first_obs and last_obs produce in an empty array.
Aligned returns for /DVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DVA: first_obs and last_obs produce in an empty array.
Aligned returns for /DVN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DVN: first_obs and last_obs produce in an empty array.
Aligned returns for /DXC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DXC: first_obs and last_obs produce in an empty array.
Aligned returns for /DXCM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /DXCM: first_obs and last_obs produce in an empty array.
Aligned returns for /EA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EA: first_obs and last_obs produce in an empty array.
Aligned returns for /EBAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EBAY: first_obs and last_obs produce in an empty array.
Aligned returns for /ECL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ECL: first_obs and last_obs produce in an empty array.
Aligned returns for /ED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ED: first_obs and last_obs produce in an empty array.
Aligned returns for /EEFT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EEFT: first_obs and last_obs produce in an empty array.
Aligned returns for /EFX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EFX: first_obs and last_obs produce in an empty array.
Aligned returns for /EG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EG: first_obs and last_obs produce in an empty array.
Aligned returns for /EGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EGP: first_obs and last_obs produce in an empty array.
Aligned returns for /EHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EHC: first_obs and last_obs produce in an empty array.
Aligned returns for /EIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EIX: first_obs and last_obs produce in an empty array.
Aligned returns for /EL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EL: first_obs and last_obs produce in an empty array.
Aligned returns for /ELAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ELAN: first_obs and last_obs produce in an empty array.
Aligned returns for /ELF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ELF: first_obs and last_obs produce in an empty array.
Aligned returns for /ELS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ELS: first_obs and last_obs produce in an empty array.
Aligned returns for /ELV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ELV: first_obs and last_obs produce in an empty array.
Aligned returns for /EME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EME: first_obs and last_obs produce in an empty array.
Aligned returns for /EMN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EMN: first_obs and last_obs produce in an empty array.
Aligned returns for /EMR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EMR: first_obs and last_obs produce in an empty array.
Aligned returns for /ENOV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ENOV: first_obs and last_obs produce in an empty array.
Aligned returns for /ENPH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ENPH: first_obs and last_obs produce in an empty array.
Aligned returns for /ENTG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ENTG: first_obs and last_obs produce in an empty array.
Aligned returns for /EOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EOG: first_obs and last_obs produce in an empty array.
Aligned returns for /EPAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EPAM: first_obs and last_obs produce in an empty array.
Aligned returns for /EPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EPR: first_obs and last_obs produce in an empty array.
Aligned returns for /EQH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EQH: first_obs and last_obs produce in an empty array.
Aligned returns for /EQIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EQIX: first_obs and last_obs produce in an empty array.
Aligned returns for /EQR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EQR: first_obs and last_obs produce in an empty array.
Aligned returns for /EQT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EQT: first_obs and last_obs produce in an empty array.
Aligned returns for /ES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ES: first_obs and last_obs produce in an empty array.
Aligned returns for /ESAB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ESAB: first_obs and last_obs produce in an empty array.
Aligned returns for /ESI:
Date
2001-02-01    0.779254
2001-03-01    0.778781
2001-05-01    0.695450
2001-06-01    0.695091
2001-08-01    0.693072
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /ESI:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                44.4732
Distribution:                  Normal   AIC:                          -80.9465
Method:            Maximum Likelihood   BIC:                          -69.7965
                                        No. Observations:                  120
Date:                Sun, Oct 13 2024   Df Residuals:                      119
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5090      1.683      0.302      0.762 [ -2.789,  3.807]
                            Volatility Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
omega      4.1033e-03      0.252  1.630e-02      0.987 [ -0.489,  0.497]
alpha[1]       1.0000     17.568  5.692e-02      0.955 [-33.432, 35.432]
beta[1]        0.0000      3.385      0.000      1.000 [ -6.634,  6.634]
========================================================================

Covariance estimator: robust
Aligned returns for /ESS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ESS: first_obs and last_obs produce in an empty array.
Aligned returns for /ESTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ESTC: first_obs and last_obs produce in an empty array.
Aligned returns for /ETN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ETN: first_obs and last_obs produce in an empty array.
Aligned returns for /ETR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ETR: first_obs and last_obs produce in an empty array.
Aligned returns for /ETSY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ETSY: first_obs and last_obs produce in an empty array.
Aligned returns for /EVR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EVR: first_obs and last_obs produce in an empty array.
Aligned returns for /EVRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EVRG: first_obs and last_obs produce in an empty array.
Aligned returns for /EW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EW: first_obs and last_obs produce in an empty array.
Aligned returns for /EWBC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EWBC: first_obs and last_obs produce in an empty array.
Aligned returns for /EXAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EXAS: first_obs and last_obs produce in an empty array.
Aligned returns for /EXC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EXC: first_obs and last_obs produce in an empty array.
Aligned returns for /EXEL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EXEL: first_obs and last_obs produce in an empty array.
Aligned returns for /EXP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EXP: first_obs and last_obs produce in an empty array.
Aligned returns for /EXPD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EXPD: first_obs and last_obs produce in an empty array.
Aligned returns for /EXPE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EXPE: first_obs and last_obs produce in an empty array.
Aligned returns for /EXR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /EXR: first_obs and last_obs produce in an empty array.
Aligned returns for /F:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /F: first_obs and last_obs produce in an empty array.
Aligned returns for /FAF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FAF: first_obs and last_obs produce in an empty array.
Aligned returns for /FANG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FANG: first_obs and last_obs produce in an empty array.
Aligned returns for /FAST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FAST: first_obs and last_obs produce in an empty array.
Aligned returns for /FBIN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FBIN: first_obs and last_obs produce in an empty array.
Aligned returns for /FCN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FCN: first_obs and last_obs produce in an empty array.
Aligned returns for /FCNCA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FCNCA: first_obs and last_obs produce in an empty array.
Aligned returns for /FCX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FCX: first_obs and last_obs produce in an empty array.
Aligned returns for /FDS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FDS: first_obs and last_obs produce in an empty array.
Aligned returns for /FDX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FDX: first_obs and last_obs produce in an empty array.
Aligned returns for /FE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FE: first_obs and last_obs produce in an empty array.
Aligned returns for /FERG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FERG: first_obs and last_obs produce in an empty array.
Aligned returns for /FFIV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FFIV: first_obs and last_obs produce in an empty array.
Aligned returns for /FHB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FHB: first_obs and last_obs produce in an empty array.
Aligned returns for /FHN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FHN: first_obs and last_obs produce in an empty array.
Aligned returns for /FI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FI: first_obs and last_obs produce in an empty array.

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.09426. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02798. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02772. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.006999. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Aligned returns for /FIVN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FIVN: first_obs and last_obs produce in an empty array.
Aligned returns for /FIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FIX: first_obs and last_obs produce in an empty array.
Aligned returns for /FLO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FLO: first_obs and last_obs produce in an empty array.
Aligned returns for /FLS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FLS: first_obs and last_obs produce in an empty array.
Aligned returns for /FMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FMC: first_obs and last_obs produce in an empty array.
Aligned returns for /FNB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FNB: first_obs and last_obs produce in an empty array.
Aligned returns for /FND:
Date
2001-02-01    0.545763
2001-03-01    0.546678
2001-05-01    0.590457
2001-06-01    0.591364
2001-08-01    0.599086
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /FND:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                54.3565
Distribution:                  Normal   AIC:                          -100.713
Method:            Maximum Likelihood   BIC:                          -93.1458
                                        No. Observations:                   49
Date:                Sun, Oct 13 2024   Df Residuals:                       48
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2534  3.524e-03     71.906      0.000 [  0.246,  0.260]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.6652e-04  1.014e-04      1.641      0.101 [-3.232e-05,3.654e-04]
alpha[1]       1.0000      0.166      6.014  1.806e-09      [  0.674,  1.326]
beta[1]        0.0000      0.102      0.000      1.000      [ -0.200,  0.200]
=============================================================================

Covariance estimator: robust
Aligned returns for /FNF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FNF: first_obs and last_obs produce in an empty array.
Aligned returns for /FOUR:
Date
2001-06-01    1.985756
2001-08-01    1.964047
2001-10-01    1.771869
2001-11-01    1.887966
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
2001-10-01  0.0748 -0.0765
2001-11-01 -0.0047  0.0221
Results for /FOUR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                4.25187
Distribution:                  Normal   AIC:                         -0.503750
Method:            Maximum Likelihood   BIC:                          -2.95857
                                        No. Observations:                    4
Date:                Sun, Oct 13 2024   Df Residuals:                        3
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.9009  2.933e-02     64.805      0.000 [  1.843,  1.958]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.9989e-11  1.543e-02  4.537e-09      1.000 [-3.023e-02,3.023e-02]
alpha[1]   4.9373e-17      0.618  7.990e-17      1.000      [ -1.211,  1.211]
beta[1]        0.9747      2.491      0.391      0.696      [ -3.908,  5.858]
=============================================================================

Covariance estimator: robust
Aligned returns for /FOX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FOX: first_obs and last_obs produce in an empty array.
Aligned returns for /FOXA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FOXA: first_obs and last_obs produce in an empty array.
Aligned returns for /FR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FR: first_obs and last_obs produce in an empty array.
Aligned returns for /FRPT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FRPT: first_obs and last_obs produce in an empty array.
Aligned returns for /FRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FRT: first_obs and last_obs produce in an empty array.
Aligned returns for /FSLR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FSLR: first_obs and last_obs produce in an empty array.
Aligned returns for /FTI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FTI: first_obs and last_obs produce in an empty array.
Aligned returns for /FTNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FTNT: first_obs and last_obs produce in an empty array.
Aligned returns for /FTRE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FTRE: first_obs and last_obs produce in an empty array.
Aligned returns for /FTV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FTV: first_obs and last_obs produce in an empty array.
Aligned returns for /FWONA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FWONA: first_obs and last_obs produce in an empty array.
Aligned returns for /FWONK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FWONK: first_obs and last_obs produce in an empty array.
Aligned returns for /FYBR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /FYBR: first_obs and last_obs produce in an empty array.
Aligned returns for /G:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /G: first_obs and last_obs produce in an empty array.
Aligned returns for /GAP:
Date
2001-02-01    0.506857
2001-03-01    0.518072
2001-05-01    0.526933
2001-06-01    0.544349
2001-08-01    0.589793
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /GAP:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                46.2725
Distribution:                  Normal   AIC:                          -84.5451
Method:            Maximum Likelihood   BIC:                          -75.2221
                                        No. Observations:                   76
Date:                Sun, Oct 13 2024   Df Residuals:                       75
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5392  1.238e-02     43.542      0.000 [  0.515,  0.563]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      8.3878e-04  3.736e-04      2.245  2.476e-02 [1.066e-04,1.571e-03]
alpha[1]       1.0000      0.164      6.082  1.189e-09     [  0.678,  1.322]
beta[1]        0.0000  8.107e-02      0.000      1.000     [ -0.159,  0.159]
============================================================================

Covariance estimator: robust
Aligned returns for /GD:
Series([], Name: r_vol, dtype: float64)

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06071. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06968. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GD: first_obs and last_obs produce in an empty array.
Aligned returns for /GDDY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GDDY: first_obs and last_obs produce in an empty array.
Aligned returns for /GE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GE: first_obs and last_obs produce in an empty array.
Aligned returns for /GEHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GEHC: first_obs and last_obs produce in an empty array.
Aligned returns for /GEN:
Date
2008-07-01    0.357678
2008-08-01    0.373785
2008-10-01    0.379570
2008-12-01    0.526126
2009-04-01    0.606198
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2008-07-01  0.0260  0.0542
2008-08-01  0.0360  0.0159
2008-10-01 -0.0260 -0.0230
2008-12-01  0.0346  0.0014
2009-04-01  0.0539  0.0536
Results for /GEN:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                22.5914
Distribution:                  Normal   AIC:                          -37.1828
Method:            Maximum Likelihood   BIC:                          -26.8429
                                        No. Observations:                   98
Date:                Sun, Oct 13 2024   Df Residuals:                       97
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.6710  4.032e-02     16.641  3.501e-62 [  0.592,  0.750]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.2536e-03  2.306e-03      1.411      0.158 [-1.267e-03,7.774e-03]
alpha[1]       0.9859      0.147      6.710  1.946e-11      [  0.698,  1.274]
beta[1]        0.0141  8.918e-02      0.159      0.874      [ -0.161,  0.189]
=============================================================================

Covariance estimator: robust
Aligned returns for /GEV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GEV: first_obs and last_obs produce in an empty array.
Aligned returns for /GFS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GFS: first_obs and last_obs produce in an empty array.
Aligned returns for /GGG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GGG: first_obs and last_obs produce in an empty array.
Aligned returns for /GILD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GILD: first_obs and last_obs produce in an empty array.
Aligned returns for /GIS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GIS: first_obs and last_obs produce in an empty array.
Aligned returns for /GL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GL: first_obs and last_obs produce in an empty array.
Aligned returns for /GLOB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GLOB: first_obs and last_obs produce in an empty array.
Aligned returns for /GLPI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GLPI: first_obs and last_obs produce in an empty array.
Aligned returns for /GLW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GLW: first_obs and last_obs produce in an empty array.
Aligned returns for /GM:
Date
2001-02-01    0.411855
2001-03-01    0.414866
2001-05-01    0.399320
2001-06-01    0.367390
2001-08-01    0.361212
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /GM:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                71.3711
Distribution:                  Normal   AIC:                          -134.742
Method:            Maximum Likelihood   BIC:                          -126.170
                                        No. Observations:                   63
Date:                Sun, Oct 13 2024   Df Residuals:                       62
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3698  1.239e-02     29.837 1.285e-195 [  0.346,  0.394]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      7.9622e-04  6.291e-04      1.266      0.206 [-4.369e-04,2.029e-03]
alpha[1]       1.0000      0.272      3.672  2.407e-04      [  0.466,  1.534]
beta[1]        0.0000      0.431      0.000      1.000      [ -0.845,  0.845]
=============================================================================

Covariance estimator: robust
Aligned returns for /GME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GME: first_obs and last_obs produce in an empty array.
Aligned returns for /GMED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GMED: first_obs and last_obs produce in an empty array.
Aligned returns for /GNRC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GNRC: first_obs and last_obs produce in an empty array.
Aligned returns for /GNTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GNTX: first_obs and last_obs produce in an empty array.
Aligned returns for /GO:
Date
2001-02-01    0.928744
2001-03-01    0.966865
2001-05-01    0.948314
2001-06-01    0.925165
2001-08-01    0.826608
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01417. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01999. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /GO:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                31.7837
Distribution:                  Normal   AIC:                          -55.5673
Method:            Maximum Likelihood   BIC:                          -49.9625
                                        No. Observations:                   30
Date:                Sun, Oct 13 2024   Df Residuals:                       29
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.6286  3.948e-03    159.224      0.000 [  0.621,  0.636]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.2937e-04  5.247e-05      2.465  1.369e-02 [2.652e-05,2.322e-04]
alpha[1]       1.0000      0.655      1.527      0.127     [ -0.283,  2.283]
beta[1]    1.2971e-08      0.363  3.573e-08      1.000     [ -0.712,  0.712]
============================================================================

Covariance estimator: robust
Aligned returns for /GOOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GOOG: first_obs and last_obs produce in an empty array.
Aligned returns for /GOOGL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GOOGL: first_obs and last_obs produce in an empty array.
Aligned returns for /GPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GPC: first_obs and last_obs produce in an empty array.
Aligned returns for /GPK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GPK: first_obs and last_obs produce in an empty array.
Aligned returns for /GPN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GPN: first_obs and last_obs produce in an empty array.
Aligned returns for /GRMN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GRMN: first_obs and last_obs produce in an empty array.
Aligned returns for /GS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GS: first_obs and last_obs produce in an empty array.
Aligned returns for /GTES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GTES: first_obs and last_obs produce in an empty array.
Aligned returns for /GTLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GTLB: first_obs and last_obs produce in an empty array.
Aligned returns for /GWRE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GWRE: first_obs and last_obs produce in an empty array.
Aligned returns for /GWW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GWW: first_obs and last_obs produce in an empty array.
Aligned returns for /GXO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /GXO: first_obs and last_obs produce in an empty array.
Aligned returns for /H:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /H: first_obs and last_obs produce in an empty array.
Aligned returns for /HAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HAL: first_obs and last_obs produce in an empty array.
Aligned returns for /HAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HAS: first_obs and last_obs produce in an empty array.
Aligned returns for /HAYW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HAYW: first_obs and last_obs produce in an empty array.
Aligned returns for /HBAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HBAN: first_obs and last_obs produce in an empty array.
Aligned returns for /HCA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HCA: first_obs and last_obs produce in an empty array.
Aligned returns for /HCP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HCP: first_obs and last_obs produce in an empty array.
Aligned returns for /HD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HD: first_obs and last_obs produce in an empty array.
Aligned returns for /HEI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HEI: first_obs and last_obs produce in an empty array.
Aligned returns for /HES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HES: first_obs and last_obs produce in an empty array.
Aligned returns for /HHH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HHH: first_obs and last_obs produce in an empty array.
Aligned returns for /HIG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HIG: first_obs and last_obs produce in an empty array.
Aligned returns for /HII:
Date
2001-02-01    1.409720
2001-03-01    1.383497
2001-06-01    1.400427
2001-08-01    1.400555
2001-11-01    1.450175
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
2001-11-01 -0.0047  0.0221
Results for /HII:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                3.50027
Distribution:                  Normal   AIC:                          0.999461
Method:            Maximum Likelihood   BIC:                          0.166499
                                        No. Observations:                    6
Date:                Sun, Oct 13 2024   Df Residuals:                        5
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.4591  4.814e-02     30.308 9.006e-202 [  1.365,  1.553]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.8945e-03  3.697e-02  5.124e-02      0.959 [-7.057e-02,7.436e-02]
alpha[1]       0.0000      1.356      0.000      1.000      [ -2.657,  2.657]
beta[1]        1.0000      1.469      0.681      0.496      [ -1.880,  3.880]
=============================================================================

Covariance estimator: robust
Aligned returns for /HIW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HIW: first_obs and last_obs produce in an empty array.
Aligned returns for /HLI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HLI: first_obs and last_obs produce in an empty array.
Aligned returns for /HLT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HLT: first_obs and last_obs produce in an empty array.
Aligned returns for /HOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HOG: first_obs and last_obs produce in an empty array.
Aligned returns for /HOLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HOLX: first_obs and last_obs produce in an empty array.
Aligned returns for /HON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HON: first_obs and last_obs produce in an empty array.
Aligned returns for /HOOD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HOOD: first_obs and last_obs produce in an empty array.
Aligned returns for /HPE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HPE: first_obs and last_obs produce in an empty array.
Aligned returns for /HPQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HPQ: first_obs and last_obs produce in an empty array.
Aligned returns for /HR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HR: first_obs and last_obs produce in an empty array.
Aligned returns for /HRB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HRB: first_obs and last_obs produce in an empty array.
Aligned returns for /HRL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HRL: first_obs and last_obs produce in an empty array.
Aligned returns for /HSIC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HSIC: first_obs and last_obs produce in an empty array.
Aligned returns for /HST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HST: first_obs and last_obs produce in an empty array.
Aligned returns for /HSY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HSY: first_obs and last_obs produce in an empty array.
Aligned returns for /HUBB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HUBB: first_obs and last_obs produce in an empty array.
Aligned returns for /HUBS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HUBS: first_obs and last_obs produce in an empty array.
Aligned returns for /HUM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HUM: first_obs and last_obs produce in an empty array.
Aligned returns for /HUN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HUN: first_obs and last_obs produce in an empty array.
Aligned returns for /HWM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HWM: first_obs and last_obs produce in an empty array.
Aligned returns for /HXL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /HXL: first_obs and last_obs produce in an empty array.
Aligned returns for /IAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IAC: first_obs and last_obs produce in an empty array.
Aligned returns for /IBKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IBKR: first_obs and last_obs produce in an empty array.
Aligned returns for /IBM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IBM: first_obs and last_obs produce in an empty array.
Aligned returns for /ICE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ICE: first_obs and last_obs produce in an empty array.
Aligned returns for /IDA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IDA: first_obs and last_obs produce in an empty array.
Aligned returns for /IDXX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IDXX: first_obs and last_obs produce in an empty array.
Aligned returns for /IEX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IEX: first_obs and last_obs produce in an empty array.
Aligned returns for /IFF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IFF: first_obs and last_obs produce in an empty array.
Aligned returns for /ILMN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ILMN: first_obs and last_obs produce in an empty array.
Aligned returns for /INCY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /INCY: first_obs and last_obs produce in an empty array.
Aligned returns for /INFA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /INFA: first_obs and last_obs produce in an empty array.
Aligned returns for /INGR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /INGR: first_obs and last_obs produce in an empty array.
Aligned returns for /INSP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /INSP: first_obs and last_obs produce in an empty array.
Aligned returns for /INTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /INTC: first_obs and last_obs produce in an empty array.
Aligned returns for /INTU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /INTU: first_obs and last_obs produce in an empty array.
Aligned returns for /INVH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /INVH: first_obs and last_obs produce in an empty array.
Aligned returns for /IONS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IONS: first_obs and last_obs produce in an empty array.
Aligned returns for /IP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IP: first_obs and last_obs produce in an empty array.
Aligned returns for /IPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IPG: first_obs and last_obs produce in an empty array.
Aligned returns for /IPGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IPGP: first_obs and last_obs produce in an empty array.
Aligned returns for /IQV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IQV: first_obs and last_obs produce in an empty array.
Aligned returns for /IR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IR: first_obs and last_obs produce in an empty array.
Aligned returns for /IRDM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IRDM: first_obs and last_obs produce in an empty array.
Aligned returns for /IRM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /IRM: first_obs and last_obs produce in an empty array.
Aligned returns for /ISRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ISRG: first_obs and last_obs produce in an empty array.
Aligned returns for /IT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.0246. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.09925. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /JEF: first_obs and last_obs produce in an empty array.
Aligned returns for /JHG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /JHG: first_obs and last_obs produce in an empty array.
Aligned returns for /JKHY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /JKHY: first_obs and last_obs produce in an empty array.
Aligned returns for /JLL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /JLL: first_obs and last_obs produce in an empty array.
Aligned returns for /JNJ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /JNJ: first_obs and last_obs produce in an empty array.
Aligned returns for /JNPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /JNPR: first_obs and last_obs produce in an empty array.
Aligned returns for /JPM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /JPM: first_obs and last_obs produce in an empty array.
Aligned returns for /JWN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /JWN: first_obs and last_obs produce in an empty array.
Aligned returns for /K:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /K: first_obs and last_obs produce in an empty array.
Aligned returns for /KBR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KBR: first_obs and last_obs produce in an empty array.
Aligned returns for /KD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KD: first_obs and last_obs produce in an empty array.
Aligned returns for /KDP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KDP: first_obs and last_obs produce in an empty array.
Aligned returns for /KEX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KEX: first_obs and last_obs produce in an empty array.
Aligned returns for /KEY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KEY: first_obs and last_obs produce in an empty array.
Aligned returns for /KEYS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KEYS: first_obs and last_obs produce in an empty array.
Aligned returns for /KHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KHC: first_obs and last_obs produce in an empty array.
Aligned returns for /KIM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KIM: first_obs and last_obs produce in an empty array.
Aligned returns for /KKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KKR: first_obs and last_obs produce in an empty array.
Aligned returns for /KLAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KLAC: first_obs and last_obs produce in an empty array.
Aligned returns for /KMB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KMB: first_obs and last_obs produce in an empty array.
Aligned returns for /KMI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KMI: first_obs and last_obs produce in an empty array.
Aligned returns for /KMPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KMPR: first_obs and last_obs produce in an empty array.
Aligned returns for /KMX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KMX: first_obs and last_obs produce in an empty array.
Aligned returns for /KNSL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KNSL: first_obs and last_obs produce in an empty array.
Aligned returns for /KNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KNX: first_obs and last_obs produce in an empty array.
Aligned returns for /KO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KO: first_obs and last_obs produce in an empty array.
Aligned returns for /KR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KR: first_obs and last_obs produce in an empty array.
Aligned returns for /KRC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KRC: first_obs and last_obs produce in an empty array.
Aligned returns for /KSS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KSS: first_obs and last_obs produce in an empty array.
Aligned returns for /KVUE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /KVUE: first_obs and last_obs produce in an empty array.
Aligned returns for /L:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /L: first_obs and last_obs produce in an empty array.
Aligned returns for /LAD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LAD: first_obs and last_obs produce in an empty array.
Aligned returns for /LAMR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LAMR: first_obs and last_obs produce in an empty array.
Aligned returns for /LAZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LAZ: first_obs and last_obs produce in an empty array.
Aligned returns for /LBRDA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LBRDA: first_obs and last_obs produce in an empty array.
Aligned returns for /LBRDK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LBRDK: first_obs and last_obs produce in an empty array.
Aligned returns for /LBTYA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LBTYA: first_obs and last_obs produce in an empty array.
Aligned returns for /LBTYK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LBTYK: first_obs and last_obs produce in an empty array.
Aligned returns for /LCID:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LCID: first_obs and last_obs produce in an empty array.
Aligned returns for /LDOS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LDOS: first_obs and last_obs produce in an empty array.
Aligned returns for /LEA:
Date
2001-02-01    0.518379
2001-03-01    0.503998
2001-05-01    0.473377
2001-06-01    0.462728
2001-08-01    0.451835
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /LEA:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                56.5304
Distribution:                  Normal   AIC:                          -105.061
Method:            Maximum Likelihood   BIC:                          -96.4253
                                        No. Observations:                   64
Date:                Sun, Oct 13 2024   Df Residuals:                       63
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4189  4.764e-03     87.935      0.000 [  0.410,  0.428]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.8914e-04  2.601e-04      1.496      0.135 [-1.206e-04,8.989e-04]
alpha[1]       1.0000      0.145      6.876  6.141e-12      [  0.715,  1.285]
beta[1]        0.0000  9.284e-02      0.000      1.000      [ -0.182,  0.182]
=============================================================================

Covariance estimator: robust
Aligned returns for /LECO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LECO: first_obs and last_obs produce in an empty array.
Aligned returns for /LEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LEG: first_obs and last_obs produce in an empty array.
Aligned returns for /LEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LEN: first_obs and last_obs produce in an empty array.
Aligned returns for /LFUS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LFUS: first_obs and last_obs produce in an empty array.
Aligned returns for /LH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LH: first_obs and last_obs produce in an empty array.
Aligned returns for /LHX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LHX: first_obs and last_obs produce in an empty array.
Aligned returns for /LII:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LII: first_obs and last_obs produce in an empty array.
Aligned returns for /LIN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LIN: first_obs and last_obs produce in an empty array.
Aligned returns for /LINE:
Date
2007-02-01    0.239854
2007-03-01    0.231433
2007-05-01    0.225100
2007-06-01    0.237011
2007-08-01    0.259862
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2007-02-01  0.0119 -0.0014
2007-03-01  0.0016 -0.0097
2007-05-01  0.0024 -0.0065
2007-06-01  0.0075 -0.0105
2007-08-01 -0.0013 -0.0186
Results for /LINE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                64.1198
Distribution:                  Normal   AIC:                          -120.240
Method:            Maximum Likelihood   BIC:                          -111.246
                                        No. Observations:                   70
Date:                Sun, Oct 13 2024   Df Residuals:                       69
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2661  8.515e-03     31.253 2.046e-214 [  0.249,  0.283]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.0174e-04  5.975e-04      1.007      0.314 [-5.693e-04,1.773e-03]
alpha[1]       1.0000      0.571      1.751  7.993e-02      [ -0.119,  2.119]
beta[1]        0.0000      0.508      0.000      1.000      [ -0.995,  0.995]
=============================================================================

Covariance estimator: robust
Aligned returns for /LITE:
Date
2001-02-01    1.756061
2001-08-01    1.596838
2001-10-01    1.630658
2001-11-01    1.672616
2002-02-01    1.649480
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-08-01  0.0248  0.0231
2001-10-01  0.0748 -0.0765
2001-11-01 -0.0047  0.0221
2002-02-01 -0.0101  0.0216

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01814. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.0535. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06007. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /LITE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                8.84115
Distribution:                  Normal   AIC:                          -9.68230
Method:            Maximum Likelihood   BIC:                          -7.12607
                                        No. Observations:                   14
Date:                Sun, Oct 13 2024   Df Residuals:                       13
Time:                        22:28:03   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.6059  7.537e-02     21.307 9.743e-101 [  1.458,  1.754]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      7.6383e-03  9.099e-03      0.839      0.401 [-1.020e-02,2.547e-02]
alpha[1]       0.8212      0.660      1.244      0.214      [ -0.473,  2.115]
beta[1]    7.9461e-14      0.256  3.106e-13      1.000      [ -0.501,  0.501]
=============================================================================

Covariance estimator: robust
Aligned returns for /LKQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LKQ: first_obs and last_obs produce in an empty array.
Aligned returns for /LLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LLY: first_obs and last_obs produce in an empty array.
Aligned returns for /LLYVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LLYVA: first_obs and last_obs produce in an empty array.
Aligned returns for /LLYVK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LLYVK: first_obs and last_obs produce in an empty array.
Aligned returns for /LMT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LMT: first_obs and last_obs produce in an empty array.
Aligned returns for /LNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LNC: first_obs and last_obs produce in an empty array.
Aligned returns for /LNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LNG: first_obs and last_obs produce in an empty array.
Aligned returns for /LNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LNT: first_obs and last_obs produce in an empty array.
Aligned returns for /LNW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LNW: first_obs and last_obs produce in an empty array.
Aligned returns for /LOPE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LOPE: first_obs and last_obs produce in an empty array.
Aligned returns for /LOW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LOW: first_obs and last_obs produce in an empty array.
Aligned returns for /LPLA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LPLA: first_obs and last_obs produce in an empty array.
Aligned returns for /LPX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LPX: first_obs and last_obs produce in an empty array.
Aligned returns for /LRCX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LRCX: first_obs and last_obs produce in an empty array.
Aligned returns for /LSCC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LSCC: first_obs and last_obs produce in an empty array.
Aligned returns for /LSTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LSTR: first_obs and last_obs produce in an empty array.
Aligned returns for /LULU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LULU: first_obs and last_obs produce in an empty array.
Aligned returns for /LUV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LUV: first_obs and last_obs produce in an empty array.
Aligned returns for /LVS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LVS: first_obs and last_obs produce in an empty array.
Aligned returns for /LW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LW: first_obs and last_obs produce in an empty array.
Aligned returns for /LYB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LYB: first_obs and last_obs produce in an empty array.
Aligned returns for /LYFT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LYFT: first_obs and last_obs produce in an empty array.
Aligned returns for /LYV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /LYV: first_obs and last_obs produce in an empty array.
Aligned returns for /M:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /M: first_obs and last_obs produce in an empty array.
Aligned returns for /MA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MA: first_obs and last_obs produce in an empty array.
Aligned returns for /MAA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MAA: first_obs and last_obs produce in an empty array.
Aligned returns for /MAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MAN: first_obs and last_obs produce in an empty array.
Aligned returns for /MANH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MANH: first_obs and last_obs produce in an empty array.
Aligned returns for /MAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MAR: first_obs and last_obs produce in an empty array.
Aligned returns for /MAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MAS: first_obs and last_obs produce in an empty array.
Aligned returns for /MASI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MASI: first_obs and last_obs produce in an empty array.
Aligned returns for /MAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MAT: first_obs and last_obs produce in an empty array.
Aligned returns for /MCD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MCD: first_obs and last_obs produce in an empty array.
Aligned returns for /MCHP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MCHP: first_obs and last_obs produce in an empty array.
Aligned returns for /MCK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MCK: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /MCO. Resolving...
Aligned returns for /MCO:
Date
2001-02-01    0.459273
2001-03-01    0.456425
2001-05-01    0.480888
2001-06-01    0.514576
2001-08-01    0.519123
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /MCO:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                37.2093
Distribution:                  Normal   AIC:                          -66.4186
Method:            Maximum Likelihood   BIC:                          -58.3893
                                        No. Observations:                   55
Date:                Sun, Oct 13 2024   Df Residuals:                       54
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4325  1.768e-02     24.467 3.308e-132 [  0.398,  0.467]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.5591e-04  4.241e-04      0.839      0.401 [-4.754e-04,1.187e-03]
alpha[1]       0.4571      0.176      2.593  9.502e-03      [  0.112,  0.803]
beta[1]        0.5429      0.311      1.746  8.080e-02   [-6.650e-02,  1.152]
=============================================================================

Covariance estimator: robust
Aligned returns for /MDB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MDB: first_obs and last_obs produce in an empty array.
Aligned returns for /MDLZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MDLZ: first_obs and last_obs produce in an empty array.
Aligned returns for /MDT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MDT: first_obs and last_obs produce in an empty array.
Aligned returns for /MDU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MDU: first_obs and last_obs produce in an empty array.
Aligned returns for /MEDP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MEDP: first_obs and last_obs produce in an empty array.
Aligned returns for /MET:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MET: first_obs and last_obs produce in an empty array.
Aligned returns for /META:
Date
2001-03-01    1.350942
2001-05-01    1.542615
2001-06-01    1.569431
2001-10-01    1.624184
2001-11-01    1.612094
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-10-01  0.0748 -0.0765
2001-11-01 -0.0047  0.0221
Results for /META:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:             -0.0970681
Distribution:                  Normal   AIC:                           8.19414
Method:            Maximum Likelihood   BIC:                           8.51190
                                        No. Observations:                    8
Date:                Sun, Oct 13 2024   Df Residuals:                        7
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.7210  8.371e-02     20.559  6.377e-94 [  1.557,  1.885]
                              Volatility Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
omega          0.0279  4.326e-02      0.646      0.518 [-5.685e-02,  0.113]
alpha[1]       0.0000  8.362e-02      0.000      1.000    [ -0.164,  0.164]
beta[1]        0.5037      0.783      0.643      0.520    [ -1.032,  2.039]
===========================================================================

Covariance estimator: robust
Aligned returns for /MGM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MGM: first_obs and last_obs produce in an empty array.
Aligned returns for /MHK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MHK: first_obs and last_obs produce in an empty array.
Aligned returns for /MIDD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MIDD: first_obs and last_obs produce in an empty array.
Aligned returns for /MKC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MKC: first_obs and last_obs produce in an empty array.
Aligned returns for /MKL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MKL: first_obs and last_obs produce in an empty array.
Aligned returns for /MKSI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MKSI: first_obs and last_obs produce in an empty array.
Aligned returns for /MKTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MKTX: first_obs and last_obs produce in an empty array.
Aligned returns for /MLM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MLM: first_obs and last_obs produce in an empty array.
Aligned returns for /MMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MMC: first_obs and last_obs produce in an empty array.
Aligned returns for /MMM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MMM: first_obs and last_obs produce in an empty array.
Aligned returns for /MNST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MNST: first_obs and last_obs produce in an empty array.
Aligned returns for /MO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MO: first_obs and last_obs produce in an empty array.
Aligned returns for /MOH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MOH: first_obs and last_obs produce in an empty array.
Aligned returns for /MORN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MORN: first_obs and last_obs produce in an empty array.
Aligned returns for /MOS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MOS: first_obs and last_obs produce in an empty array.
Aligned returns for /MP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MP: first_obs and last_obs produce in an empty array.
Aligned returns for /MPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MPC: first_obs and last_obs produce in an empty array.
Aligned returns for /MPW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MPW: first_obs and last_obs produce in an empty array.
Aligned returns for /MPWR:
Date
2001-02-01    1.483617
2001-03-01    1.491763
2001-05-01    1.564705
2001-06-01    1.580859
2001-08-01    1.706151
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231

Results for /MPWR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               0.391081
Distribution:                  Normal   AIC:                           7.21784
Method:            Maximum Likelihood   BIC:                           8.42818
                                        No. Observations:                   10
Date:                Sun, Oct 13 2024   Df Residuals:                        9
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.6087  5.996e-02     26.830 1.452e-158 [  1.491,  1.726]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      5.9312e-03  3.113e-03      1.905  5.677e-02 [-1.709e-04,1.203e-02]
alpha[1]       1.0000      0.252      3.976  7.011e-05      [  0.507,  1.493]
beta[1]    7.5419e-13      0.223  3.389e-12      1.000      [ -0.436,  0.436]
=============================================================================

Covariance estimator: robust
Aligned returns for /MRK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MRK: first_obs and last_obs produce in an empty array.
Aligned returns for /MRNA:
Date
2001-02-01    1.043382
2001-03-01    0.909497
2001-05-01    0.843687
2001-06-01    0.807680
2001-08-01    0.797540
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /MRNA:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -10.6889
Distribution:                  Normal   AIC:                           29.3779
Method:            Maximum Likelihood   BIC:                           39.1953
                                        No. Observations:                   86
Date:                Sun, Oct 13 2024   Df Residuals:                       85
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.6483  5.431e-02     11.936  7.645e-33 [  0.542,  0.755]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      2.8244e-03  3.848e-03      0.734      0.463 [-4.717e-03,1.037e-02]
alpha[1]       0.7468      0.278      2.690  7.137e-03      [  0.203,  1.291]
beta[1]        0.2532      0.338      0.748      0.454      [ -0.410,  0.917]
=============================================================================

Covariance estimator: robust
Aligned returns for /MRO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MRO: first_obs and last_obs produce in an empty array.
Aligned returns for /MRVL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MRVL: first_obs and last_obs produce in an empty array.
Aligned returns for /MS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MS: first_obs and last_obs produce in an empty array.
Aligned returns for /MSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MSA: first_obs and last_obs produce in an empty array.
Aligned returns for /MSCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MSCI: first_obs and last_obs produce in an empty array.
Aligned returns for /MSFT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MSFT: first_obs and last_obs produce in an empty array.
Aligned returns for /MSGS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MSGS: first_obs and last_obs produce in an empty array.
Aligned returns for /MSI:
Date
2001-02-01    1.227479
2001-03-01    1.206080
2001-05-01    1.205554
2001-06-01    1.187262
2001-11-01    1.216058
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-11-01 -0.0047  0.0221
Results for /MSI:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                16.4817
Distribution:                  Normal   AIC:                          -24.9635
Method:            Maximum Likelihood   BIC:                          -15.0541
                                        No. Observations:                   88
Date:                Sun, Oct 13 2024   Df Residuals:                       87
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8192  6.386e-02     12.829  1.133e-37 [  0.694,  0.944]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      5.4824e-03  4.254e-03      1.289      0.197 [-2.855e-03,1.382e-02]
alpha[1]       0.9514      2.229      0.427      0.669      [ -3.417,  5.320]
beta[1]        0.0000      1.648      0.000      1.000      [ -3.231,  3.231]
=============================================================================

Covariance estimator: robust
Aligned returns for /MSM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MSM: first_obs and last_obs produce in an empty array.
Aligned returns for /MSTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MSTR: first_obs and last_obs produce in an empty array.
Aligned returns for /MTB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTB: first_obs and last_obs produce in an empty array.
Aligned returns for /MTCH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTCH: first_obs and last_obs produce in an empty array.
Aligned returns for /MTD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTD: first_obs and last_obs produce in an empty array.
Aligned returns for /MTDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTDR: first_obs and last_obs produce in an empty array.
Aligned returns for /MTG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTG: first_obs and last_obs produce in an empty array.
Aligned returns for /MTN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTN: first_obs and last_obs produce in an empty array.
Aligned returns for /MTSI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTSI: first_obs and last_obs produce in an empty array.
Aligned returns for /MTZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MTZ: first_obs and last_obs produce in an empty array.
Aligned returns for /MU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MU: first_obs and last_obs produce in an empty array.
Aligned returns for /MUSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /MUSA: first_obs and last_obs produce in an empty array.
Aligned returns for /NBIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NBIX: first_obs and last_obs produce in an empty array.
Aligned returns for /NCLH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NCLH: first_obs and last_obs produce in an empty array.
Aligned returns for /NCNO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NCNO: first_obs and last_obs produce in an empty array.
Aligned returns for /NDAQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NDAQ: first_obs and last_obs produce in an empty array.
Aligned returns for /NDSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NDSN: first_obs and last_obs produce in an empty array.
Aligned returns for /NEE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NEE: first_obs and last_obs produce in an empty array.
Aligned returns for /NEM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NEM: first_obs and last_obs produce in an empty array.
Aligned returns for /NET:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NET: first_obs and last_obs produce in an empty array.
Aligned returns for /NEU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NEU: first_obs and last_obs produce in an empty array.
Aligned returns for /NFE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NFE: first_obs and last_obs produce in an empty array.
Aligned returns for /NFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NFG: first_obs and last_obs produce in an empty array.
Aligned returns for /NFLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NFLX: first_obs and last_obs produce in an empty array.
Aligned returns for /NI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NI: first_obs and last_obs produce in an empty array.
Aligned returns for /NKE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NKE: first_obs and last_obs produce in an empty array.
Aligned returns for /NLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NLY: first_obs and last_obs produce in an empty array.
Aligned returns for /NNN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NNN: first_obs and last_obs produce in an empty array.
Aligned returns for /NOC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NOC: first_obs and last_obs produce in an empty array.
Aligned returns for /NOV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NOV: first_obs and last_obs produce in an empty array.
Aligned returns for /NOW:
Date
2001-02-01    2.053689
2001-03-01    2.070269
2001-05-01    2.137985
2001-06-01    2.137927
2001-08-01    2.089110
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.08851. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.09789. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/volatility.py:1201: RuntimeWarning: invalid value encountered in scalar divide
  scale = np.mean(resids**2) / (target ** (2.0 / power))

Results for /NOW:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1.22574
Distribution:                  Normal   AIC:                           5.54852
Method:            Maximum Likelihood   BIC:                           8.63888
                                        No. Observations:                   16
Date:                Sun, Oct 13 2024   Df Residuals:                       15
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             2.0763  2.496e-02     83.182      0.000 [  2.027,  2.125]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      5.5896e-03  3.025e-03      1.848  6.460e-02 [-3.386e-04,1.152e-02]
alpha[1]       1.0000      0.306      3.271  1.071e-03      [  0.401,  1.599]
beta[1]        0.0000  8.443e-02      0.000      1.000      [ -0.165,  0.165]
=============================================================================

Covariance estimator: robust
Aligned returns for /NRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NRG: first_obs and last_obs produce in an empty array.
Aligned returns for /NSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NSA: first_obs and last_obs produce in an empty array.
Aligned returns for /NSC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NSC: first_obs and last_obs produce in an empty array.
Aligned returns for /NTAP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NTAP: first_obs and last_obs produce in an empty array.
Aligned returns for /NTNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NTNX: first_obs and last_obs produce in an empty array.
Aligned returns for /NTRA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NTRA: first_obs and last_obs produce in an empty array.
Aligned returns for /NTRS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NTRS: first_obs and last_obs produce in an empty array.
Aligned returns for /NU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NU: first_obs and last_obs produce in an empty array.
Aligned returns for /NUE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NUE: first_obs and last_obs produce in an empty array.
Aligned returns for /NVDA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NVDA: first_obs and last_obs produce in an empty array.
Aligned returns for /NVR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NVR: first_obs and last_obs produce in an empty array.
Aligned returns for /NVST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NVST: first_obs and last_obs produce in an empty array.
Aligned returns for /NVT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NVT: first_obs and last_obs produce in an empty array.
Aligned returns for /NWL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NWL: first_obs and last_obs produce in an empty array.
Aligned returns for /NWS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NWS: first_obs and last_obs produce in an empty array.
Aligned returns for /NWSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NWSA: first_obs and last_obs produce in an empty array.
Aligned returns for /NXST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NXST: first_obs and last_obs produce in an empty array.
Aligned returns for /NYT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /NYT: first_obs and last_obs produce in an empty array.
Aligned returns for /O:
Date
2002-07-01    2.257557
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2002-07-01 -0.0528 -0.0385
Results for /O:
Error fitting GARCH model for /O: float division by zero
Aligned returns for /OC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OC: first_obs and last_obs produce in an empty array.
Aligned returns for /ODFL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ODFL: first_obs and last_obs produce in an empty array.
Aligned returns for /OGE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OGE: first_obs and last_obs produce in an empty array.
Aligned returns for /OGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OGN: first_obs and last_obs produce in an empty array.
Aligned returns for /OHI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OHI: first_obs and last_obs produce in an empty array.
Aligned returns for /OKE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OKE: first_obs and last_obs produce in an empty array.
Aligned returns for /OKTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OKTA: first_obs and last_obs produce in an empty array.
Aligned returns for /OLED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OLED: first_obs and last_obs produce in an empty array.
Aligned returns for /OLLI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OLLI: first_obs and last_obs produce in an empty array.
Aligned returns for /OLN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OLN: first_obs and last_obs produce in an empty array.
Aligned returns for /OMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OMC: first_obs and last_obs produce in an empty array.
Aligned returns for /OMF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OMF: first_obs and last_obs produce in an empty array.
Aligned returns for /ON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ON: first_obs and last_obs produce in an empty array.
Aligned returns for /ONTO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ONTO: first_obs and last_obs produce in an empty array.
Aligned returns for /ORCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ORCL: first_obs and last_obs produce in an empty array.
Aligned returns for /ORI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ORI: first_obs and last_obs produce in an empty array.
Aligned returns for /ORLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ORLY: first_obs and last_obs produce in an empty array.
Aligned returns for /OSK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OSK: first_obs and last_obs produce in an empty array.
Aligned returns for /OTIS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OTIS: first_obs and last_obs produce in an empty array.
Aligned returns for /OVV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OVV: first_obs and last_obs produce in an empty array.
Aligned returns for /OWL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OWL: first_obs and last_obs produce in an empty array.
Aligned returns for /OXY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OXY: first_obs and last_obs produce in an empty array.
Aligned returns for /OZK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /OZK: first_obs and last_obs produce in an empty array.
Aligned returns for /PAG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PAG: first_obs and last_obs produce in an empty array.
Aligned returns for /PANW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PANW: first_obs and last_obs produce in an empty array.
Aligned returns for /PARA:
Date
2001-02-01    2.038707
2001-03-01    1.952678
2001-05-01    1.872163
2001-06-01    1.870983
2001-08-01    2.052518
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /PARA:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                3.44479
Distribution:                  Normal   AIC:                           1.11042
Method:            Maximum Likelihood   BIC:                           1.89932
                                        No. Observations:                    9
Date:                Sun, Oct 13 2024   Df Residuals:                        8
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             2.0701      0.263      7.881  3.251e-15 [  1.555,  2.585]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.2097e-03  3.284e-02  3.684e-02      0.971 [-6.315e-02,6.557e-02]
alpha[1]       0.0000      3.054      0.000      1.000      [ -5.986,  5.986]
beta[1]        1.0000      2.816      0.355      0.723      [ -4.520,  6.520]
=============================================================================

Covariance estimator: robust
Aligned returns for /PARAA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PARAA: first_obs and last_obs produce in an empty array.
Aligned returns for /PATH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PATH: first_obs and last_obs produce in an empty array.
Aligned returns for /PAYC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PAYC: first_obs and last_obs produce in an empty array.
Aligned returns for /PAYX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PAYX: first_obs and last_obs produce in an empty array.
Aligned returns for /PB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PB: first_obs and last_obs produce in an empty array.
Aligned returns for /PCAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PCAR: first_obs and last_obs produce in an empty array.
Aligned returns for /PCG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PCG: first_obs and last_obs produce in an empty array.
Aligned returns for /PCOR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PCOR: first_obs and last_obs produce in an empty array.
Aligned returns for /PCTY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PCTY: first_obs and last_obs produce in an empty array.
Aligned returns for /PEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PEG: first_obs and last_obs produce in an empty array.
Aligned returns for /PEGA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PEGA: first_obs and last_obs produce in an empty array.
Aligned returns for /PEN:
Date
2001-02-01    1.871152
2001-03-01    1.904570
2001-05-01    1.852976
2001-06-01    1.874326
2001-08-01    1.848018
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/distribution.py:451: RuntimeWarning: divide by zero encountered in log
  lls = -0.5 * (log(2 * pi) + log(sigma2) + resids ** 2.0 / sigma2)
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/distribution.py:451: RuntimeWarning: invalid value encountered in divide
  lls = -0.5 * (log(2 * pi) + log(sigma2) + resids ** 2.0 / sigma2)
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/distribution.py:451: RuntimeWarning: divide by zero encountered in divide
  lls = -0.5 * (log(2 * pi) + log(sigma2) + resids ** 2.0 / sigma2)
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/distribution.py:451: RuntimeWarning: invalid value encountered in add
  lls = -0.5 * (log(2 * pi) + log(sigma2) + resids ** 2.0 / sigma2)
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:766: ConvergenceWarning: The optimizer returned code 4. The message is:
Inequality constraints incompatible
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02798. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /PEN:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                20.4485
Distribution:                  Normal   AIC:                          -32.8971
Method:            Maximum Likelihood   BIC:                          -24.5869
                                        No. Observations:                   59
Date:                Sun, Oct 13 2024   Df Residuals:                       58
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.0321      0.103     10.047  9.441e-24 [  0.831,  1.233]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      4.2695e-03  1.773e-03      2.409  1.601e-02 [7.954e-04,7.744e-03]
alpha[1]       0.8558      0.574      1.491      0.136     [ -0.269,  1.981]
beta[1]        0.0000      0.431      0.000      1.000     [ -0.844,  0.844]
============================================================================

Covariance estimator: robust
Aligned returns for /PENN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PENN: first_obs and last_obs produce in an empty array.
Aligned returns for /PEP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PEP: first_obs and last_obs produce in an empty array.
Aligned returns for /PFE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PFE: first_obs and last_obs produce in an empty array.
Aligned returns for /PFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PFG: first_obs and last_obs produce in an empty array.
Aligned returns for /PFGC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PFGC: first_obs and last_obs produce in an empty array.
Aligned returns for /PG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PG: first_obs and last_obs produce in an empty array.
Aligned returns for /PGR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PGR: first_obs and last_obs produce in an empty array.
Aligned returns for /PH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PH: first_obs and last_obs produce in an empty array.
Aligned returns for /PHM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PHM: first_obs and last_obs produce in an empty array.
Aligned returns for /PII:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PII: first_obs and last_obs produce in an empty array.
Aligned returns for /PINC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PINC: first_obs and last_obs produce in an empty array.
Aligned returns for /PINS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PINS: first_obs and last_obs produce in an empty array.
Aligned returns for /PK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PK: first_obs and last_obs produce in an empty array.
Aligned returns for /PKG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PKG: first_obs and last_obs produce in an empty array.
Aligned returns for /PLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PLD: first_obs and last_obs produce in an empty array.
Aligned returns for /PLNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PLNT: first_obs and last_obs produce in an empty array.
Aligned returns for /PLTK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PLTK: first_obs and last_obs produce in an empty array.
Aligned returns for /PLTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PLTR: first_obs and last_obs produce in an empty array.
Aligned returns for /PM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PM: first_obs and last_obs produce in an empty array.
Aligned returns for /PNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PNC: first_obs and last_obs produce in an empty array.
Aligned returns for /PNFP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PNFP: first_obs and last_obs produce in an empty array.
Aligned returns for /PNR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PNR: first_obs and last_obs produce in an empty array.
Aligned returns for /PNW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PNW: first_obs and last_obs produce in an empty array.
Aligned returns for /PODD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PODD: first_obs and last_obs produce in an empty array.
Aligned returns for /POOL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /POOL: first_obs and last_obs produce in an empty array.
Aligned returns for /POST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /POST: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /PPC. Resolving...
Aligned returns for /PPC:
Date
2001-02-01    0.726462
2001-03-01    0.588729
2001-05-01    0.558131
2001-06-01    0.549291
2001-08-01    0.524854
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /PPC:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                101.627
Distribution:                  Normal   AIC:                          -195.254
Method:            Maximum Likelihood   BIC:                          -184.345
                                        No. Observations:                  113
Date:                Sun, Oct 13 2024   Df Residuals:                      112
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5566  8.978e-03     62.002      0.000 [  0.539,  0.574]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      7.6307e-04  3.315e-04      2.302  2.135e-02 [1.133e-04,1.413e-03]
alpha[1]       1.0000      0.165      6.056  1.391e-09     [  0.676,  1.324]
beta[1]        0.0000      0.126      0.000      1.000     [ -0.248,  0.248]
============================================================================

Covariance estimator: robust
Aligned returns for /PPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PPG: first_obs and last_obs produce in an empty array.
Aligned returns for /PPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PPL: first_obs and last_obs produce in an empty array.
Aligned returns for /PR:
Date
2001-02-01    0.454644
2001-03-01    0.414689
2001-05-01    0.372039
2001-06-01    0.358584
2001-08-01    0.362012
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /PR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                66.6519
Distribution:                  Normal   AIC:                          -125.304
Method:            Maximum Likelihood   BIC:                          -118.259
                                        No. Observations:                   43
Date:                Sun, Oct 13 2024   Df Residuals:                       42
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.1574  8.697e-03     18.095  3.478e-73 [  0.140,  0.174]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      2.0631e-04  1.927e-04      1.070      0.284 [-1.714e-04,5.841e-04]
alpha[1]       0.7510      0.275      2.735  6.229e-03      [  0.213,  1.289]
beta[1]        0.0286      0.248      0.116      0.908      [ -0.457,  0.514]
=============================================================================

Covariance estimator: robust
Aligned returns for /PRGO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PRGO: first_obs and last_obs produce in an empty array.
Aligned returns for /PRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PRI: first_obs and last_obs produce in an empty array.
Aligned returns for /PRU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PRU: first_obs and last_obs produce in an empty array.
Aligned returns for /PSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PSA: first_obs and last_obs produce in an empty array.
Aligned returns for /PSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PSN: first_obs and last_obs produce in an empty array.
Aligned returns for /PSTG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PSTG: first_obs and last_obs produce in an empty array.
Aligned returns for /PSX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PSX: first_obs and last_obs produce in an empty array.
Aligned returns for /PTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PTC: first_obs and last_obs produce in an empty array.
Aligned returns for /PVH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PVH: first_obs and last_obs produce in an empty array.
Aligned returns for /PWR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PWR: first_obs and last_obs produce in an empty array.
Aligned returns for /PYCR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PYCR: first_obs and last_obs produce in an empty array.
Aligned returns for /PYPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /PYPL: first_obs and last_obs produce in an empty array.
Aligned returns for /QCOM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /QCOM: first_obs and last_obs produce in an empty array.
Aligned returns for /QDEL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /QDEL: first_obs and last_obs produce in an empty array.
Aligned returns for /QGEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /QGEN: first_obs and last_obs produce in an empty array.
Aligned returns for /QRVO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /QRVO: first_obs and last_obs produce in an empty array.
Aligned returns for /QS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /QS: first_obs and last_obs produce in an empty array.
Aligned returns for /R:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /R: first_obs and last_obs produce in an empty array.
Aligned returns for /RARE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RARE: first_obs and last_obs produce in an empty array.
Aligned returns for /RBA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RBA: first_obs and last_obs produce in an empty array.
Aligned returns for /RBC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RBC: first_obs and last_obs produce in an empty array.
Aligned returns for /RBLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RBLX: first_obs and last_obs produce in an empty array.
Aligned returns for /RCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RCL: first_obs and last_obs produce in an empty array.
Aligned returns for /RCM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RCM: first_obs and last_obs produce in an empty array.
Aligned returns for /REG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /REG: first_obs and last_obs produce in an empty array.
Aligned returns for /REGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /REGN: first_obs and last_obs produce in an empty array.
Aligned returns for /REXR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /REXR: first_obs and last_obs produce in an empty array.
Aligned returns for /REYN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /REYN: first_obs and last_obs produce in an empty array.
Aligned returns for /RF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RF: first_obs and last_obs produce in an empty array.
Aligned returns for /RGA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RGA: first_obs and last_obs produce in an empty array.
Aligned returns for /RGEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RGEN: first_obs and last_obs produce in an empty array.
Aligned returns for /RGLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RGLD: first_obs and last_obs produce in an empty array.
Aligned returns for /RH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RH: first_obs and last_obs produce in an empty array.
Aligned returns for /RHI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.04686. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.00831. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /RL: first_obs and last_obs produce in an empty array.
Aligned returns for /RLI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RLI: first_obs and last_obs produce in an empty array.
Aligned returns for /RMD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RMD: first_obs and last_obs produce in an empty array.
Aligned returns for /RNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RNG: first_obs and last_obs produce in an empty array.
Aligned returns for /RNR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RNR: first_obs and last_obs produce in an empty array.
Aligned returns for /ROIV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ROIV: first_obs and last_obs produce in an empty array.
Aligned returns for /ROK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ROK: first_obs and last_obs produce in an empty array.
Aligned returns for /ROKU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ROKU: first_obs and last_obs produce in an empty array.
Aligned returns for /ROL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ROL: first_obs and last_obs produce in an empty array.
Aligned returns for /ROP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ROP: first_obs and last_obs produce in an empty array.
Aligned returns for /ROST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ROST: first_obs and last_obs produce in an empty array.
Aligned returns for /RPM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RPM: first_obs and last_obs produce in an empty array.
Aligned returns for /RPRX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RPRX: first_obs and last_obs produce in an empty array.
Aligned returns for /RRC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RRC: first_obs and last_obs produce in an empty array.
Aligned returns for /RRX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RRX: first_obs and last_obs produce in an empty array.
Aligned returns for /RS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RS: first_obs and last_obs produce in an empty array.
Aligned returns for /RSG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RSG: first_obs and last_obs produce in an empty array.
Aligned returns for /RTX:
Date
2001-08-01    1.512982
2001-10-01    1.622603
2001-11-01    1.661676
2002-02-01    1.609600
2002-03-01    1.578531
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-08-01  0.0248  0.0231
2001-10-01  0.0748 -0.0765
2001-11-01 -0.0047  0.0221
2002-02-01 -0.0101  0.0216
2002-03-01  0.0421  0.0106
Results for /RTX:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -47.3949
Distribution:                  Normal   AIC:                           102.790
Method:            Maximum Likelihood   BIC:                           112.318
                                        No. Observations:                   80
Date:                Sun, Oct 13 2024   Df Residuals:                       79
Time:                        22:28:04   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.5933  2.568e-02     62.039      0.000 [  1.543,  1.644]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.3075e-03  3.833e-03      1.645  9.989e-02 [-1.206e-03,1.382e-02]
alpha[1]       1.0000      0.120      8.332  7.949e-17      [  0.765,  1.235]
beta[1]        0.0000  8.490e-02      0.000      1.000      [ -0.166,  0.166]
=============================================================================

Covariance estimator: robust
Aligned returns for /RVTY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RVTY: first_obs and last_obs produce in an empty array.
Aligned returns for /RYAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RYAN: first_obs and last_obs produce in an empty array.
Aligned returns for /RYN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /RYN: first_obs and last_obs produce in an empty array.
Aligned returns for /S:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /S: first_obs and last_obs produce in an empty array.
Aligned returns for /SAIA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SAIA: first_obs and last_obs produce in an empty array.
Aligned returns for /SAIC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SAIC: first_obs and last_obs produce in an empty array.
Aligned returns for /SAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SAM: first_obs and last_obs produce in an empty array.
Aligned returns for /SBAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SBAC: first_obs and last_obs produce in an empty array.
Aligned returns for /SBUX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SBUX: first_obs and last_obs produce in an empty array.
Aligned returns for /SCCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SCCO: first_obs and last_obs produce in an empty array.
Aligned returns for /SCHW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SCHW: first_obs and last_obs produce in an empty array.
Aligned returns for /SCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SCI: first_obs and last_obs produce in an empty array.
Aligned returns for /SEB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SEB: first_obs and last_obs produce in an empty array.
Aligned returns for /SEE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SEE: first_obs and last_obs produce in an empty array.
Aligned returns for /SEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SEG: first_obs and last_obs produce in an empty array.
Aligned returns for /SEIC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SEIC: first_obs and last_obs produce in an empty array.
Aligned returns for /SF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SF: first_obs and last_obs produce in an empty array.
Aligned returns for /SHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SHC: first_obs and last_obs produce in an empty array.
Aligned returns for /SHW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SHW: first_obs and last_obs produce in an empty array.
Aligned returns for /SIRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SIRI: first_obs and last_obs produce in an empty array.
Aligned returns for /SITE:
Date
2001-02-01    0.878177
2001-03-01    0.866476
2001-05-01    1.066846
2001-06-01    1.063909
2001-08-01    1.082965
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /SITE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                3.16899
Distribution:                  Normal   AIC:                           1.66202
Method:            Maximum Likelihood   BIC:                           4.49422
                                        No. Observations:                   15
Date:                Sun, Oct 13 2024   Df Residuals:                       14
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.1261  5.942e-02     18.953  4.172e-80 [  1.010,  1.243]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      2.9737e-03  2.569e-03      1.158      0.247 [-2.061e-03,8.009e-03]
alpha[1]       1.0000      0.247      4.049  5.146e-05      [  0.516,  1.484]
beta[1]    3.1447e-11      0.163  1.928e-10      1.000      [ -0.320,  0.320]
=============================================================================

Covariance estimator: robust
Aligned returns for /SJM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SJM: first_obs and last_obs produce in an empty array.
Aligned returns for /SKX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []

Error fitting GARCH model for /SKX: first_obs and last_obs produce in an empty array.
Aligned returns for /SLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SLB: first_obs and last_obs produce in an empty array.
Aligned returns for /SLGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SLGN: first_obs and last_obs produce in an empty array.
Aligned returns for /SLM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SLM: first_obs and last_obs produce in an empty array.
Aligned returns for /SMAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SMAR: first_obs and last_obs produce in an empty array.
Aligned returns for /SMCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SMCI: first_obs and last_obs produce in an empty array.
Aligned returns for /SMG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SMG: first_obs and last_obs produce in an empty array.
Aligned returns for /SN:
Date
2013-02-01    0.427648
2013-03-01    0.415340
2013-04-01    0.418059
2013-05-01    0.419458
2013-07-01    0.394198
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2013-02-01 -0.0027  0.0011
2013-03-01  0.0081 -0.0019
2013-04-01 -0.0237  0.0045
2013-05-01  0.0171  0.0263
2013-07-01  0.0187  0.0057
Results for /SN:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                12.7869
Distribution:                  Normal   AIC:                          -17.5738
Method:            Maximum Likelihood   BIC:                          -10.2592
                                        No. Observations:                   46
Date:                Sun, Oct 13 2024   Df Residuals:                       45
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8035  5.635e-02     14.259  3.958e-46 [  0.693,  0.914]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          0.0114  1.894e-02      0.600      0.548 [-2.576e-02,4.849e-02]
alpha[1]       0.7255      1.262      0.575      0.565      [ -1.749,  3.199]
beta[1]    3.5004e-12      1.450  2.413e-12      1.000      [ -2.843,  2.843]
=============================================================================

Covariance estimator: robust
Aligned returns for /SNA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SNA: first_obs and last_obs produce in an empty array.
Aligned returns for /SNDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SNDR: first_obs and last_obs produce in an empty array.
Aligned returns for /SNOW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SNOW: first_obs and last_obs produce in an empty array.
Aligned returns for /SNPS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SNPS: first_obs and last_obs produce in an empty array.
Aligned returns for /SNV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SNV: first_obs and last_obs produce in an empty array.
Aligned returns for /SNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SNX: first_obs and last_obs produce in an empty array.
Aligned returns for /SO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SO: first_obs and last_obs produce in an empty array.
Aligned returns for /SOFI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SOFI: first_obs and last_obs produce in an empty array.
Aligned returns for /SON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SON: first_obs and last_obs produce in an empty array.
Aligned returns for /SPB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SPB: first_obs and last_obs produce in an empty array.
Aligned returns for /SPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SPG: first_obs and last_obs produce in an empty array.
Aligned returns for /SPGI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SPGI: first_obs and last_obs produce in an empty array.
Aligned returns for /SPOT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SPOT: first_obs and last_obs produce in an empty array.
Aligned returns for /SPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SPR: first_obs and last_obs produce in an empty array.
Aligned returns for /SQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SQ: first_obs and last_obs produce in an empty array.
Aligned returns for /SRCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SRCL: first_obs and last_obs produce in an empty array.
Aligned returns for /SRE:
Date
2001-02-01    0.692114
2001-03-01    0.662652
2001-05-01    0.566809
2001-06-01    0.569002
2001-08-01    0.532129
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /SRE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                11.6738
Distribution:                  Normal   AIC:                          -15.3476
Method:            Maximum Likelihood   BIC:                          -12.7914
                                        No. Observations:                   14
Date:                Sun, Oct 13 2024   Df Residuals:                       13
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5431  4.012e-02     13.538  9.286e-42 [  0.464,  0.622]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      9.2434e-04  1.011e-03      0.914      0.361 [-1.057e-03,2.906e-03]
alpha[1]       1.0000      0.298      3.350  8.078e-04      [  0.415,  1.585]
beta[1]    1.1477e-18  3.522e-02  3.259e-17      1.000 [-6.903e-02,6.903e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /SRPT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SRPT: first_obs and last_obs produce in an empty array.
Aligned returns for /SSD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SSD: first_obs and last_obs produce in an empty array.
Aligned returns for /SSNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SSNC: first_obs and last_obs produce in an empty array.
Aligned returns for /ST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ST: first_obs and last_obs produce in an empty array.
Aligned returns for /STAG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /STAG: first_obs and last_obs produce in an empty array.
Aligned returns for /STE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /STE: first_obs and last_obs produce in an empty array.
Aligned returns for /STLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /STLD: first_obs and last_obs produce in an empty array.
Aligned returns for /STT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /STT: first_obs and last_obs produce in an empty array.
Aligned returns for /STWD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /STWD: first_obs and last_obs produce in an empty array.
Aligned returns for /STZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /STZ: first_obs and last_obs produce in an empty array.
Aligned returns for /SUI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SUI: first_obs and last_obs produce in an empty array.
Aligned returns for /SW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SW: first_obs and last_obs produce in an empty array.
Aligned returns for /SWK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SWK: first_obs and last_obs produce in an empty array.
Aligned returns for /SWKS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SWKS: first_obs and last_obs produce in an empty array.
Aligned returns for /SWN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SWN: first_obs and last_obs produce in an empty array.
Aligned returns for /SYF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SYF: first_obs and last_obs produce in an empty array.
Aligned returns for /SYK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SYK: first_obs and last_obs produce in an empty array.
Aligned returns for /SYY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /SYY: first_obs and last_obs produce in an empty array.
Aligned returns for /T:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /T: first_obs and last_obs produce in an empty array.
Aligned returns for /TAP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TAP: first_obs and last_obs produce in an empty array.
Aligned returns for /TDC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TDC: first_obs and last_obs produce in an empty array.
Aligned returns for /TDG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TDG: first_obs and last_obs produce in an empty array.
Aligned returns for /TDY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TDY: first_obs and last_obs produce in an empty array.
Aligned returns for /TEAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TEAM: first_obs and last_obs produce in an empty array.
Aligned returns for /TECH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TECH: first_obs and last_obs produce in an empty array.
Aligned returns for /TER:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TER: first_obs and last_obs produce in an empty array.
Aligned returns for /TFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TFC: first_obs and last_obs produce in an empty array.
Aligned returns for /TFSL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TFSL: first_obs and last_obs produce in an empty array.
Aligned returns for /TFX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TFX: first_obs and last_obs produce in an empty array.
Aligned returns for /TGT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TGT: first_obs and last_obs produce in an empty array.
Aligned returns for /THC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /THC: first_obs and last_obs produce in an empty array.
Aligned returns for /THG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /THG: first_obs and last_obs produce in an empty array.
Aligned returns for /THO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /THO: first_obs and last_obs produce in an empty array.
Aligned returns for /TJX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TJX: first_obs and last_obs produce in an empty array.
Aligned returns for /TKO:
Date
2005-03-01    0.808255
2005-04-01    0.731192
2005-06-01    0.708807
2005-07-01    0.706812
2005-08-01    0.687216
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2005-03-01 -0.0140  0.0204
2005-04-01 -0.0394  0.0007
2005-06-01  0.0258  0.0283
2005-07-01  0.0291 -0.0079
2005-08-01 -0.0097  0.0132

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.05425. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01533. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /TKO:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                27.0106
Distribution:                  Normal   AIC:                          -46.0211
Method:            Maximum Likelihood   BIC:                          -39.6871
                                        No. Observations:                   36
Date:                Sun, Oct 13 2024   Df Residuals:                       35
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7103  1.418e-02     50.085      0.000 [  0.683,  0.738]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.6608e-04  7.548e-04      0.485      0.628 [-1.113e-03,1.845e-03]
alpha[1]       0.9436      0.262      3.596  3.227e-04      [  0.429,  1.458]
beta[1]        0.0564  8.244e-02      0.684      0.494      [ -0.105,  0.218]
=============================================================================

Covariance estimator: robust
Aligned returns for /TKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TKR: first_obs and last_obs produce in an empty array.
Aligned returns for /TMO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TMO: first_obs and last_obs produce in an empty array.
Aligned returns for /TMUS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TMUS: first_obs and last_obs produce in an empty array.
Aligned returns for /TNL:
Date
2001-02-01    1.167994
2001-03-01    1.184310
2001-05-01    1.213718
2001-06-01    1.212368
2001-08-01    1.210422
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /TNL:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                6.28479
Distribution:                  Normal   AIC:                          -4.56959
Method:            Maximum Likelihood   BIC:                           6.04625
                                        No. Observations:                  105
Date:                Sun, Oct 13 2024   Df Residuals:                      104
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4093  1.987e-02     20.599  2.778e-94 [  0.370,  0.448]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.1893e-03  2.150e-03      0.553      0.580 [-3.024e-03,5.403e-03]
alpha[1]       1.0000      0.176      5.692  1.258e-08      [  0.656,  1.344]
beta[1]        0.0000  2.496e-02      0.000      1.000 [-4.891e-02,4.891e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /TOL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TOL: first_obs and last_obs produce in an empty array.
Aligned returns for /TOST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TOST: first_obs and last_obs produce in an empty array.
Aligned returns for /TPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TPG: first_obs and last_obs produce in an empty array.
Aligned returns for /TPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TPL: first_obs and last_obs produce in an empty array.
Aligned returns for /TPR:
Date
2001-02-01    0.702771
2001-03-01    0.728013
2001-05-01    0.755907
2001-06-01    0.734723
2001-10-01    0.716979
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-10-01  0.0748 -0.0765
Results for /TPR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                33.3164
Distribution:                  Normal   AIC:                          -58.6329
Method:            Maximum Likelihood   BIC:                          -50.2555
                                        No. Observations:                   60
Date:                Sun, Oct 13 2024   Df Residuals:                       59
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4167  1.064e-02     39.149      0.000 [  0.396,  0.438]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.9951e-04  3.319e-04      1.204      0.229 [-2.509e-04,1.050e-03]
alpha[1]       0.9539      0.143      6.673  2.500e-11      [  0.674,  1.234]
beta[1]        0.0461  8.005e-02      0.575      0.565      [ -0.111,  0.203]
=============================================================================

Covariance estimator: robust
Aligned returns for /TPX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TPX: first_obs and last_obs produce in an empty array.
Aligned returns for /TREX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TREX: first_obs and last_obs produce in an empty array.
Aligned returns for /TRGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TRGP: first_obs and last_obs produce in an empty array.
Aligned returns for /TRIP:
Date
2001-02-01    2.793173
2001-03-01    2.810311
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
Results for /TRIP:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                6.68129
Distribution:                  Normal   AIC:                          -5.36257
Method:            Maximum Likelihood   BIC:                          -10.5900
                                        No. Observations:                    2
Date:                Sun, Oct 13 2024   Df Residuals:                        1
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             2.8017  9.107e-03    307.636      0.000 [  2.784,  2.820]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.6715e-05  1.096e-07    334.896      0.000 [3.650e-05,3.693e-05]
alpha[1]       0.0100      0.142  7.027e-02      0.944     [ -0.269,  0.289]
beta[1]        0.4900      0.193      2.543  1.098e-02     [  0.112,  0.868]
============================================================================

Covariance estimator: robust
Aligned returns for /TRMB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TRMB: first_obs and last_obs produce in an empty array.
Aligned returns for /TROW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TROW: first_obs and last_obs produce in an empty array.
Aligned returns for /TRU:
Date
2001-02-01    0.414798
2001-03-01    0.419233
2001-05-01    0.426999
2001-06-01    0.465098
2001-08-01    0.512466
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /TRU:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                20.6621
Distribution:                  Normal   AIC:                          -33.3241
Method:            Maximum Likelihood   BIC:                          -23.2370
                                        No. Observations:                   92
Date:                Sun, Oct 13 2024   Df Residuals:                       91
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4137  4.485e-02      9.223  2.889e-20 [  0.326,  0.502]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.3391e-03  4.834e-04      2.770  5.607e-03  [3.916e-04,2.287e-03]
alpha[1]       1.0000      0.108      9.275  1.768e-20      [  0.789,  1.211]
beta[1]    1.4200e-14  3.242e-02  4.380e-13      1.000 [-6.355e-02,6.355e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /TRV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 7.343e-05. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 100 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06598. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /TRV: first_obs and last_obs produce in an empty array.
Aligned returns for /TSCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TSCO: first_obs and last_obs produce in an empty array.
Aligned returns for /TSLA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TSLA: first_obs and last_obs produce in an empty array.
Aligned returns for /TSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TSN: first_obs and last_obs produce in an empty array.
Aligned returns for /TT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TT: first_obs and last_obs produce in an empty array.
Aligned returns for /TTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TTC: first_obs and last_obs produce in an empty array.
Aligned returns for /TTD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TTD: first_obs and last_obs produce in an empty array.
Aligned returns for /TTEK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TTEK: first_obs and last_obs produce in an empty array.
Aligned returns for /TTWO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TTWO: first_obs and last_obs produce in an empty array.
Aligned returns for /TW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TW: first_obs and last_obs produce in an empty array.
Aligned returns for /TWLO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TWLO: first_obs and last_obs produce in an empty array.
Aligned returns for /TXG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TXG: first_obs and last_obs produce in an empty array.
Aligned returns for /TXN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TXN: first_obs and last_obs produce in an empty array.
Aligned returns for /TXRH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TXRH: first_obs and last_obs produce in an empty array.
Aligned returns for /TXT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TXT: first_obs and last_obs produce in an empty array.
Aligned returns for /TYL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /TYL: first_obs and last_obs produce in an empty array.
Aligned returns for /U:
Date
2001-02-01    0.848274
2001-03-01    0.842364
2001-05-01    0.775253
2001-06-01    0.429495
2001-08-01    0.486222
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /U:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                2.41309
Distribution:                  Normal   AIC:                           3.17382
Method:            Maximum Likelihood   BIC:                           5.43362
                                        No. Observations:                   13
Date:                Sun, Oct 13 2024   Df Residuals:                       12
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.1108  8.626e-02     12.877  6.070e-38 [  0.942,  1.280]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      5.5819e-03  4.142e-03      1.348      0.178 [-2.537e-03,1.370e-02]
alpha[1]       1.0000      0.649      1.541      0.123      [ -0.272,  2.272]
beta[1]    6.4923e-12      0.195  3.325e-11      1.000      [ -0.383,  0.383]
=============================================================================

Covariance estimator: robust
Aligned returns for /UA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UA: first_obs and last_obs produce in an empty array.
Aligned returns for /UAA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UAA: first_obs and last_obs produce in an empty array.
Aligned returns for /UAL:
Date
2001-02-01    0.441741
2001-03-01    0.445903
2001-05-01    0.441448
2001-06-01    0.425464
2001-08-01    0.412181
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-08-01  0.0248  0.0231
Results for /UAL:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1.67010
Distribution:                  Normal   AIC:                           4.65979
Method:            Maximum Likelihood   BIC:                           7.75015
                                        No. Observations:                   16
Date:                Sun, Oct 13 2024   Df Residuals:                       15
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8135  3.860e-02     21.076  1.312e-98 [  0.738,  0.889]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.6835e-03  2.067e-03      0.814      0.415 [-2.368e-03,5.735e-03]
alpha[1]       1.0000      0.337      2.969  2.988e-03      [  0.340,  1.660]
beta[1]    8.9089e-16      0.238  3.750e-15      1.000      [ -0.466,  0.466]
=============================================================================

Covariance estimator: robust
Aligned returns for /UBER:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UBER: first_obs and last_obs produce in an empty array.
Aligned returns for /UDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UDR: first_obs and last_obs produce in an empty array.
Aligned returns for /UGI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UGI: first_obs and last_obs produce in an empty array.
Aligned returns for /UHAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UHAL: first_obs and last_obs produce in an empty array.
Aligned returns for /UHS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UHS: first_obs and last_obs produce in an empty array.
Aligned returns for /UI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UI: first_obs and last_obs produce in an empty array.
Aligned returns for /ULTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ULTA: first_obs and last_obs produce in an empty array.
Aligned returns for /UNH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UNH: first_obs and last_obs produce in an empty array.
Aligned returns for /UNM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UNM: first_obs and last_obs produce in an empty array.
Aligned returns for /UNP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UNP: first_obs and last_obs produce in an empty array.
Aligned returns for /UPS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UPS: first_obs and last_obs produce in an empty array.
Aligned returns for /URI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /URI: first_obs and last_obs produce in an empty array.
Aligned returns for /USB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /USB: first_obs and last_obs produce in an empty array.
Aligned returns for /USFD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /USFD: first_obs and last_obs produce in an empty array.
Aligned returns for /UTHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UTHR: first_obs and last_obs produce in an empty array.
Aligned returns for /UWMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /UWMC: first_obs and last_obs produce in an empty array.
Aligned returns for /V:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /V: first_obs and last_obs produce in an empty array.
Aligned returns for /VAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VAC: first_obs and last_obs produce in an empty array.
Aligned returns for /VEEV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VEEV: first_obs and last_obs produce in an empty array.
Aligned returns for /VFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VFC: first_obs and last_obs produce in an empty array.
Aligned returns for /VICI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VICI: first_obs and last_obs produce in an empty array.
Aligned returns for /VIRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VIRT: first_obs and last_obs produce in an empty array.
Aligned returns for /VKTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VKTX: first_obs and last_obs produce in an empty array.
Aligned returns for /VLO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VLO: first_obs and last_obs produce in an empty array.
Aligned returns for /VLTO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VLTO: first_obs and last_obs produce in an empty array.
Aligned returns for /VMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VMC: first_obs and last_obs produce in an empty array.
Aligned returns for /VMI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VMI: first_obs and last_obs produce in an empty array.
Aligned returns for /VNO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VNO: first_obs and last_obs produce in an empty array.
Aligned returns for /VNOM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VNOM: first_obs and last_obs produce in an empty array.
Aligned returns for /VNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VNT: first_obs and last_obs produce in an empty array.
Aligned returns for /VOYA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VOYA: first_obs and last_obs produce in an empty array.
Aligned returns for /VRSK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VRSK: first_obs and last_obs produce in an empty array.
Aligned returns for /VRSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VRSN: first_obs and last_obs produce in an empty array.
Aligned returns for /VRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VRT: first_obs and last_obs produce in an empty array.
Aligned returns for /VRTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VRTX: first_obs and last_obs produce in an empty array.
Aligned returns for /VST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VST: first_obs and last_obs produce in an empty array.
Aligned returns for /VSTS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VSTS: first_obs and last_obs produce in an empty array.
Aligned returns for /VTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VTR: first_obs and last_obs produce in an empty array.
Aligned returns for /VTRS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []

Error fitting GARCH model for /VTRS: first_obs and last_obs produce in an empty array.
Aligned returns for /VVV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VVV: first_obs and last_obs produce in an empty array.
Aligned returns for /VZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /VZ: first_obs and last_obs produce in an empty array.
Aligned returns for /W:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /W: first_obs and last_obs produce in an empty array.
Aligned returns for /WAB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WAB: first_obs and last_obs produce in an empty array.
Aligned returns for /WAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WAL: first_obs and last_obs produce in an empty array.
Aligned returns for /WAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WAT: first_obs and last_obs produce in an empty array.
Aligned returns for /WBA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WBA: first_obs and last_obs produce in an empty array.
Aligned returns for /WBD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WBD: first_obs and last_obs produce in an empty array.
Aligned returns for /WBS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WBS: first_obs and last_obs produce in an empty array.
Aligned returns for /WCC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WCC: first_obs and last_obs produce in an empty array.
Aligned returns for /WDAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WDAY: first_obs and last_obs produce in an empty array.
Aligned returns for /WDC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WDC: first_obs and last_obs produce in an empty array.
Aligned returns for /WEC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WEC: first_obs and last_obs produce in an empty array.
Aligned returns for /WEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WEN: first_obs and last_obs produce in an empty array.
Aligned returns for /WEX:
Date
2001-05-01    0.971475
2001-06-01    0.986184
2001-10-01    1.089214
2001-11-01    1.151866
2002-05-01    1.398736
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-05-01  0.0250  0.0336
2001-06-01  0.0624 -0.0112
2001-10-01  0.0748 -0.0765
2001-11-01 -0.0047  0.0221
2002-05-01 -0.0321  0.0153
Results for /WEX:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                19.5867
Distribution:                  Normal   AIC:                          -31.1734
Method:            Maximum Likelihood   BIC:                          -21.8505
                                        No. Observations:                   76
Date:                Sun, Oct 13 2024   Df Residuals:                       75
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7169  3.725e-02     19.242  1.632e-82 [  0.644,  0.790]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      7.6084e-03  5.671e-03      1.342      0.180 [-3.507e-03,1.872e-02]
alpha[1]       1.0000      1.120      0.893      0.372      [ -1.195,  3.195]
beta[1]        0.0000      0.732      0.000      1.000      [ -1.435,  1.435]
=============================================================================

Covariance estimator: robust
Aligned returns for /WFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WFC: first_obs and last_obs produce in an empty array.
Aligned returns for /WFRD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WFRD: first_obs and last_obs produce in an empty array.
Aligned returns for /WH:
Date
2009-04-01    0.937506
2009-05-01    0.916314
2009-06-01    0.918207
2009-07-01    0.958199
2009-09-01    0.983676
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2009-04-01  0.0539  0.0536
2009-05-01 -0.0252  0.0028
2009-06-01  0.0263 -0.0273
2009-07-01  0.0187  0.0483
2009-09-01  0.0243  0.0104
Results for /WH:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -8.17640
Distribution:                  Normal   AIC:                           24.3528
Method:            Maximum Likelihood   BIC:                           31.4896
                                        No. Observations:                   44
Date:                Sun, Oct 13 2024   Df Residuals:                       43
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8411  6.200e-02     13.566  6.330e-42 [  0.720,  0.963]
                              Volatility Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
omega          0.0488  4.210e-02      1.158      0.247 [-3.376e-02,  0.131]
alpha[1]       0.5492      0.146      3.771  1.625e-04    [  0.264,  0.835]
beta[1]    8.8057e-15      0.128  6.881e-14      1.000    [ -0.251,  0.251]
===========================================================================

Covariance estimator: robust
Aligned returns for /WHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WHR: first_obs and last_obs produce in an empty array.
Aligned returns for /WING:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WING: first_obs and last_obs produce in an empty array.
Aligned returns for /WLK:
Date
2001-02-01    1.378239
2001-03-01    1.528605
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               smb     hml
Date
2001-02-01 -0.0078  0.1247
2001-03-01  0.0025  0.0642
Results for /WLK:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                2.33778
Distribution:                  Normal   AIC:                           3.32445
Method:            Maximum Likelihood   BIC:                          -1.90297
                                        No. Observations:                    2
Date:                Sun, Oct 13 2024   Df Residuals:                        1
Time:                        22:28:05   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.4534  8.443e-02     17.215  2.045e-66 [  1.288,  1.619]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.6958e-03  1.598e-04     10.610  2.675e-26 [1.383e-03,2.009e-03]
alpha[1]       0.0100  5.668e-02      0.176      0.860     [ -0.101,  0.121]
beta[1]        0.6900      0.383      1.800  7.184e-02  [-6.127e-02,  1.441]
============================================================================

Covariance estimator: robust
Aligned returns for /WM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WM: first_obs and last_obs produce in an empty array.
Aligned returns for /WMB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WMB: first_obs and last_obs produce in an empty array.
Aligned returns for /WMS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WMS: first_obs and last_obs produce in an empty array.
Aligned returns for /WMT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WMT: first_obs and last_obs produce in an empty array.
Aligned returns for /WOLF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WOLF: first_obs and last_obs produce in an empty array.
Aligned returns for /WPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WPC: first_obs and last_obs produce in an empty array.
Aligned returns for /WRB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WRB: first_obs and last_obs produce in an empty array.
Aligned returns for /WSC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WSC: first_obs and last_obs produce in an empty array.
Aligned returns for /WSM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WSM: first_obs and last_obs produce in an empty array.
Aligned returns for /WSO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WSO: first_obs and last_obs produce in an empty array.
Aligned returns for /WST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WST: first_obs and last_obs produce in an empty array.
Aligned returns for /WTFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WTFC: first_obs and last_obs produce in an empty array.
Aligned returns for /WTM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WTM: first_obs and last_obs produce in an empty array.
Aligned returns for /WTRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WTRG: first_obs and last_obs produce in an empty array.
Aligned returns for /WTW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WTW: first_obs and last_obs produce in an empty array.
Aligned returns for /WU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WU: first_obs and last_obs produce in an empty array.
Aligned returns for /WWD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WWD: first_obs and last_obs produce in an empty array.
Aligned returns for /WY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WY: first_obs and last_obs produce in an empty array.
Aligned returns for /WYNN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /WYNN: first_obs and last_obs produce in an empty array.
Aligned returns for /X:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /X: first_obs and last_obs produce in an empty array.
Aligned returns for /XEL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /XEL: first_obs and last_obs produce in an empty array.
Aligned returns for /XOM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /XOM: first_obs and last_obs produce in an empty array.
Aligned returns for /XP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /XP: first_obs and last_obs produce in an empty array.
Aligned returns for /XPO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /XPO: first_obs and last_obs produce in an empty array.
Aligned returns for /XRAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /XRAY: first_obs and last_obs produce in an empty array.
Aligned returns for /XYL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /XYL: first_obs and last_obs produce in an empty array.
Aligned returns for /YETI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /YETI: first_obs and last_obs produce in an empty array.
Aligned returns for /YUM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /YUM: first_obs and last_obs produce in an empty array.
Aligned returns for /Z:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /Z: first_obs and last_obs produce in an empty array.
Aligned returns for /ZBH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZBH: first_obs and last_obs produce in an empty array.
Aligned returns for /ZBRA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZBRA: first_obs and last_obs produce in an empty array.
Aligned returns for /ZG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZG: first_obs and last_obs produce in an empty array.
Aligned returns for /ZI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZI: first_obs and last_obs produce in an empty array.
Aligned returns for /ZION:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZION: first_obs and last_obs produce in an empty array.
Aligned returns for /ZM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZM: first_obs and last_obs produce in an empty array.
Aligned returns for /ZS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZS: first_obs and last_obs produce in an empty array.
Aligned returns for /ZTS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /ZTS: first_obs and last_obs produce in an empty array.
Aligned returns for /BRK/B:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [smb, hml]
Index: []
Error fitting GARCH model for /BRK/B: first_obs and last_obs produce in an empty array.

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.07355. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.005653. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

In [19]:
for ticker, data in stock_data.items():
    
    r_vol = data['r_vol']
    
    if r_vol.index.duplicated().any():
        print(f"Duplicates found in returns for {ticker}. Resolving...")
        r_vol =\
        (
            r_vol
            [~r_vol.index.duplicated(keep='first')]
        )
    
    if fama_french.index.duplicated().any():
        print("Duplicates found in Fama-French factors. Resolving...")
        fama_french =\
        (
            fama_french
            [~fama_french.index.duplicated(keep='first')]
        )

    r_vol.index =\
    (
        pd
        .to_datetime
        (r_vol.index)
    )
    
    fama_french.index =\
    (
        pd
        .to_datetime
        (fama_french.index)
    )
    
    aligned_factors =\
    (
        pd
        .merge_asof(r_vol.sort_index(), 
                    fama_french.sort_index(), 
                    left_index=True, 
                    right_index=True, 
                    direction='backward')
    )
    
    aligned_factors =\
    (
        aligned_factors
        .dropna()
    )

    aligned_r_vol =\
    (
        r_vol
        .loc
        [aligned_factors.index]
    )

    print(f"Aligned returns for {ticker}:\n{aligned_r_vol.head()}")
    
    print(f"Aligned Fama-French factors:\n{aligned_factors.head()}")
    
    model =\
    (
        arch_model(aligned_r_vol,
                   vol='Garch',
                   p=1, 
                   q=1,
                   x=aligned_factors.values,
                   dist='Normal')
    )
    
    try:
        results =\
        (
            model
            .fit
            (disp='off')
        )
        
        print(f"Results for {ticker}:")
        
        print(results.summary())
        
    except Exception as e:
        
        print(f"Error fitting GARCH model for {ticker}: {e}")

Aligned returns for /A:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /A: first_obs and last_obs produce in an empty array.
Aligned returns for /AA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AA: first_obs and last_obs produce in an empty array.
Aligned returns for /AAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AAL: first_obs and last_obs produce in an empty array.
Aligned returns for /AAON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AAON: first_obs and last_obs produce in an empty array.
Aligned returns for /AAP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AAP: first_obs and last_obs produce in an empty array.
Aligned returns for /AAPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AAPL: first_obs and last_obs produce in an empty array.
Aligned returns for /ABBV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ABBV: first_obs and last_obs produce in an empty array.
Aligned returns for /ABNB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ABNB: first_obs and last_obs produce in an empty array.
Aligned returns for /ABT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ABT: first_obs and last_obs produce in an empty array.
Aligned returns for /ACGL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ACGL: first_obs and last_obs produce in an empty array.
Aligned returns for /ACHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ACHC: first_obs and last_obs produce in an empty array.
Aligned returns for /ACI:
Date
2001-01-02    0.698037
2001-01-03    0.698134
2001-01-04    0.697538
2001-01-05    0.698202
2001-01-08    0.698465
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.698037  0.0668 -0.0507
2001-01-03  0.698134  0.0668 -0.0507
2001-01-04  0.697538  0.0668 -0.0507
2001-01-05  0.698202  0.0668 -0.0507
2001-01-08  0.698465  0.0668 -0.0507
Results for /ACI:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1561.95
Distribution:                  Normal   AIC:                          -3115.89
Method:            Maximum Likelihood   BIC:                          -3090.94
                                        No. Observations:                 3778
Date:                Mon, Oct 14 2024   Df Residuals:                     3777
Time:                        14:49:23   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5182  5.302e-03     97.740      0.000 [  0.508,  0.529]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.2304e-03  6.777e-05     47.668      0.000 [3.098e-03,3.363e-03]
alpha[1]       0.2000  1.140e-02     17.543  6.709e-69     [  0.178,  0.222]
beta[1]        0.7800  5.932e-03    131.485      0.000     [  0.768,  0.792]
============================================================================

Covariance estimator: robust
Aligned returns for /ACM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ACM: first_obs and last_obs produce in an empty array.
Aligned returns for /ACN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ACN: first_obs and last_obs produce in an empty array.
Aligned returns for /ADBE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ADBE: first_obs and last_obs produce in an empty array.
Aligned returns for /ADC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ADC: first_obs and last_obs produce in an empty array.
Aligned returns for /ADI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ADI: first_obs and last_obs produce in an empty array.
Aligned returns for /ADM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ADM: first_obs and last_obs produce in an empty array.
Aligned returns for /ADP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ADP: first_obs and last_obs produce in an empty array.
Aligned returns for /ADSK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ADSK: first_obs and last_obs produce in an empty array.
Aligned returns for /ADT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ADT: first_obs and last_obs produce in an empty array.
Aligned returns for /AEE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AEE: first_obs and last_obs produce in an empty array.
Aligned returns for /AEP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AEP: first_obs and last_obs produce in an empty array.
Aligned returns for /AES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AES: first_obs and last_obs produce in an empty array.
Aligned returns for /AFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AFG: first_obs and last_obs produce in an empty array.
Aligned returns for /AFL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AFL: first_obs and last_obs produce in an empty array.
Aligned returns for /AFRM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AFRM: first_obs and last_obs produce in an empty array.
Aligned returns for /AGCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AGCO: first_obs and last_obs produce in an empty array.
Aligned returns for /AGNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AGNC: first_obs and last_obs produce in an empty array.
Aligned returns for /AGO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AGO: first_obs and last_obs produce in an empty array.
Aligned returns for /AGR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AGR: first_obs and last_obs produce in an empty array.
Aligned returns for /AIG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AIG: first_obs and last_obs produce in an empty array.
Aligned returns for /AIZ:
Date
2001-01-02    0.530859
2001-01-03    0.530712
2001-01-04    0.528422
2001-01-05    0.528538
2001-01-08    0.532007
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.530859  0.0668 -0.0507
2001-01-03  0.530712  0.0668 -0.0507
2001-01-04  0.528422  0.0668 -0.0507
2001-01-05  0.528538  0.0668 -0.0507
2001-01-08  0.532007  0.0668 -0.0507
Results for /AIZ:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                578.196
Distribution:                  Normal   AIC:                          -1148.39
Method:            Maximum Likelihood   BIC:                          -1131.09
                                        No. Observations:                  558
Date:                Mon, Oct 14 2024   Df Residuals:                      557
Time:                        14:49:23   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4537  2.832e-02     16.020  9.300e-58 [  0.398,  0.509]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.6088e-04  6.559e-05      5.502  3.755e-08 [2.323e-04,4.894e-04]
alpha[1]       0.2000  3.371e-02      5.933  2.980e-09     [  0.134,  0.266]
beta[1]        0.7799  3.516e-02     22.182 5.122e-109     [  0.711,  0.849]
============================================================================

Covariance estimator: robust
Aligned returns for /AJG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AJG: first_obs and last_obs produce in an empty array.
Aligned returns for /AKAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AKAM: first_obs and last_obs produce in an empty array.
Aligned returns for /AL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AL: first_obs and last_obs produce in an empty array.
Aligned returns for /ALAB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALAB: first_obs and last_obs produce in an empty array.
Aligned returns for /ALB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALB: first_obs and last_obs produce in an empty array.
Aligned returns for /ALGM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01805. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.07429. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /ALGM: first_obs and last_obs produce in an empty array.
Aligned returns for /ALGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALGN: first_obs and last_obs produce in an empty array.
Aligned returns for /ALK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALK: first_obs and last_obs produce in an empty array.
Aligned returns for /ALL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALL: first_obs and last_obs produce in an empty array.
Aligned returns for /ALLE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALLE: first_obs and last_obs produce in an empty array.
Aligned returns for /ALLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALLY: first_obs and last_obs produce in an empty array.
Aligned returns for /ALNY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALNY: first_obs and last_obs produce in an empty array.
Aligned returns for /ALSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ALSN: first_obs and last_obs produce in an empty array.
Aligned returns for /AM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AM: first_obs and last_obs produce in an empty array.
Aligned returns for /AMAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMAT: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /AMCR. Resolving...
Aligned returns for /AMCR:
Date
2000-12-08    3.073656
2000-12-11    3.073645
2000-12-12    3.073067
2000-12-13    3.072873
2000-12-14    3.068985
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2000-12-08  3.073656  0.0073  0.0761
2000-12-11  3.073645  0.0073  0.0761
2000-12-12  3.073067  0.0073  0.0761
2000-12-13  3.072873  0.0073  0.0761
2000-12-14  3.068985  0.0073  0.0761
Results for /AMCR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                3688.89
Distribution:                  Normal   AIC:                          -7369.77
Method:            Maximum Likelihood   BIC:                          -7348.19
                                        No. Observations:                 1630
Date:                Mon, Oct 14 2024   Df Residuals:                     1629
Time:                        14:49:23   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2457  3.298e-02      7.450  9.302e-14 [  0.181,  0.310]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      6.9444e-06  2.454e-06      2.829  4.664e-03  [2.134e-06,1.175e-05]
alpha[1]       0.9691      0.422      2.299  2.150e-02      [  0.143,  1.795]
beta[1]    7.1958e-05  3.605e-02  1.996e-03      0.998 [-7.058e-02,7.072e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /AMD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMD: first_obs and last_obs produce in an empty array.
Aligned returns for /AME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AME: first_obs and last_obs produce in an empty array.
Aligned returns for /AMED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMED: first_obs and last_obs produce in an empty array.
Aligned returns for /AMG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMG: first_obs and last_obs produce in an empty array.
Aligned returns for /AMGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMGN: first_obs and last_obs produce in an empty array.
Aligned returns for /AMH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMH: first_obs and last_obs produce in an empty array.
Aligned returns for /AMKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMKR: first_obs and last_obs produce in an empty array.
Aligned returns for /AMP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMP: first_obs and last_obs produce in an empty array.
Aligned returns for /AMT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMT: first_obs and last_obs produce in an empty array.
Aligned returns for /AMZN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AMZN: first_obs and last_obs produce in an empty array.
Aligned returns for /AN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AN: first_obs and last_obs produce in an empty array.
Aligned returns for /ANET:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ANET: first_obs and last_obs produce in an empty array.
Aligned returns for /ANSS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ANSS: first_obs and last_obs produce in an empty array.
Aligned returns for /AON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AON: first_obs and last_obs produce in an empty array.
Aligned returns for /AOS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AOS: first_obs and last_obs produce in an empty array.
Aligned returns for /APA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /APA: first_obs and last_obs produce in an empty array.
Aligned returns for /APD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /APD: first_obs and last_obs produce in an empty array.
Aligned returns for /APG:
Date
2001-02-13    1.800048
2001-02-14    1.525015
2001-02-15    1.523723
2001-02-16    1.524027
2001-02-20    1.524784
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-02-13  1.800048 -0.0078  0.1247
2001-02-14  1.525015 -0.0078  0.1247
2001-02-15  1.523723 -0.0078  0.1247
2001-02-16  1.524027 -0.0078  0.1247
2001-02-20  1.524784 -0.0078  0.1247

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.04169. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /APG:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                463.136
Distribution:                  Normal   AIC:                          -918.273
Method:            Maximum Likelihood   BIC:                          -903.580
                                        No. Observations:                  291
Date:                Mon, Oct 14 2024   Df Residuals:                      290
Time:                        14:49:24   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.5897  7.644e-04   2079.553      0.000 [  1.588,  1.591]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.2226e-05  1.623e-08    753.099      0.000  [1.219e-05,1.226e-05]
alpha[1]       1.0000  4.125e-02     24.245 7.423e-130      [  0.919,  1.081]
beta[1]    6.9822e-11  2.957e-02  2.362e-09      1.000 [-5.795e-02,5.795e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /APH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /APH: first_obs and last_obs produce in an empty array.
Aligned returns for /APLS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /APLS: first_obs and last_obs produce in an empty array.
Aligned returns for /APO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /APO: first_obs and last_obs produce in an empty array.
Aligned returns for /APP:
Date
2007-04-30    0.263769
2007-05-01    0.263958
2007-05-02    0.266039
2007-05-03    0.268377
2007-05-04    0.272171
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2007-04-30  0.263769 -0.0216 -0.0145
2007-05-01  0.263958  0.0024 -0.0065
2007-05-02  0.266039  0.0024 -0.0065
2007-05-03  0.268377  0.0024 -0.0065
2007-05-04  0.272171  0.0024 -0.0065
Results for /APP:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                378.366
Distribution:                  Normal   AIC:                          -748.731
Method:            Maximum Likelihood   BIC:                          -726.087
                                        No. Observations:                 2124
Date:                Mon, Oct 14 2024   Df Residuals:                     2123
Time:                        14:49:24   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8474  1.420e-02     59.693      0.000 [  0.820,  0.875]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.7814e-03  9.773e-05     18.227  3.174e-74 [1.590e-03,1.973e-03]
alpha[1]       0.2000  1.044e-02     19.163  7.566e-82     [  0.180,  0.220]
beta[1]        0.7800  1.026e-02     76.005      0.000     [  0.760,  0.800]
============================================================================

Covariance estimator: robust
Aligned returns for /APPF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /APPF: first_obs and last_obs produce in an empty array.
Aligned returns for /APTV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /APTV: first_obs and last_obs produce in an empty array.
Aligned returns for /AR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AR: first_obs and last_obs produce in an empty array.
Aligned returns for /ARE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ARE: first_obs and last_obs produce in an empty array.
Aligned returns for /ARES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ARES: first_obs and last_obs produce in an empty array.
Aligned returns for /ARMK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ARMK: first_obs and last_obs produce in an empty array.
Aligned returns for /ARW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ARW: first_obs and last_obs produce in an empty array.
Aligned returns for /ASH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ASH: first_obs and last_obs produce in an empty array.
Aligned returns for /ATI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ATI: first_obs and last_obs produce in an empty array.

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.08907. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Aligned returns for /ATO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ATO: first_obs and last_obs produce in an empty array.
Aligned returns for /ATR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ATR: first_obs and last_obs produce in an empty array.
Aligned returns for /AVB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AVB: first_obs and last_obs produce in an empty array.
Aligned returns for /AVGO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AVGO: first_obs and last_obs produce in an empty array.
Aligned returns for /AVT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AVT: first_obs and last_obs produce in an empty array.
Aligned returns for /AVTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AVTR: first_obs and last_obs produce in an empty array.
Aligned returns for /AVY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AVY: first_obs and last_obs produce in an empty array.
Aligned returns for /AWI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AWI: first_obs and last_obs produce in an empty array.
Aligned returns for /AWK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AWK: first_obs and last_obs produce in an empty array.
Aligned returns for /AXON:
Date
2016-06-10    0.871585
2016-06-13    0.827657
2016-06-14    0.827701
2016-06-15    0.827124
2016-06-16    0.826684
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2016-06-10  0.871585  0.0061 -0.0148
2016-06-13  0.827657  0.0061 -0.0148
2016-06-14  0.827701  0.0061 -0.0148
2016-06-15  0.827124  0.0061 -0.0148
2016-06-16  0.826684  0.0061 -0.0148
Results for /AXON:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                349.805
Distribution:                  Normal   AIC:                          -691.611
Method:            Maximum Likelihood   BIC:                          -669.841
                                        No. Observations:                 1707
Date:                Mon, Oct 14 2024   Df Residuals:                     1706
Time:                        14:49:24   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.0080  9.013e-05  1.118e+04      0.000 [  1.008,  1.008]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.0748e-06  2.962e-07     10.380  3.063e-25  [2.494e-06,3.655e-06]
alpha[1]       1.0000  4.115e-02     24.301 1.891e-130      [  0.919,  1.081]
beta[1]    3.4423e-10  3.211e-04  1.072e-06      1.000 [-6.294e-04,6.294e-04]
=============================================================================

Covariance estimator: robust
Aligned returns for /AXP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AXP: first_obs and last_obs produce in an empty array.
Aligned returns for /AXS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AXS: first_obs and last_obs produce in an empty array.
Aligned returns for /AXTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AXTA: first_obs and last_obs produce in an empty array.
Aligned returns for /AYI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AYI: first_obs and last_obs produce in an empty array.
Aligned returns for /AZEK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AZEK: first_obs and last_obs produce in an empty array.
Aligned returns for /AZO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AZO: first_obs and last_obs produce in an empty array.
Aligned returns for /AZPN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AZPN: first_obs and last_obs produce in an empty array.
Aligned returns for /AZTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /AZTA: first_obs and last_obs produce in an empty array.
Aligned returns for /BA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BA: first_obs and last_obs produce in an empty array.
Aligned returns for /BAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BAC: first_obs and last_obs produce in an empty array.
Aligned returns for /BAH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BAH: first_obs and last_obs produce in an empty array.
Aligned returns for /BALL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BALL: first_obs and last_obs produce in an empty array.
Aligned returns for /BAX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BAX: first_obs and last_obs produce in an empty array.
Aligned returns for /BBWI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BBWI: first_obs and last_obs produce in an empty array.
Aligned returns for /BBY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BBY: first_obs and last_obs produce in an empty array.
Aligned returns for /BC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BC: first_obs and last_obs produce in an empty array.
Aligned returns for /BDX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BDX: first_obs and last_obs produce in an empty array.
Aligned returns for /BEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BEN: first_obs and last_obs produce in an empty array.
Aligned returns for /BEPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BEPC: first_obs and last_obs produce in an empty array.
Aligned returns for /BERY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BERY: first_obs and last_obs produce in an empty array.
Aligned returns for /BFAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BFAM: first_obs and last_obs produce in an empty array.
Aligned returns for /BG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BG: first_obs and last_obs produce in an empty array.
Aligned returns for /BHF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BHF: first_obs and last_obs produce in an empty array.
Aligned returns for /BIIB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BIIB: first_obs and last_obs produce in an empty array.
Aligned returns for /BILL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BILL: first_obs and last_obs produce in an empty array.
Aligned returns for /BIO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BIO: first_obs and last_obs produce in an empty array.

Aligned returns for /BIRK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BIRK: first_obs and last_obs produce in an empty array.
Aligned returns for /BJ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BJ: first_obs and last_obs produce in an empty array.
Aligned returns for /BK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BK: first_obs and last_obs produce in an empty array.
Aligned returns for /BKNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BKNG: first_obs and last_obs produce in an empty array.
Aligned returns for /BKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BKR: first_obs and last_obs produce in an empty array.
Aligned returns for /BLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BLD: first_obs and last_obs produce in an empty array.
Aligned returns for /BLDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BLDR: first_obs and last_obs produce in an empty array.
Aligned returns for /BLK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BLK: first_obs and last_obs produce in an empty array.
Aligned returns for /BMRN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BMRN: first_obs and last_obs produce in an empty array.
Aligned returns for /BMY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BMY: first_obs and last_obs produce in an empty array.
Aligned returns for /BOKF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BOKF: first_obs and last_obs produce in an empty array.
Aligned returns for /BPOP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BPOP: first_obs and last_obs produce in an empty array.
Aligned returns for /BR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BR: first_obs and last_obs produce in an empty array.
Aligned returns for /BRBR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BRBR: first_obs and last_obs produce in an empty array.
Aligned returns for /BRKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BRKR: first_obs and last_obs produce in an empty array.
Aligned returns for /BRO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BRO: first_obs and last_obs produce in an empty array.
Aligned returns for /BROS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BROS: first_obs and last_obs produce in an empty array.
Aligned returns for /BRX:
Date
2001-01-02    1.714719
2001-01-03    1.716794
2001-01-04    1.716794
2001-01-05    1.720588
2001-01-08    1.716403
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  1.714719  0.0668 -0.0507
2001-01-03  1.716794  0.0668 -0.0507
2001-01-04  1.716794  0.0668 -0.0507
2001-01-05  1.720588  0.0668 -0.0507
2001-01-08  1.716403  0.0668 -0.0507
Results for /BRX:

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.003659. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02199. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:766: ConvergenceWarning: The optimizer returned code 4. The message is:
Inequality constraints incompatible
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(

                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                90.0390
Distribution:                  Normal   AIC:                          -172.078
Method:            Maximum Likelihood   BIC:                          -164.430
                                        No. Observations:                   50
Date:                Mon, Oct 14 2024   Df Residuals:                       49
Time:                        14:49:25   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.7873  2.570e-03    695.418      0.000 [  1.782,  1.792]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.2974e-05  1.937e-05      2.735  6.231e-03 [1.502e-05,9.093e-05]
alpha[1]       0.9503      0.135      7.062  1.638e-12     [  0.687,  1.214]
beta[1]        0.0497  8.787e-02      0.566      0.572     [ -0.123,  0.222]
============================================================================

Covariance estimator: robust
Aligned returns for /BSX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BSX: first_obs and last_obs produce in an empty array.
Aligned returns for /BSY:
Date
2001-04-30    0.702663
2001-05-02    0.702650
2001-05-03    0.703100
2001-05-04    0.703263
2001-05-07    0.702986
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-04-30  0.702663  0.0055 -0.0467
2001-05-02  0.702650  0.0250  0.0336
2001-05-03  0.703100  0.0250  0.0336
2001-05-04  0.703263  0.0250  0.0336
2001-05-07  0.702986  0.0250  0.0336
Results for /BSY:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                2058.95
Distribution:                  Normal   AIC:                          -4109.90
Method:            Maximum Likelihood   BIC:                          -4087.02
                                        No. Observations:                 2252
Date:                Mon, Oct 14 2024   Df Residuals:                     2251
Time:                        14:49:25   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3016  1.469e-03    205.259      0.000 [  0.299,  0.304]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      4.4274e-04  1.892e-05     23.395 4.774e-121 [4.057e-04,4.798e-04]
alpha[1]       0.2000  7.867e-03     25.422 1.425e-142     [  0.185,  0.215]
beta[1]        0.7800  8.099e-03     96.306      0.000     [  0.764,  0.796]
============================================================================

Covariance estimator: robust
WARNING: The optimizer did not indicate successful convergence. The message was Inequality constraints incompatible.
See convergence_flag.

Aligned returns for /BURL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BURL: first_obs and last_obs produce in an empty array.
Aligned returns for /BWA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BWA: first_obs and last_obs produce in an empty array.
Aligned returns for /BWXT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BWXT: first_obs and last_obs produce in an empty array.
Aligned returns for /BX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BX: first_obs and last_obs produce in an empty array.
Aligned returns for /BXP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BXP: first_obs and last_obs produce in an empty array.
Aligned returns for /BYD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BYD: first_obs and last_obs produce in an empty array.
Aligned returns for /C:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /C: first_obs and last_obs produce in an empty array.
Aligned returns for /CACC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CACC: first_obs and last_obs produce in an empty array.
Aligned returns for /CACI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CACI: first_obs and last_obs produce in an empty array.
Aligned returns for /CAG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CAG: first_obs and last_obs produce in an empty array.
Aligned returns for /CAH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CAH: first_obs and last_obs produce in an empty array.
Aligned returns for /CAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CAR: first_obs and last_obs produce in an empty array.
Aligned returns for /CARR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CARR: first_obs and last_obs produce in an empty array.
Aligned returns for /CART:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CART: first_obs and last_obs produce in an empty array.
Aligned returns for /CASY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CASY: first_obs and last_obs produce in an empty array.
Aligned returns for /CAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CAT: first_obs and last_obs produce in an empty array.
Aligned returns for /CAVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CAVA: first_obs and last_obs produce in an empty array.
Aligned returns for /CB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CB: first_obs and last_obs produce in an empty array.
Aligned returns for /CBOE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CBOE: first_obs and last_obs produce in an empty array.
Aligned returns for /CBRE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CBRE: first_obs and last_obs produce in an empty array.
Aligned returns for /CBSH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

Error fitting GARCH model for /CBSH: first_obs and last_obs produce in an empty array.
Aligned returns for /CC:
Date
2001-01-02    0.930737
2001-01-03    0.946451
2001-01-04    0.947178
2001-01-05    0.951812
2001-01-08    0.951987
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.930737  0.0668 -0.0507
2001-01-03  0.946451  0.0668 -0.0507
2001-01-04  0.947178  0.0668 -0.0507
2001-01-05  0.951812  0.0668 -0.0507
2001-01-08  0.951987  0.0668 -0.0507
Results for /CC:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                967.130
Distribution:                  Normal   AIC:                          -1926.26
Method:            Maximum Likelihood   BIC:                          -1903.91
                                        No. Observations:                 1975
Date:                Mon, Oct 14 2024   Df Residuals:                     1974
Time:                        14:49:25   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3951  2.994e-03    131.956      0.000 [  0.389,  0.401]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      9.7741e-04  3.497e-05     27.951 6.353e-172 [9.089e-04,1.046e-03]
alpha[1]       0.1998  6.871e-03     29.073 7.787e-186     [  0.186,  0.213]
beta[1]        0.7791  7.413e-03    105.103      0.000     [  0.765,  0.794]
============================================================================

Covariance estimator: robust
Aligned returns for /CCCS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CCCS: first_obs and last_obs produce in an empty array.
Aligned returns for /CCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CCI: first_obs and last_obs produce in an empty array.
Aligned returns for /CCK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CCK: first_obs and last_obs produce in an empty array.
Aligned returns for /CCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CCL: first_obs and last_obs produce in an empty array.
Aligned returns for /CDNS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CDNS: first_obs and last_obs produce in an empty array.
Aligned returns for /CDW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CDW: first_obs and last_obs produce in an empty array.
Aligned returns for /CE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CE: first_obs and last_obs produce in an empty array.
Aligned returns for /CEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CEG: first_obs and last_obs produce in an empty array.
Aligned returns for /CELH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CELH: first_obs and last_obs produce in an empty array.
Aligned returns for /CERT:
Date
2001-05-02    1.378656
2001-05-03    1.378323
2001-05-04    1.378286
2001-05-07    1.378256
2001-05-08    1.378267
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol    smb     hml
Date
2001-05-02  1.378656  0.025  0.0336
2001-05-03  1.378323  0.025  0.0336
2001-05-04  1.378286  0.025  0.0336
2001-05-07  1.378256  0.025  0.0336
2001-05-08  1.378267  0.025  0.0336
Results for /CERT:

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.0489. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.00462. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                484.359
Distribution:                  Normal   AIC:                          -960.718
Method:            Maximum Likelihood   BIC:                          -946.179
                                        No. Observations:                  280
Date:                Mon, Oct 14 2024   Df Residuals:                      279
Time:                        14:49:25   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.3703  1.885e-03    726.786      0.000 [  1.367,  1.374]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      9.3095e-05  4.805e-05      1.937  5.271e-02 [-1.089e-06,1.873e-04]
alpha[1]       0.2000  1.584e-02     12.630  1.439e-36      [  0.169,  0.231]
beta[1]        0.7800  2.953e-02     26.416 8.884e-154      [  0.722,  0.838]
=============================================================================

Covariance estimator: robust
Aligned returns for /CF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CF: first_obs and last_obs produce in an empty array.
Aligned returns for /CFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CFG: first_obs and last_obs produce in an empty array.
Aligned returns for /CFLT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CFLT: first_obs and last_obs produce in an empty array.
Aligned returns for /CFR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CFR: first_obs and last_obs produce in an empty array.
Aligned returns for /CG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CG: first_obs and last_obs produce in an empty array.
Aligned returns for /CGNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CGNX: first_obs and last_obs produce in an empty array.
Aligned returns for /CHD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CHD: first_obs and last_obs produce in an empty array.
Aligned returns for /CHDN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CHDN: first_obs and last_obs produce in an empty array.
Aligned returns for /CHE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CHE: first_obs and last_obs produce in an empty array.
Aligned returns for /CHH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CHH: first_obs and last_obs produce in an empty array.
Aligned returns for /CHK:
Date
2001-01-02    0.726882
2001-01-03    0.721197
2001-01-04    0.722376
2001-01-05    0.723324
2001-01-08    0.726239
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.726882  0.0668 -0.0507
2001-01-03  0.721197  0.0668 -0.0507
2001-01-04  0.722376  0.0668 -0.0507
2001-01-05  0.723324  0.0668 -0.0507
2001-01-08  0.726239  0.0668 -0.0507
Results for /CHK:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1937.40
Distribution:                  Normal   AIC:                          -3866.79
Method:            Maximum Likelihood   BIC:                          -3840.80
                                        No. Observations:                 4902
Date:                Mon, Oct 14 2024   Df Residuals:                     4901
Time:                        14:49:26   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4172  3.503e-03    119.097      0.000 [  0.410,  0.424]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.1385e-03  7.620e-05     67.437      0.000 [4.989e-03,5.288e-03]
alpha[1]       0.1817  4.455e-03     40.778      0.000     [  0.173,  0.190]
beta[1]        0.6920  4.432e-03    156.124      0.000     [  0.683,  0.701]
============================================================================

Covariance estimator: robust
Aligned returns for /CHRD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CHRD: first_obs and last_obs produce in an empty array.
Aligned returns for /CHRW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CHRW: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /CHTR. Resolving...
Aligned returns for /CHTR:
Date
2001-01-02    0.870028
2001-01-03    0.871076
2001-01-04    0.871223
2001-01-05    0.873528
2001-01-08    0.873566
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.870028  0.0668 -0.0507
2001-01-03  0.871076  0.0668 -0.0507
2001-01-04  0.871223  0.0668 -0.0507
2001-01-05  0.873528  0.0668 -0.0507
2001-01-08  0.873566  0.0668 -0.0507
Results for /CHTR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1628.83
Distribution:                  Normal   AIC:                          -3249.66
Method:            Maximum Likelihood   BIC:                          -3226.44
                                        No. Observations:                 2456
Date:                Mon, Oct 14 2024   Df Residuals:                     2455
Time:                        14:49:26   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4811  1.569e-03    306.574      0.000 [  0.478,  0.484]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.8987e-03  1.213e-04     48.645      0.000 [5.661e-03,6.136e-03]
alpha[1]       0.5226  9.159e-03     57.055      0.000     [  0.505,  0.541]
beta[1]        0.2649  1.528e-02     17.330  2.783e-67     [  0.235,  0.295]
============================================================================

Covariance estimator: robust
Aligned returns for /CI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CI: first_obs and last_obs produce in an empty array.
Aligned returns for /CIEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CIEN: first_obs and last_obs produce in an empty array.
Aligned returns for /CINF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CINF: first_obs and last_obs produce in an empty array.
Aligned returns for /CIVI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CIVI: first_obs and last_obs produce in an empty array.
Aligned returns for /CL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06144. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /CL: first_obs and last_obs produce in an empty array.
Aligned returns for /CLF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CLF: first_obs and last_obs produce in an empty array.
Aligned returns for /CLH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CLH: first_obs and last_obs produce in an empty array.
Aligned returns for /CLVT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CLVT: first_obs and last_obs produce in an empty array.
Aligned returns for /CLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CLX: first_obs and last_obs produce in an empty array.
Aligned returns for /CMA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CMA: first_obs and last_obs produce in an empty array.
Aligned returns for /CMCSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CMCSA: first_obs and last_obs produce in an empty array.
Aligned returns for /CME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CME: first_obs and last_obs produce in an empty array.
Aligned returns for /CMG:
Date
2001-01-02    0.663183
2001-01-03    0.661534
2001-01-04    0.661763
2001-01-05    0.646476
2001-01-08    0.639833
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.663183  0.0668 -0.0507
2001-01-03  0.661534  0.0668 -0.0507
2001-01-04  0.661763  0.0668 -0.0507
2001-01-05  0.646476  0.0668 -0.0507
2001-01-08  0.639833  0.0668 -0.0507
Results for /CMG:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1069.41
Distribution:                  Normal   AIC:                          -2130.82
Method:            Maximum Likelihood   BIC:                          -2104.91
                                        No. Observations:                 4810
Date:                Mon, Oct 14 2024   Df Residuals:                     4809
Time:                        14:49:26   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5025  3.183e-03    157.854      0.000 [  0.496,  0.509]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      6.4298e-03  9.541e-05     67.395      0.000 [6.243e-03,6.617e-03]
alpha[1]       0.1880  2.954e-03     63.636      0.000     [  0.182,  0.194]
beta[1]        0.7031  4.353e-03    161.532      0.000     [  0.695,  0.712]
============================================================================

Covariance estimator: robust
Aligned returns for /CMI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CMI: first_obs and last_obs produce in an empty array.
Aligned returns for /CMS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CMS: first_obs and last_obs produce in an empty array.
Aligned returns for /CNA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CNA: first_obs and last_obs produce in an empty array.
Aligned returns for /CNC:
Date
2001-01-02    1.037986
2001-01-03    1.039015
2001-01-04    1.039628
2001-01-05    1.039995
2001-01-08    1.041646
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  1.037986  0.0668 -0.0507
2001-01-03  1.039015  0.0668 -0.0507
2001-01-04  1.039628  0.0668 -0.0507
2001-01-05  1.039995  0.0668 -0.0507
2001-01-08  1.041646  0.0668 -0.0507
Results for /CNC:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                499.302
Distribution:                  Normal   AIC:                          -990.604
Method:            Maximum Likelihood   BIC:                          -974.638
                                        No. Observations:                  400
Date:                Mon, Oct 14 2024   Df Residuals:                      399
Time:                        14:49:26   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8551  2.774e-03    308.308      0.000 [  0.850,  0.861]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      2.4727e-04  3.363e-05      7.353  1.937e-13 [1.814e-04,3.132e-04]
alpha[1]       0.1999  1.592e-02     12.562  3.406e-36     [  0.169,  0.231]
beta[1]        0.7797  1.659e-02     47.010      0.000     [  0.747,  0.812]
============================================================================

Covariance estimator: robust
Aligned returns for /CNH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CNH: first_obs and last_obs produce in an empty array.
Aligned returns for /CNM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CNM: first_obs and last_obs produce in an empty array.
Aligned returns for /CNP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CNP: first_obs and last_obs produce in an empty array.
Aligned returns for /CNXC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CNXC: first_obs and last_obs produce in an empty array.
Aligned returns for /COF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COF: first_obs and last_obs produce in an empty array.
Aligned returns for /COHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COHR: first_obs and last_obs produce in an empty array.
Aligned returns for /COIN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COIN: first_obs and last_obs produce in an empty array.
Aligned returns for /COKE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COKE: first_obs and last_obs produce in an empty array.
Aligned returns for /COLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COLB: first_obs and last_obs produce in an empty array.
Aligned returns for /COLD:
Date
2002-05-23    0.818592
2002-06-11    0.819413
2002-06-19    0.821003
2002-06-20    0.819022
2002-06-21    0.817363
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2002-05-23  0.818592 -0.0321  0.0153
2002-06-11  0.819413  0.0429 -0.0005
2002-06-19  0.821003  0.0429 -0.0005
2002-06-20  0.819022  0.0429 -0.0005
2002-06-21  0.817363  0.0429 -0.0005
Results for /COLD:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                9.38902
Distribution:                  Normal   AIC:                          -10.7780
Method:            Maximum Likelihood   BIC:                           10.2472
                                        No. Observations:                 1417
Date:                Mon, Oct 14 2024   Df Residuals:                     1416
Time:                        14:49:26   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8084  7.726e-03    104.632      0.000 [  0.793,  0.824]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.9961e-03  1.380e-04     14.461  2.128e-47 [1.726e-03,2.267e-03]
alpha[1]       0.2000  1.138e-02     17.578  3.655e-69     [  0.178,  0.222]
beta[1]        0.7799  1.267e-02     61.576      0.000     [  0.755,  0.805]
============================================================================

Covariance estimator: robust
Aligned returns for /COLM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COLM: first_obs and last_obs produce in an empty array.
Aligned returns for /COO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COO: first_obs and last_obs produce in an empty array.
Aligned returns for /COP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COP: first_obs and last_obs produce in an empty array.
Aligned returns for /COR:
Date
2002-05-15    0.657059
2002-05-16    0.652135
2002-05-17    0.651943
2002-05-20    0.649878
2002-05-21    0.649464
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2002-05-15  0.657059 -0.0321  0.0153
2002-05-16  0.652135 -0.0321  0.0153
2002-05-17  0.651943 -0.0321  0.0153
2002-05-20  0.649878 -0.0321  0.0153
2002-05-21  0.649464 -0.0321  0.0153

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.0111. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.09977. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.05426. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /COR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1038.75
Distribution:                  Normal   AIC:                          -2069.51
Method:            Maximum Likelihood   BIC:                          -2047.29
                                        No. Observations:                 1909
Date:                Mon, Oct 14 2024   Df Residuals:                     1908
Time:                        14:49:26   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.9985  4.351e-03    229.459      0.000 [  0.990,  1.007]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.0943e-03  5.299e-05     20.652  9.411e-95 [9.905e-04,1.198e-03]
alpha[1]       0.2000  8.131e-03     24.597 1.348e-133     [  0.184,  0.216]
beta[1]        0.7800  7.801e-03     99.986      0.000     [  0.765,  0.795]
============================================================================

Covariance estimator: robust
Aligned returns for /COST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COST: first_obs and last_obs produce in an empty array.
Aligned returns for /COTY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /COTY: first_obs and last_obs produce in an empty array.
Aligned returns for /CPB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CPB: first_obs and last_obs produce in an empty array.
Aligned returns for /CPNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CPNG: first_obs and last_obs produce in an empty array.
Aligned returns for /CPRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CPRI: first_obs and last_obs produce in an empty array.
Aligned returns for /CPRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CPRT: first_obs and last_obs produce in an empty array.
Aligned returns for /CPT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CPT: first_obs and last_obs produce in an empty array.
Aligned returns for /CR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CR: first_obs and last_obs produce in an empty array.
Aligned returns for /CRBG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CRBG: first_obs and last_obs produce in an empty array.
Aligned returns for /CRH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CRH: first_obs and last_obs produce in an empty array.
Aligned returns for /CRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CRI: first_obs and last_obs produce in an empty array.
Aligned returns for /CRL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CRL: first_obs and last_obs produce in an empty array.
Aligned returns for /CRM:
Date
2001-03-29    3.216908
2001-04-02    3.197721
2001-04-03    3.165042
2001-04-04    3.165084
2001-04-10    3.164340
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-03-29  3.216908  0.0025  0.0642
2001-04-02  3.197721  0.0055 -0.0467
2001-04-03  3.165042  0.0055 -0.0467
2001-04-04  3.165084  0.0055 -0.0467
2001-04-10  3.164340  0.0055 -0.0467
Results for /CRM:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                182.572
Distribution:                  Normal   AIC:                          -357.144
Method:            Maximum Likelihood   BIC:                          -342.765
                                        No. Observations:                  269
Date:                Mon, Oct 14 2024   Df Residuals:                      268
Time:                        14:49:27   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.0613  1.538e-03    690.243      0.000 [  1.058,  1.064]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      7.1174e-07  1.190e-04  5.980e-03      0.995 [-2.326e-04,2.340e-04]
alpha[1]       1.0000      7.737      0.129      0.897      [-14.164, 16.164]
beta[1]    4.5192e-07      0.328  1.377e-06      1.000      [ -0.643,  0.643]
=============================================================================

Covariance estimator: robust
Aligned returns for /CROX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CROX: first_obs and last_obs produce in an empty array.
Aligned returns for /CRUS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CRUS: first_obs and last_obs produce in an empty array.
Aligned returns for /CRWD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CRWD: first_obs and last_obs produce in an empty array.
Aligned returns for /CSCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CSCO: first_obs and last_obs produce in an empty array.
Aligned returns for /CSGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CSGP: first_obs and last_obs produce in an empty array.
Aligned returns for /CSL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CSL: first_obs and last_obs produce in an empty array.
Aligned returns for /CSX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CSX: first_obs and last_obs produce in an empty array.
Aligned returns for /CTAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CTAS: first_obs and last_obs produce in an empty array.
Aligned returns for /CTLT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CTLT: first_obs and last_obs produce in an empty array.
Aligned returns for /CTRA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CTRA: first_obs and last_obs produce in an empty array.
Aligned returns for /CTSH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CTSH: first_obs and last_obs produce in an empty array.
Aligned returns for /CTVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CTVA: first_obs and last_obs produce in an empty array.
Aligned returns for /CUBE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CUBE: first_obs and last_obs produce in an empty array.
Aligned returns for /CUZ:
Date
2001-01-02    0.663183
2001-01-03    0.661534
2001-01-04    0.661763
2001-01-05    0.646476
2001-01-08    0.639833
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.663183  0.0668 -0.0507
2001-01-03  0.661534  0.0668 -0.0507
2001-01-04  0.661763  0.0668 -0.0507
2001-01-05  0.646476  0.0668 -0.0507
2001-01-08  0.639833  0.0668 -0.0507

Results for /CUZ:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1069.41
Distribution:                  Normal   AIC:                          -2130.82
Method:            Maximum Likelihood   BIC:                          -2104.91
                                        No. Observations:                 4810
Date:                Mon, Oct 14 2024   Df Residuals:                     4809
Time:                        14:49:27   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5025  3.183e-03    157.854      0.000 [  0.496,  0.509]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      6.4298e-03  9.541e-05     67.395      0.000 [6.243e-03,6.617e-03]
alpha[1]       0.1880  2.954e-03     63.636      0.000     [  0.182,  0.194]
beta[1]        0.7031  4.353e-03    161.532      0.000     [  0.695,  0.712]
============================================================================

Covariance estimator: robust
Aligned returns for /CVNA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CVNA: first_obs and last_obs produce in an empty array.
Aligned returns for /CVS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CVS: first_obs and last_obs produce in an empty array.
Aligned returns for /CVX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CVX: first_obs and last_obs produce in an empty array.
Aligned returns for /CW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CW: first_obs and last_obs produce in an empty array.
Aligned returns for /CWEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CWEN: first_obs and last_obs produce in an empty array.
Aligned returns for /CXT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CXT: first_obs and last_obs produce in an empty array.
Aligned returns for /CZR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /CZR: first_obs and last_obs produce in an empty array.
Aligned returns for /D:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /D: first_obs and last_obs produce in an empty array.
Aligned returns for /DAL:
Date
2001-01-02    0.414253
2001-01-03    0.415131
2001-01-04    0.416040
2001-01-05    0.416029
2001-01-08    0.417062
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.414253  0.0668 -0.0507
2001-01-03  0.415131  0.0668 -0.0507
2001-01-04  0.416040  0.0668 -0.0507
2001-01-05  0.416029  0.0668 -0.0507
2001-01-08  0.417062  0.0668 -0.0507
Results for /DAL:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:           -7.25356e+06
Distribution:                  Normal   AIC:                       1.45071e+07
Method:            Maximum Likelihood   BIC:                       1.45071e+07
                                        No. Observations:                 1201
Date:                Mon, Oct 14 2024   Df Residuals:                     1200
Time:                        14:49:27   Df Model:                            1
                                  Mean Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
mu          1094.8432  2.063e+04  5.308e-02      0.958 [-3.933e+04,4.152e+04]
                            Volatility Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
omega      2.5414e-10      1.803  1.409e-10      1.000 [ -3.534,  3.534]
alpha[1]       1.0000     37.386  2.675e-02      0.979 [-72.274, 74.274]
beta[1]    3.3128e-05      2.248  1.473e-05      1.000 [ -4.407,  4.407]
========================================================================

Covariance estimator: robust
WARNING: The optimizer did not indicate successful convergence. The message was Inequality constraints incompatible.
See convergence_flag.

Aligned returns for /DAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DAR: first_obs and last_obs produce in an empty array.
Aligned returns for /DASH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DASH: first_obs and last_obs produce in an empty array.
Aligned returns for /DAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DAY: first_obs and last_obs produce in an empty array.
Aligned returns for /DBX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02541. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:766: ConvergenceWarning: The optimizer returned code 4. The message is:
Inequality constraints incompatible
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02714. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /DBX: first_obs and last_obs produce in an empty array.
Aligned returns for /DCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DCI: first_obs and last_obs produce in an empty array.
Aligned returns for /DD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DD: first_obs and last_obs produce in an empty array.
Aligned returns for /DDOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DDOG: first_obs and last_obs produce in an empty array.
Aligned returns for /DDS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DDS: first_obs and last_obs produce in an empty array.
Aligned returns for /DE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DE: first_obs and last_obs produce in an empty array.
Aligned returns for /DECK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DECK: first_obs and last_obs produce in an empty array.
Aligned returns for /DELL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DELL: first_obs and last_obs produce in an empty array.
Aligned returns for /DFS:
Date
2001-01-02    0.721143
2001-01-03    0.723189
2001-01-04    0.723171
2001-01-05    0.722458
2001-01-08    0.722450
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.721143  0.0668 -0.0507
2001-01-03  0.723189  0.0668 -0.0507
2001-01-04  0.723171  0.0668 -0.0507
2001-01-05  0.722458  0.0668 -0.0507
2001-01-08  0.722450  0.0668 -0.0507
Results for /DFS:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1576.70
Distribution:                  Normal   AIC:                          -3145.41
Method:            Maximum Likelihood   BIC:                          -3123.31
                                        No. Observations:                 1852
Date:                Mon, Oct 14 2024   Df Residuals:                     1851
Time:                        14:49:27   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4230  7.493e-03     56.449      0.000 [  0.408,  0.438]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.4629e-04  4.789e-05     11.408  3.802e-30 [4.524e-04,6.401e-04]
alpha[1]       0.2000  1.835e-02     10.898  1.177e-27     [  0.164,  0.236]
beta[1]        0.7800  1.665e-02     46.837      0.000     [  0.747,  0.813]
============================================================================

Covariance estimator: robust
Aligned returns for /DG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DG: first_obs and last_obs produce in an empty array.
Aligned returns for /DGX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DGX: first_obs and last_obs produce in an empty array.
Aligned returns for /DHI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DHI: first_obs and last_obs produce in an empty array.
Aligned returns for /DHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DHR: first_obs and last_obs produce in an empty array.
Aligned returns for /DINO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DINO: first_obs and last_obs produce in an empty array.
Aligned returns for /DIS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DIS: first_obs and last_obs produce in an empty array.
Aligned returns for /DJT:
Date
2001-01-02    0.580448
2001-01-03    0.580448
2001-01-04    0.584276
2001-01-05    0.584028
2001-01-08    0.586988
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.580448  0.0668 -0.0507
2001-01-03  0.580448  0.0668 -0.0507
2001-01-04  0.584276  0.0668 -0.0507
2001-01-05  0.584028  0.0668 -0.0507
2001-01-08  0.586988  0.0668 -0.0507
Results for /DJT:

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02516. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02624. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                745.114
Distribution:                  Normal   AIC:                          -1482.23
Method:            Maximum Likelihood   BIC:                          -1463.01
                                        No. Observations:                  903
Date:                Mon, Oct 14 2024   Df Residuals:                      902
Time:                        14:49:27   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5604  7.908e-03     70.866      0.000 [  0.545,  0.576]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.0842e-04  6.838e-05      7.435  1.046e-13 [3.744e-04,6.424e-04]
alpha[1]       0.1998  2.662e-02      7.505  6.151e-14     [  0.148,  0.252]
beta[1]        0.7792  2.461e-02     31.662 5.256e-220     [  0.731,  0.827]
============================================================================

Covariance estimator: robust
Aligned returns for /DKNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DKNG: first_obs and last_obs produce in an empty array.
Aligned returns for /DKS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DKS: first_obs and last_obs produce in an empty array.
Aligned returns for /DLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DLB: first_obs and last_obs produce in an empty array.
Aligned returns for /DLR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DLR: first_obs and last_obs produce in an empty array.
Aligned returns for /DLTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DLTR: first_obs and last_obs produce in an empty array.
Aligned returns for /DNB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DNB: first_obs and last_obs produce in an empty array.
Aligned returns for /DOC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DOC: first_obs and last_obs produce in an empty array.
Aligned returns for /DOCS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DOCS: first_obs and last_obs produce in an empty array.
Aligned returns for /DOCU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DOCU: first_obs and last_obs produce in an empty array.
Aligned returns for /DOV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DOV: first_obs and last_obs produce in an empty array.
Aligned returns for /DOW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DOW: first_obs and last_obs produce in an empty array.
Aligned returns for /DOX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DOX: first_obs and last_obs produce in an empty array.
Aligned returns for /DPZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DPZ: first_obs and last_obs produce in an empty array.
Aligned returns for /DRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DRI: first_obs and last_obs produce in an empty array.
Aligned returns for /DT:
Date
2001-01-02    0.618061
2001-01-03    0.621322
2001-01-04    0.621224
2001-01-05    0.617409
2001-01-08    0.614243
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.618061  0.0668 -0.0507
2001-01-03  0.621322  0.0668 -0.0507
2001-01-04  0.621224  0.0668 -0.0507
2001-01-05  0.617409  0.0668 -0.0507
2001-01-08  0.614243  0.0668 -0.0507
Results for /DT:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                836.557
Distribution:                  Normal   AIC:                          -1665.11
Method:            Maximum Likelihood   BIC:                          -1642.02
                                        No. Observations:                 2379
Date:                Mon, Oct 14 2024   Df Residuals:                     2378
Time:                        14:49:27   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.1312  2.954e-03     44.406      0.000 [  0.125,  0.137]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.4340e-04  5.608e-05      9.690  3.315e-22 [4.335e-04,6.533e-04]
alpha[1]       0.2000  2.043e-02      9.791  1.236e-22     [  0.160,  0.240]
beta[1]        0.7799  2.124e-02     36.716 4.093e-295     [  0.738,  0.822]
============================================================================

Covariance estimator: robust
Aligned returns for /DTE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DTE: first_obs and last_obs produce in an empty array.
Aligned returns for /DTM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DTM: first_obs and last_obs produce in an empty array.
Aligned returns for /DUK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DUK: first_obs and last_obs produce in an empty array.
Aligned returns for /DUOL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DUOL: first_obs and last_obs produce in an empty array.

Aligned returns for /DV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DV: first_obs and last_obs produce in an empty array.
Aligned returns for /DVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DVA: first_obs and last_obs produce in an empty array.
Aligned returns for /DVN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DVN: first_obs and last_obs produce in an empty array.
Aligned returns for /DXC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DXC: first_obs and last_obs produce in an empty array.
Aligned returns for /DXCM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /DXCM: first_obs and last_obs produce in an empty array.
Aligned returns for /EA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EA: first_obs and last_obs produce in an empty array.
Aligned returns for /EBAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EBAY: first_obs and last_obs produce in an empty array.
Aligned returns for /ECL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ECL: first_obs and last_obs produce in an empty array.
Aligned returns for /ED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ED: first_obs and last_obs produce in an empty array.
Aligned returns for /EEFT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EEFT: first_obs and last_obs produce in an empty array.
Aligned returns for /EFX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EFX: first_obs and last_obs produce in an empty array.
Aligned returns for /EG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EG: first_obs and last_obs produce in an empty array.
Aligned returns for /EGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EGP: first_obs and last_obs produce in an empty array.
Aligned returns for /EHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EHC: first_obs and last_obs produce in an empty array.
Aligned returns for /EIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EIX: first_obs and last_obs produce in an empty array.
Aligned returns for /EL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EL: first_obs and last_obs produce in an empty array.
Aligned returns for /ELAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ELAN: first_obs and last_obs produce in an empty array.
Aligned returns for /ELF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ELF: first_obs and last_obs produce in an empty array.
Aligned returns for /ELS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ELS: first_obs and last_obs produce in an empty array.
Aligned returns for /ELV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ELV: first_obs and last_obs produce in an empty array.
Aligned returns for /EME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EME: first_obs and last_obs produce in an empty array.
Aligned returns for /EMN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EMN: first_obs and last_obs produce in an empty array.
Aligned returns for /EMR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EMR: first_obs and last_obs produce in an empty array.
Aligned returns for /ENOV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ENOV: first_obs and last_obs produce in an empty array.
Aligned returns for /ENPH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ENPH: first_obs and last_obs produce in an empty array.
Aligned returns for /ENTG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ENTG: first_obs and last_obs produce in an empty array.
Aligned returns for /EOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EOG: first_obs and last_obs produce in an empty array.
Aligned returns for /EPAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EPAM: first_obs and last_obs produce in an empty array.
Aligned returns for /EPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EPR: first_obs and last_obs produce in an empty array.
Aligned returns for /EQH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EQH: first_obs and last_obs produce in an empty array.
Aligned returns for /EQIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EQIX: first_obs and last_obs produce in an empty array.
Aligned returns for /EQR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EQR: first_obs and last_obs produce in an empty array.
Aligned returns for /EQT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EQT: first_obs and last_obs produce in an empty array.
Aligned returns for /ES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ES: first_obs and last_obs produce in an empty array.
Aligned returns for /ESAB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ESAB: first_obs and last_obs produce in an empty array.
Aligned returns for /ESI:
Date
2001-01-02    0.757415
2001-01-03    0.755275
2001-01-04    0.749060
2001-01-05    0.749451
2001-01-08    0.749703
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.757415  0.0668 -0.0507
2001-01-03  0.755275  0.0668 -0.0507
2001-01-04  0.749060  0.0668 -0.0507
2001-01-05  0.749451  0.0668 -0.0507
2001-01-08  0.749703  0.0668 -0.0507

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.09251. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /ESI:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1787.08
Distribution:                  Normal   AIC:                          -3566.17
Method:            Maximum Likelihood   BIC:                          -3541.05
                                        No. Observations:                 3943
Date:                Mon, Oct 14 2024   Df Residuals:                     3942
Time:                        14:49:28   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5441  3.149e-03    172.772      0.000 [  0.538,  0.550]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.8717e-03  4.182e-05     44.761      0.000 [1.790e-03,1.954e-03]
alpha[1]       0.2000  5.413e-03     36.944 8.967e-299     [  0.189,  0.211]
beta[1]        0.7799  4.742e-03    164.464      0.000     [  0.771,  0.789]
============================================================================

Covariance estimator: robust
Aligned returns for /ESS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ESS: first_obs and last_obs produce in an empty array.
Aligned returns for /ESTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ESTC: first_obs and last_obs produce in an empty array.
Aligned returns for /ETN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ETN: first_obs and last_obs produce in an empty array.
Aligned returns for /ETR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ETR: first_obs and last_obs produce in an empty array.
Aligned returns for /ETSY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ETSY: first_obs and last_obs produce in an empty array.
Aligned returns for /EVR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EVR: first_obs and last_obs produce in an empty array.
Aligned returns for /EVRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EVRG: first_obs and last_obs produce in an empty array.
Aligned returns for /EW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EW: first_obs and last_obs produce in an empty array.
Aligned returns for /EWBC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EWBC: first_obs and last_obs produce in an empty array.
Aligned returns for /EXAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EXAS: first_obs and last_obs produce in an empty array.
Aligned returns for /EXC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EXC: first_obs and last_obs produce in an empty array.
Aligned returns for /EXEL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EXEL: first_obs and last_obs produce in an empty array.
Aligned returns for /EXP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EXP: first_obs and last_obs produce in an empty array.
Aligned returns for /EXPD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EXPD: first_obs and last_obs produce in an empty array.
Aligned returns for /EXPE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EXPE: first_obs and last_obs produce in an empty array.
Aligned returns for /EXR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /EXR: first_obs and last_obs produce in an empty array.
Aligned returns for /F:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /F: first_obs and last_obs produce in an empty array.
Aligned returns for /FAF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FAF: first_obs and last_obs produce in an empty array.
Aligned returns for /FANG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FANG: first_obs and last_obs produce in an empty array.
Aligned returns for /FAST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FAST: first_obs and last_obs produce in an empty array.
Aligned returns for /FBIN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FBIN: first_obs and last_obs produce in an empty array.
Aligned returns for /FCN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FCN: first_obs and last_obs produce in an empty array.
Aligned returns for /FCNCA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FCNCA: first_obs and last_obs produce in an empty array.
Aligned returns for /FCX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FCX: first_obs and last_obs produce in an empty array.
Aligned returns for /FDS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FDS: first_obs and last_obs produce in an empty array.
Aligned returns for /FDX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FDX: first_obs and last_obs produce in an empty array.
Aligned returns for /FE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FE: first_obs and last_obs produce in an empty array.
Aligned returns for /FERG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FERG: first_obs and last_obs produce in an empty array.
Aligned returns for /FFIV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FFIV: first_obs and last_obs produce in an empty array.
Aligned returns for /FHB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FHB: first_obs and last_obs produce in an empty array.
Aligned returns for /FHN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FHN: first_obs and last_obs produce in an empty array.
Aligned returns for /FI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FI: first_obs and last_obs produce in an empty array.
Aligned returns for /FICO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

Error fitting GARCH model for /FICO: first_obs and last_obs produce in an empty array.
Aligned returns for /FIS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FIS: first_obs and last_obs produce in an empty array.
Aligned returns for /FITB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FITB: first_obs and last_obs produce in an empty array.
Aligned returns for /FIVE:
Date
2001-01-05    1.970135
2001-01-08    1.969728
2001-01-10    1.968699
2001-01-11    1.971409
2001-01-12    1.973113
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-05  1.970135  0.0668 -0.0507
2001-01-08  1.969728  0.0668 -0.0507
2001-01-10  1.968699  0.0668 -0.0507
2001-01-11  1.971409  0.0668 -0.0507
2001-01-12  1.973113  0.0668 -0.0507
Results for /FIVE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                218.521
Distribution:                  Normal   AIC:                          -429.042
Method:            Maximum Likelihood   BIC:                          -414.663
                                        No. Observations:                  269
Date:                Mon, Oct 14 2024   Df Residuals:                      268
Time:                        14:49:28   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.9805  2.733e-02     72.460      0.000 [  1.927,  2.034]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.1607e-04  1.403e-04      0.827      0.408 [-1.589e-04,3.911e-04]
alpha[1]       1.0000      1.655      0.604      0.546      [ -2.243,  4.243]
beta[1]    9.5923e-14      1.406  6.822e-14      1.000      [ -2.756,  2.756]
=============================================================================

Covariance estimator: robust
Aligned returns for /FIVN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FIVN: first_obs and last_obs produce in an empty array.
Aligned returns for /FIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FIX: first_obs and last_obs produce in an empty array.
Aligned returns for /FLO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FLO: first_obs and last_obs produce in an empty array.
Aligned returns for /FLS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FLS: first_obs and last_obs produce in an empty array.
Aligned returns for /FMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FMC: first_obs and last_obs produce in an empty array.
Aligned returns for /FNB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FNB: first_obs and last_obs produce in an empty array.
Aligned returns for /FND:
Date
2001-01-02    0.526591
2001-01-03    0.533472
2001-01-04    0.533688
2001-01-05    0.537226
2001-01-08    0.538416
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.526591  0.0668 -0.0507
2001-01-03  0.533472  0.0668 -0.0507
2001-01-04  0.533688  0.0668 -0.0507
2001-01-05  0.537226  0.0668 -0.0507
2001-01-08  0.538416  0.0668 -0.0507
Results for /FND:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1353.76
Distribution:                  Normal   AIC:                          -2699.53
Method:            Maximum Likelihood   BIC:                          -2677.80
                                        No. Observations:                 1688
Date:                Mon, Oct 14 2024   Df Residuals:                     1687
Time:                        14:49:28   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2688  2.205e-03    121.889      0.000 [  0.264,  0.273]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.4453e-04  2.708e-05     20.106  6.605e-90 [4.914e-04,5.976e-04]
alpha[1]       0.2000  1.106e-02     18.076  4.930e-73     [  0.178,  0.222]
beta[1]        0.7799  1.065e-02     73.250      0.000     [  0.759,  0.801]
============================================================================

Covariance estimator: robust

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.03466. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02645. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.005352. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Aligned returns for /FNF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FNF: first_obs and last_obs produce in an empty array.
Aligned returns for /FOUR:
Date
2001-05-31    1.986261
2001-06-01    1.985756
2001-06-04    1.983652
2001-06-05    1.981433
2001-06-06    1.981447
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-05-31  1.986261  0.0250  0.0336
2001-06-01  1.985756  0.0624 -0.0112
2001-06-04  1.983652  0.0624 -0.0112
2001-06-05  1.981433  0.0624 -0.0112
2001-06-06  1.981447  0.0624 -0.0112
Results for /FOUR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                206.752
Distribution:                  Normal   AIC:                          -405.504
Method:            Maximum Likelihood   BIC:                          -393.569
                                        No. Observations:                  146
Date:                Mon, Oct 14 2024   Df Residuals:                      145
Time:                        14:49:28   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.9049      0.120     15.918  4.777e-57 [  1.670,  2.139]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.0773e-04  2.599e-03  4.145e-02      0.967 [-4.987e-03,5.202e-03]
alpha[1]       0.2000      0.196      1.020      0.308      [ -0.184,  0.584]
beta[1]        0.7799      0.509      1.532      0.126      [ -0.218,  1.778]
=============================================================================

Covariance estimator: robust
Aligned returns for /FOX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FOX: first_obs and last_obs produce in an empty array.
Aligned returns for /FOXA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FOXA: first_obs and last_obs produce in an empty array.
Aligned returns for /FR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FR: first_obs and last_obs produce in an empty array.
Aligned returns for /FRPT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FRPT: first_obs and last_obs produce in an empty array.
Aligned returns for /FRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FRT: first_obs and last_obs produce in an empty array.
Aligned returns for /FSLR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FSLR: first_obs and last_obs produce in an empty array.
Aligned returns for /FTI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FTI: first_obs and last_obs produce in an empty array.
Aligned returns for /FTNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FTNT: first_obs and last_obs produce in an empty array.
Aligned returns for /FTRE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FTRE: first_obs and last_obs produce in an empty array.
Aligned returns for /FTV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FTV: first_obs and last_obs produce in an empty array.
Aligned returns for /FWONA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FWONA: first_obs and last_obs produce in an empty array.
Aligned returns for /FWONK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FWONK: first_obs and last_obs produce in an empty array.
Aligned returns for /FYBR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /FYBR: first_obs and last_obs produce in an empty array.
Aligned returns for /G:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /G: first_obs and last_obs produce in an empty array.
Aligned returns for /GAP:
Date
2001-01-02    0.467432
2001-01-03    0.468457
2001-01-04    0.469481
2001-01-05    0.473078
2001-01-08    0.473995
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.467432  0.0668 -0.0507
2001-01-03  0.468457  0.0668 -0.0507
2001-01-04  0.469481  0.0668 -0.0507
2001-01-05  0.473078  0.0668 -0.0507
2001-01-08  0.473995  0.0668 -0.0507
Results for /GAP:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1347.41
Distribution:                  Normal   AIC:                          -2686.83
Method:            Maximum Likelihood   BIC:                          -2663.53
                                        No. Observations:                 2501
Date:                Mon, Oct 14 2024   Df Residuals:                     2500
Time:                        14:49:28   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5487  3.658e-03    150.002      0.000 [  0.541,  0.556]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.2025e-03  3.992e-05     30.121 2.545e-199 [1.124e-03,1.281e-03]
alpha[1]       0.2000  7.421e-03     26.951 5.500e-160     [  0.185,  0.215]
beta[1]        0.7800  6.991e-03    111.563      0.000     [  0.766,  0.794]
============================================================================

Covariance estimator: robust
Aligned returns for /GD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.05985. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /GD: first_obs and last_obs produce in an empty array.
Aligned returns for /GDDY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GDDY: first_obs and last_obs produce in an empty array.
Aligned returns for /GE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GE: first_obs and last_obs produce in an empty array.
Aligned returns for /GEHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GEHC: first_obs and last_obs produce in an empty array.
Aligned returns for /GEN:
Date
2008-05-14    0.358018
2008-05-15    0.358109
2008-05-16    0.358424
2008-05-19    0.359357
2008-05-20    0.359565
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2008-05-14  0.358018  0.0296 -0.0143
2008-05-15  0.358109  0.0296 -0.0143
2008-05-16  0.358424  0.0296 -0.0143
2008-05-19  0.359357  0.0296 -0.0143
2008-05-20  0.359565  0.0296 -0.0143
Results for /GEN:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1209.25
Distribution:                  Normal   AIC:                          -2410.49
Method:            Maximum Likelihood   BIC:                          -2386.16
                                        No. Observations:                 3239
Date:                Mon, Oct 14 2024   Df Residuals:                     3238
Time:                        14:49:29   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5438  6.338e-03     85.795      0.000 [  0.531,  0.556]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      2.0933e-03  1.316e-04     15.911  5.295e-57 [1.835e-03,2.351e-03]
alpha[1]       0.1978  1.184e-02     16.703  1.243e-62     [  0.175,  0.221]
beta[1]        0.7715  1.252e-02     61.597      0.000     [  0.747,  0.796]
============================================================================

Covariance estimator: robust
Aligned returns for /GEV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GEV: first_obs and last_obs produce in an empty array.
Aligned returns for /GFS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GFS: first_obs and last_obs produce in an empty array.
Aligned returns for /GGG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GGG: first_obs and last_obs produce in an empty array.
Aligned returns for /GILD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GILD: first_obs and last_obs produce in an empty array.
Aligned returns for /GIS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GIS: first_obs and last_obs produce in an empty array.
Aligned returns for /GL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GL: first_obs and last_obs produce in an empty array.
Aligned returns for /GLOB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GLOB: first_obs and last_obs produce in an empty array.
Aligned returns for /GLPI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GLPI: first_obs and last_obs produce in an empty array.
Aligned returns for /GLW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GLW: first_obs and last_obs produce in an empty array.
Aligned returns for /GM:
Date
2001-01-02    0.421981
2001-01-03    0.423108
2001-01-04    0.425225
2001-01-05    0.428813
2001-01-08    0.427143
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.421981  0.0668 -0.0507
2001-01-03  0.423108  0.0668 -0.0507
2001-01-04  0.425225  0.0668 -0.0507
2001-01-05  0.428813  0.0668 -0.0507
2001-01-08  0.427143  0.0668 -0.0507
Results for /GM:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                2151.90
Distribution:                  Normal   AIC:                          -4295.79
Method:            Maximum Likelihood   BIC:                          -4273.17
                                        No. Observations:                 2114
Date:                Mon, Oct 14 2024   Df Residuals:                     2113
Time:                        14:49:29   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3900  1.956e-03    199.366      0.000 [  0.386,  0.394]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.1556e-03  2.008e-05     57.550      0.000 [1.116e-03,1.195e-03]
alpha[1]       0.2000  5.774e-03     34.638 6.848e-263     [  0.189,  0.211]
beta[1]        0.7800  4.080e-03    191.194      0.000     [  0.772,  0.788]
============================================================================

Covariance estimator: robust
Aligned returns for /GME:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.05778. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01461. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /GME: first_obs and last_obs produce in an empty array.
Aligned returns for /GMED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GMED: first_obs and last_obs produce in an empty array.
Aligned returns for /GNRC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GNRC: first_obs and last_obs produce in an empty array.
Aligned returns for /GNTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GNTX: first_obs and last_obs produce in an empty array.
Aligned returns for /GO:
Date
2001-01-18    0.943778
2001-01-19    0.943902
2001-01-22    0.945139
2001-01-23    0.945800
2001-01-24    0.943162
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-18  0.943778  0.0668 -0.0507
2001-01-19  0.943902  0.0668 -0.0507
2001-01-22  0.945139  0.0668 -0.0507
2001-01-23  0.945800  0.0668 -0.0507
2001-01-24  0.943162  0.0668 -0.0507
Results for /GO:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                879.334
Distribution:                  Normal   AIC:                          -1750.67
Method:            Maximum Likelihood   BIC:                          -1731.09
                                        No. Observations:                  986
Date:                Mon, Oct 14 2024   Df Residuals:                      985
Time:                        14:49:29   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7486  1.184e-02     63.248      0.000 [  0.725,  0.772]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      2.9217e-04  4.615e-05      6.331  2.437e-10 [2.017e-04,3.826e-04]
alpha[1]       0.2000  1.501e-02     13.321  1.757e-40     [  0.171,  0.229]
beta[1]        0.7800  1.762e-02     44.273      0.000     [  0.745,  0.815]
============================================================================

Covariance estimator: robust
Aligned returns for /GOOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GOOG: first_obs and last_obs produce in an empty array.
Aligned returns for /GOOGL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GOOGL: first_obs and last_obs produce in an empty array.
Aligned returns for /GPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GPC: first_obs and last_obs produce in an empty array.
Aligned returns for /GPK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GPK: first_obs and last_obs produce in an empty array.
Aligned returns for /GPN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GPN: first_obs and last_obs produce in an empty array.
Aligned returns for /GRMN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GRMN: first_obs and last_obs produce in an empty array.
Aligned returns for /GS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GS: first_obs and last_obs produce in an empty array.
Aligned returns for /GTES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GTES: first_obs and last_obs produce in an empty array.
Aligned returns for /GTLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GTLB: first_obs and last_obs produce in an empty array.
Aligned returns for /GWRE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GWRE: first_obs and last_obs produce in an empty array.
Aligned returns for /GWW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GWW: first_obs and last_obs produce in an empty array.
Aligned returns for /GXO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /GXO: first_obs and last_obs produce in an empty array.
Aligned returns for /H:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /H: first_obs and last_obs produce in an empty array.
Aligned returns for /HAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HAL: first_obs and last_obs produce in an empty array.
Aligned returns for /HAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HAS: first_obs and last_obs produce in an empty array.
Aligned returns for /HAYW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HAYW: first_obs and last_obs produce in an empty array.
Aligned returns for /HBAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HBAN: first_obs and last_obs produce in an empty array.
Aligned returns for /HCA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HCA: first_obs and last_obs produce in an empty array.
Aligned returns for /HCP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HCP: first_obs and last_obs produce in an empty array.
Aligned returns for /HD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HD: first_obs and last_obs produce in an empty array.
Aligned returns for /HEI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HEI: first_obs and last_obs produce in an empty array.
Aligned returns for /HES:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HES: first_obs and last_obs produce in an empty array.
Aligned returns for /HHH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HHH: first_obs and last_obs produce in an empty array.
Aligned returns for /HIG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HIG: first_obs and last_obs produce in an empty array.
Aligned returns for /HII:
Date
2001-01-08    3.305769
2001-01-09    3.306953
2001-01-10    3.306953
2001-01-11    2.968138
2001-01-12    2.543762
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-08  3.305769  0.0668 -0.0507
2001-01-09  3.306953  0.0668 -0.0507
2001-01-10  3.306953  0.0668 -0.0507
2001-01-11  2.968138  0.0668 -0.0507
2001-01-12  2.543762  0.0668 -0.0507

Results for /HII:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                380.928
Distribution:                  Normal   AIC:                          -753.857
Method:            Maximum Likelihood   BIC:                          -739.868
                                        No. Observations:                  244
Date:                Mon, Oct 14 2024   Df Residuals:                      243
Time:                        14:49:29   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.3998  2.096e-05  6.677e+04      0.000 [  1.400,  1.400]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.2160e-06  5.267e-08     61.057      0.000  [3.113e-06,3.319e-06]
alpha[1]       1.0000  4.889e-02     20.453  5.645e-93      [  0.904,  1.096]
beta[1]        0.0000  1.412e-03      0.000      1.000 [-2.768e-03,2.768e-03]
=============================================================================

Covariance estimator: robust
Aligned returns for /HIW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HIW: first_obs and last_obs produce in an empty array.
Aligned returns for /HLI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HLI: first_obs and last_obs produce in an empty array.
Aligned returns for /HLT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HLT: first_obs and last_obs produce in an empty array.
Aligned returns for /HOG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HOG: first_obs and last_obs produce in an empty array.
Aligned returns for /HOLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HOLX: first_obs and last_obs produce in an empty array.
Aligned returns for /HON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HON: first_obs and last_obs produce in an empty array.
Aligned returns for /HOOD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HOOD: first_obs and last_obs produce in an empty array.
Aligned returns for /HPE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HPE: first_obs and last_obs produce in an empty array.
Aligned returns for /HPQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HPQ: first_obs and last_obs produce in an empty array.
Aligned returns for /HR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HR: first_obs and last_obs produce in an empty array.
Aligned returns for /HRB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HRB: first_obs and last_obs produce in an empty array.
Aligned returns for /HRL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HRL: first_obs and last_obs produce in an empty array.
Aligned returns for /HSIC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HSIC: first_obs and last_obs produce in an empty array.
Aligned returns for /HST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HST: first_obs and last_obs produce in an empty array.
Aligned returns for /HSY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HSY: first_obs and last_obs produce in an empty array.
Aligned returns for /HUBB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HUBB: first_obs and last_obs produce in an empty array.
Aligned returns for /HUBS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HUBS: first_obs and last_obs produce in an empty array.
Aligned returns for /HUM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HUM: first_obs and last_obs produce in an empty array.
Aligned returns for /HUN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HUN: first_obs and last_obs produce in an empty array.
Aligned returns for /HWM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HWM: first_obs and last_obs produce in an empty array.
Aligned returns for /HXL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /HXL: first_obs and last_obs produce in an empty array.
Aligned returns for /IAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IAC: first_obs and last_obs produce in an empty array.
Aligned returns for /IBKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IBKR: first_obs and last_obs produce in an empty array.
Aligned returns for /IBM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IBM: first_obs and last_obs produce in an empty array.
Aligned returns for /ICE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ICE: first_obs and last_obs produce in an empty array.
Aligned returns for /IDA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IDA: first_obs and last_obs produce in an empty array.
Aligned returns for /IDXX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IDXX: first_obs and last_obs produce in an empty array.
Aligned returns for /IEX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IEX: first_obs and last_obs produce in an empty array.
Aligned returns for /IFF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IFF: first_obs and last_obs produce in an empty array.
Aligned returns for /ILMN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ILMN: first_obs and last_obs produce in an empty array.
Aligned returns for /INCY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /INCY: first_obs and last_obs produce in an empty array.
Aligned returns for /INFA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /INFA: first_obs and last_obs produce in an empty array.
Aligned returns for /INGR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /INGR: first_obs and last_obs produce in an empty array.
Aligned returns for /INSP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /INSP: first_obs and last_obs produce in an empty array.
Aligned returns for /INTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /INTC: first_obs and last_obs produce in an empty array.
Aligned returns for /INTU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /INTU: first_obs and last_obs produce in an empty array.
Aligned returns for /INVH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /INVH: first_obs and last_obs produce in an empty array.
Aligned returns for /IONS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IONS: first_obs and last_obs produce in an empty array.
Aligned returns for /IP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IP: first_obs and last_obs produce in an empty array.

Aligned returns for /IPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IPG: first_obs and last_obs produce in an empty array.
Aligned returns for /IPGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IPGP: first_obs and last_obs produce in an empty array.
Aligned returns for /IQV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IQV: first_obs and last_obs produce in an empty array.
Aligned returns for /IR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IR: first_obs and last_obs produce in an empty array.
Aligned returns for /IRDM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IRDM: first_obs and last_obs produce in an empty array.
Aligned returns for /IRM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IRM: first_obs and last_obs produce in an empty array.
Aligned returns for /ISRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ISRG: first_obs and last_obs produce in an empty array.
Aligned returns for /IT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IT: first_obs and last_obs produce in an empty array.
Aligned returns for /ITCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ITCI: first_obs and last_obs produce in an empty array.
Aligned returns for /ITT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ITT: first_obs and last_obs produce in an empty array.
Aligned returns for /ITW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ITW: first_obs and last_obs produce in an empty array.
Aligned returns for /IVZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /IVZ: first_obs and last_obs produce in an empty array.
Aligned returns for /J:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /J: first_obs and last_obs produce in an empty array.
Aligned returns for /JAZZ:
Date
2001-01-02    1.308020
2001-01-03    1.314206
2001-01-04    1.319045
2001-01-05    1.309581
2001-01-08    1.311337
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  1.308020  0.0668 -0.0507
2001-01-03  1.314206  0.0668 -0.0507
2001-01-04  1.319045  0.0668 -0.0507
2001-01-05  1.309581  0.0668 -0.0507
2001-01-08  1.311337  0.0668 -0.0507
Results for /JAZZ:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                280.263
Distribution:                  Normal   AIC:                          -552.526
Method:            Maximum Likelihood   BIC:                          -537.071
                                        No. Observations:                  352
Date:                Mon, Oct 14 2024   Df Residuals:                      351
Time:                        14:49:29   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.1373  4.535e-03    250.796      0.000 [  1.128,  1.146]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      4.5654e-04  6.004e-05      7.604  2.881e-14 [3.389e-04,5.742e-04]
alpha[1]       0.1970  1.530e-02     12.876  6.143e-38     [  0.167,  0.227]
beta[1]        0.7679  2.034e-02     37.760      0.000     [  0.728,  0.808]
============================================================================

Covariance estimator: robust
Aligned returns for /JBHT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JBHT: first_obs and last_obs produce in an empty array.
Aligned returns for /JBL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JBL: first_obs and last_obs produce in an empty array.
Aligned returns for /JCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JCI: first_obs and last_obs produce in an empty array.
Aligned returns for /JEF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JEF: first_obs and last_obs produce in an empty array.
Aligned returns for /JHG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JHG: first_obs and last_obs produce in an empty array.
Aligned returns for /JKHY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JKHY: first_obs and last_obs produce in an empty array.
Aligned returns for /JLL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JLL: first_obs and last_obs produce in an empty array.
Aligned returns for /JNJ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JNJ: first_obs and last_obs produce in an empty array.
Aligned returns for /JNPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JNPR: first_obs and last_obs produce in an empty array.
Aligned returns for /JPM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JPM: first_obs and last_obs produce in an empty array.
Aligned returns for /JWN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /JWN: first_obs and last_obs produce in an empty array.
Aligned returns for /K:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /K: first_obs and last_obs produce in an empty array.
Aligned returns for /KBR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KBR: first_obs and last_obs produce in an empty array.
Aligned returns for /KD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KD: first_obs and last_obs produce in an empty array.

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.02309. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Aligned returns for /KDP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KDP: first_obs and last_obs produce in an empty array.
Aligned returns for /KEX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KEX: first_obs and last_obs produce in an empty array.
Aligned returns for /KEY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KEY: first_obs and last_obs produce in an empty array.
Aligned returns for /KEYS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KEYS: first_obs and last_obs produce in an empty array.
Aligned returns for /KHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KHC: first_obs and last_obs produce in an empty array.
Aligned returns for /KIM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KIM: first_obs and last_obs produce in an empty array.
Aligned returns for /KKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KKR: first_obs and last_obs produce in an empty array.
Aligned returns for /KLAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KLAC: first_obs and last_obs produce in an empty array.
Aligned returns for /KMB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KMB: first_obs and last_obs produce in an empty array.
Aligned returns for /KMI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KMI: first_obs and last_obs produce in an empty array.
Aligned returns for /KMPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KMPR: first_obs and last_obs produce in an empty array.
Aligned returns for /KMX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KMX: first_obs and last_obs produce in an empty array.
Aligned returns for /KNSL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KNSL: first_obs and last_obs produce in an empty array.
Aligned returns for /KNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KNX: first_obs and last_obs produce in an empty array.
Aligned returns for /KO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KO: first_obs and last_obs produce in an empty array.
Aligned returns for /KR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KR: first_obs and last_obs produce in an empty array.
Aligned returns for /KRC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KRC: first_obs and last_obs produce in an empty array.
Aligned returns for /KSS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KSS: first_obs and last_obs produce in an empty array.
Aligned returns for /KVUE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /KVUE: first_obs and last_obs produce in an empty array.
Aligned returns for /L:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /L: first_obs and last_obs produce in an empty array.
Aligned returns for /LAD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LAD: first_obs and last_obs produce in an empty array.
Aligned returns for /LAMR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LAMR: first_obs and last_obs produce in an empty array.
Aligned returns for /LAZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LAZ: first_obs and last_obs produce in an empty array.
Aligned returns for /LBRDA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LBRDA: first_obs and last_obs produce in an empty array.
Aligned returns for /LBRDK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LBRDK: first_obs and last_obs produce in an empty array.
Aligned returns for /LBTYA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LBTYA: first_obs and last_obs produce in an empty array.
Aligned returns for /LBTYK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LBTYK: first_obs and last_obs produce in an empty array.
Aligned returns for /LCID:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LCID: first_obs and last_obs produce in an empty array.
Aligned returns for /LDOS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LDOS: first_obs and last_obs produce in an empty array.
Aligned returns for /LEA:
Date
2001-01-02    0.511418
2001-01-03    0.514942
2001-01-04    0.527134
2001-01-05    0.525835
2001-01-08    0.522956
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.511418  0.0668 -0.0507
2001-01-03  0.514942  0.0668 -0.0507
2001-01-04  0.527134  0.0668 -0.0507
2001-01-05  0.525835  0.0668 -0.0507
2001-01-08  0.522956  0.0668 -0.0507
Results for /LEA:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1526.37
Distribution:                  Normal   AIC:                          -3044.74
Method:            Maximum Likelihood   BIC:                          -3022.07
                                        No. Observations:                 2136
Date:                Mon, Oct 14 2024   Df Residuals:                     2135
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4223  2.337e-03    180.730      0.000 [  0.418,  0.427]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      2.1231e-03  4.361e-05     48.682      0.000 [2.038e-03,2.209e-03]
alpha[1]       0.2000  7.622e-03     26.241 9.118e-152     [  0.185,  0.215]
beta[1]        0.7800  4.924e-03    158.401      0.000     [  0.770,  0.790]
============================================================================

Covariance estimator: robust
Aligned returns for /LECO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

Error fitting GARCH model for /LECO: first_obs and last_obs produce in an empty array.
Aligned returns for /LEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LEG: first_obs and last_obs produce in an empty array.
Aligned returns for /LEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LEN: first_obs and last_obs produce in an empty array.
Aligned returns for /LFUS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LFUS: first_obs and last_obs produce in an empty array.
Aligned returns for /LH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LH: first_obs and last_obs produce in an empty array.
Aligned returns for /LHX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LHX: first_obs and last_obs produce in an empty array.
Aligned returns for /LII:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LII: first_obs and last_obs produce in an empty array.
Aligned returns for /LIN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LIN: first_obs and last_obs produce in an empty array.
Aligned returns for /LINE:
Date
2007-01-17    0.238730
2007-01-18    0.238306
2007-01-19    0.239454
2007-01-22    0.240445
2007-01-23    0.239700
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2007-01-17  0.238730  0.0012 -0.0068
2007-01-18  0.238306  0.0012 -0.0068
2007-01-19  0.239454  0.0012 -0.0068
2007-01-22  0.240445  0.0012 -0.0068
2007-01-23  0.239700  0.0012 -0.0068
Results for /LINE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1535.59
Distribution:                  Normal   AIC:                          -3063.18
Method:            Maximum Likelihood   BIC:                          -3040.13
                                        No. Observations:                 2355
Date:                Mon, Oct 14 2024   Df Residuals:                     2354
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2837  1.852e-03    153.167      0.000 [  0.280,  0.287]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      2.2990e-03  5.002e-05     45.964      0.000 [2.201e-03,2.397e-03]
alpha[1]       0.2000  6.883e-03     29.051 1.505e-185     [  0.186,  0.213]
beta[1]        0.7798  4.909e-03    158.859      0.000     [  0.770,  0.789]
============================================================================

Covariance estimator: robust
Aligned returns for /LITE:
Date
2001-01-17    1.714681
2001-01-18    1.724492
2001-01-19    1.726667
2001-01-22    1.750391
2001-01-23    1.750072
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-17  1.714681  0.0668 -0.0507
2001-01-18  1.724492  0.0668 -0.0507
2001-01-19  1.726667  0.0668 -0.0507
2001-01-22  1.750391  0.0668 -0.0507
2001-01-23  1.750072  0.0668 -0.0507
Results for /LITE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                406.003
Distribution:                  Normal   AIC:                          -804.006
Method:            Maximum Likelihood   BIC:                          -787.311
                                        No. Observations:                  480
Date:                Mon, Oct 14 2024   Df Residuals:                      479
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.6204  7.508e-03    215.815      0.000 [  1.606,  1.635]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.9192e-04  6.896e-05      5.683  1.324e-08 [2.568e-04,5.271e-04]
alpha[1]       0.1998  2.085e-02      9.579  9.842e-22     [  0.159,  0.241]
beta[1]        0.7790  2.324e-02     33.526 2.016e-246     [  0.733,  0.825]
============================================================================

Covariance estimator: robust
Aligned returns for /LKQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LKQ: first_obs and last_obs produce in an empty array.
Aligned returns for /LLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LLY: first_obs and last_obs produce in an empty array.
Aligned returns for /LLYVA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LLYVA: first_obs and last_obs produce in an empty array.
Aligned returns for /LLYVK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LLYVK: first_obs and last_obs produce in an empty array.
Aligned returns for /LMT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LMT: first_obs and last_obs produce in an empty array.
Aligned returns for /LNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LNC: first_obs and last_obs produce in an empty array.
Aligned returns for /LNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LNG: first_obs and last_obs produce in an empty array.
Aligned returns for /LNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01947. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /LNT: first_obs and last_obs produce in an empty array.
Aligned returns for /LNW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LNW: first_obs and last_obs produce in an empty array.
Aligned returns for /LOPE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LOPE: first_obs and last_obs produce in an empty array.
Aligned returns for /LOW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LOW: first_obs and last_obs produce in an empty array.
Aligned returns for /LPLA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LPLA: first_obs and last_obs produce in an empty array.
Aligned returns for /LPX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LPX: first_obs and last_obs produce in an empty array.
Aligned returns for /LRCX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LRCX: first_obs and last_obs produce in an empty array.
Aligned returns for /LSCC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LSCC: first_obs and last_obs produce in an empty array.
Aligned returns for /LSTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LSTR: first_obs and last_obs produce in an empty array.
Aligned returns for /LULU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LULU: first_obs and last_obs produce in an empty array.
Aligned returns for /LUV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LUV: first_obs and last_obs produce in an empty array.
Aligned returns for /LVS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LVS: first_obs and last_obs produce in an empty array.
Aligned returns for /LW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LW: first_obs and last_obs produce in an empty array.
Aligned returns for /LYB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LYB: first_obs and last_obs produce in an empty array.
Aligned returns for /LYFT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LYFT: first_obs and last_obs produce in an empty array.
Aligned returns for /LYV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /LYV: first_obs and last_obs produce in an empty array.
Aligned returns for /M:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /M: first_obs and last_obs produce in an empty array.
Aligned returns for /MA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MA: first_obs and last_obs produce in an empty array.
Aligned returns for /MAA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MAA: first_obs and last_obs produce in an empty array.
Aligned returns for /MAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MAN: first_obs and last_obs produce in an empty array.
Aligned returns for /MANH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MANH: first_obs and last_obs produce in an empty array.
Aligned returns for /MAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MAR: first_obs and last_obs produce in an empty array.
Aligned returns for /MAS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MAS: first_obs and last_obs produce in an empty array.
Aligned returns for /MASI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MASI: first_obs and last_obs produce in an empty array.
Aligned returns for /MAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MAT: first_obs and last_obs produce in an empty array.
Aligned returns for /MCD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MCD: first_obs and last_obs produce in an empty array.
Aligned returns for /MCHP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MCHP: first_obs and last_obs produce in an empty array.
Aligned returns for /MCK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MCK: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /MCO. Resolving...
Aligned returns for /MCO:
Date
2001-01-02    0.448949
2001-01-03    0.448925
2001-01-04    0.446834
2001-01-05    0.445958
2001-01-08    0.448749
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.448949  0.0668 -0.0507
2001-01-03  0.448925  0.0668 -0.0507
2001-01-04  0.446834  0.0668 -0.0507
2001-01-05  0.445958  0.0668 -0.0507
2001-01-08  0.448749  0.0668 -0.0507
Results for /MCO:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                575.347
Distribution:                  Normal   AIC:                          -1142.69
Method:            Maximum Likelihood   BIC:                          -1120.44
                                        No. Observations:                 1927
Date:                Mon, Oct 14 2024   Df Residuals:                     1926
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3192  8.412e-03     37.949      0.000 [  0.303,  0.336]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.7017e-03  1.007e-04     16.905  4.163e-64 [1.504e-03,1.899e-03]
alpha[1]       0.1153  1.466e-02      7.866  3.655e-15   [8.656e-02,  0.144]
beta[1]        0.8650  1.448e-02     59.730      0.000     [  0.837,  0.893]
============================================================================

Covariance estimator: robust
Aligned returns for /MDB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MDB: first_obs and last_obs produce in an empty array.
Aligned returns for /MDLZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MDLZ: first_obs and last_obs produce in an empty array.

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.08566. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06157. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Aligned returns for /MDT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MDT: first_obs and last_obs produce in an empty array.
Aligned returns for /MDU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MDU: first_obs and last_obs produce in an empty array.
Aligned returns for /MEDP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MEDP: first_obs and last_obs produce in an empty array.
Aligned returns for /MET:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MET: first_obs and last_obs produce in an empty array.
Aligned returns for /META:
Date
2001-01-03    1.280489
2001-01-04    1.308866
2001-01-05    1.308060
2001-01-08    1.308618
2001-01-09    1.307579
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-03  1.280489  0.0668 -0.0507
2001-01-04  1.308866  0.0668 -0.0507
2001-01-05  1.308060  0.0668 -0.0507
2001-01-08  1.308618  0.0668 -0.0507
2001-01-09  1.307579  0.0668 -0.0507
Results for /META:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                197.648
Distribution:                  Normal   AIC:                          -387.297
Method:            Maximum Likelihood   BIC:                          -372.429
                                        No. Observations:                  304
Date:                Mon, Oct 14 2024   Df Residuals:                      303
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.5758  2.957e-03    532.809      0.000 [  1.570,  1.582]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.1261e-03  1.159e-04      9.719  2.512e-22 [8.990e-04,1.353e-03]
alpha[1]       0.6305  5.617e-02     11.224  3.112e-29     [  0.520,  0.741]
beta[1]        0.3310  5.741e-02      5.765  8.162e-09     [  0.218,  0.443]
============================================================================

Covariance estimator: robust
Aligned returns for /MGM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MGM: first_obs and last_obs produce in an empty array.
Aligned returns for /MHK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MHK: first_obs and last_obs produce in an empty array.
Aligned returns for /MIDD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MIDD: first_obs and last_obs produce in an empty array.
Aligned returns for /MKC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MKC: first_obs and last_obs produce in an empty array.
Aligned returns for /MKL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MKL: first_obs and last_obs produce in an empty array.
Aligned returns for /MKSI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MKSI: first_obs and last_obs produce in an empty array.
Aligned returns for /MKTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MKTX: first_obs and last_obs produce in an empty array.
Aligned returns for /MLM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MLM: first_obs and last_obs produce in an empty array.
Aligned returns for /MMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MMC: first_obs and last_obs produce in an empty array.
Aligned returns for /MMM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MMM: first_obs and last_obs produce in an empty array.
Aligned returns for /MNST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MNST: first_obs and last_obs produce in an empty array.
Aligned returns for /MO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MO: first_obs and last_obs produce in an empty array.
Aligned returns for /MOH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MOH: first_obs and last_obs produce in an empty array.
Aligned returns for /MORN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MORN: first_obs and last_obs produce in an empty array.
Aligned returns for /MOS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MOS: first_obs and last_obs produce in an empty array.
Aligned returns for /MP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MP: first_obs and last_obs produce in an empty array.
Aligned returns for /MPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MPC: first_obs and last_obs produce in an empty array.
Aligned returns for /MPW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MPW: first_obs and last_obs produce in an empty array.
Aligned returns for /MPWR:
Date
2001-01-02    1.389233
2001-01-03    1.389718
2001-01-04    1.446377
2001-01-05    1.446055
2001-01-08    1.453322
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  1.389233  0.0668 -0.0507
2001-01-03  1.389718  0.0668 -0.0507
2001-01-04  1.446377  0.0668 -0.0507
2001-01-05  1.446055  0.0668 -0.0507
2001-01-08  1.453322  0.0668 -0.0507

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.08644. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.08949. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /MPWR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                228.870
Distribution:                  Normal   AIC:                          -449.741
Method:            Maximum Likelihood   BIC:                          -434.781
                                        No. Observations:                  311
Date:                Mon, Oct 14 2024   Df Residuals:                      310
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.5752  1.633e-03    964.497      0.000 [  1.572,  1.578]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      7.4570e-05  4.283e-05      1.741  8.166e-02 [-9.371e-06,1.585e-04]
alpha[1]       1.0000      0.338      2.959  3.082e-03      [  0.338,  1.662]
beta[1]    1.4890e-09      0.319  4.668e-09      1.000      [ -0.625,  0.625]
=============================================================================

Covariance estimator: robust
Aligned returns for /MRK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MRK: first_obs and last_obs produce in an empty array.
Aligned returns for /MRNA:
Date
2001-01-02    1.189430
2001-01-03    1.075123
2001-01-04    1.077144
2001-01-05    1.077578
2001-01-08    1.077430
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  1.189430  0.0668 -0.0507
2001-01-03  1.075123  0.0668 -0.0507
2001-01-04  1.077144  0.0668 -0.0507
2001-01-05  1.077578  0.0668 -0.0507
2001-01-08  1.077430  0.0668 -0.0507
Results for /MRNA:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                131.853
Distribution:                  Normal   AIC:                          -255.706
Method:            Maximum Likelihood   BIC:                          -231.974
                                        No. Observations:                 2788
Date:                Mon, Oct 14 2024   Df Residuals:                     2787
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7096  3.652e-03    194.315      0.000 [  0.702,  0.717]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.2754e-03  8.975e-05     36.494 1.375e-291 [3.099e-03,3.451e-03]
alpha[1]       0.3799  3.242e-02     11.721  9.993e-32     [  0.316,  0.443]
beta[1]        0.6883  1.333e-02     51.632      0.000     [  0.662,  0.714]
============================================================================

Covariance estimator: robust
WARNING: The optimizer did not indicate successful convergence. The message was Positive directional derivative for linesearch.
See convergence_flag.

Aligned returns for /MRO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MRO: first_obs and last_obs produce in an empty array.
Aligned returns for /MRVL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MRVL: first_obs and last_obs produce in an empty array.
Aligned returns for /MS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MS: first_obs and last_obs produce in an empty array.
Aligned returns for /MSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MSA: first_obs and last_obs produce in an empty array.
Aligned returns for /MSCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MSCI: first_obs and last_obs produce in an empty array.
Aligned returns for /MSFT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MSFT: first_obs and last_obs produce in an empty array.
Aligned returns for /MSGS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MSGS: first_obs and last_obs produce in an empty array.
Aligned returns for /MSI:
Date
2001-01-25    1.228621
2001-01-26    1.210693
2001-01-29    1.210975
2001-01-30    1.225462
2001-01-31    1.229143
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-25  1.228621  0.0668 -0.0507
2001-01-26  1.210693  0.0668 -0.0507
2001-01-29  1.210975  0.0668 -0.0507
2001-01-30  1.225462  0.0668 -0.0507
2001-01-31  1.229143  0.0668 -0.0507
Results for /MSI:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                771.119
Distribution:                  Normal   AIC:                          -1534.24
Method:            Maximum Likelihood   BIC:                          -1510.33
                                        No. Observations:                 2913
Date:                Mon, Oct 14 2024   Df Residuals:                     2912
Time:                        14:49:30   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7565  4.431e-03    170.703      0.000 [  0.748,  0.765]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.8213e-03  8.055e-05     22.611 3.415e-113 [1.663e-03,1.979e-03]
alpha[1]       0.2000  9.671e-03     20.676  5.721e-95     [  0.181,  0.219]
beta[1]        0.7799  9.241e-03     84.388      0.000     [  0.762,  0.798]
============================================================================

Covariance estimator: robust
Aligned returns for /MSM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MSM: first_obs and last_obs produce in an empty array.
Aligned returns for /MSTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MSTR: first_obs and last_obs produce in an empty array.
Aligned returns for /MTB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTB: first_obs and last_obs produce in an empty array.
Aligned returns for /MTCH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTCH: first_obs and last_obs produce in an empty array.
Aligned returns for /MTD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTD: first_obs and last_obs produce in an empty array.
Aligned returns for /MTDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTDR: first_obs and last_obs produce in an empty array.
Aligned returns for /MTG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTG: first_obs and last_obs produce in an empty array.
Aligned returns for /MTN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTN: first_obs and last_obs produce in an empty array.
Aligned returns for /MTSI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTSI: first_obs and last_obs produce in an empty array.
Aligned returns for /MTZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MTZ: first_obs and last_obs produce in an empty array.
Aligned returns for /MU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MU: first_obs and last_obs produce in an empty array.
Aligned returns for /MUSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /MUSA: first_obs and last_obs produce in an empty array.
Aligned returns for /NBIX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NBIX: first_obs and last_obs produce in an empty array.
Aligned returns for /NCLH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NCLH: first_obs and last_obs produce in an empty array.
Aligned returns for /NCNO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NCNO: first_obs and last_obs produce in an empty array.
Aligned returns for /NDAQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NDAQ: first_obs and last_obs produce in an empty array.
Aligned returns for /NDSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NDSN: first_obs and last_obs produce in an empty array.
Aligned returns for /NEE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NEE: first_obs and last_obs produce in an empty array.
Aligned returns for /NEM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NEM: first_obs and last_obs produce in an empty array.
Aligned returns for /NET:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NET: first_obs and last_obs produce in an empty array.
Aligned returns for /NEU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NEU: first_obs and last_obs produce in an empty array.
Aligned returns for /NFE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NFE: first_obs and last_obs produce in an empty array.
Aligned returns for /NFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NFG: first_obs and last_obs produce in an empty array.
Aligned returns for /NFLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NFLX: first_obs and last_obs produce in an empty array.
Aligned returns for /NI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NI: first_obs and last_obs produce in an empty array.
Aligned returns for /NKE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NKE: first_obs and last_obs produce in an empty array.
Aligned returns for /NLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NLY: first_obs and last_obs produce in an empty array.
Aligned returns for /NNN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NNN: first_obs and last_obs produce in an empty array.
Aligned returns for /NOC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NOC: first_obs and last_obs produce in an empty array.
Aligned returns for /NOV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NOV: first_obs and last_obs produce in an empty array.
Aligned returns for /NOW:
Date
2001-01-04    1.900647
2001-01-05    1.900647
2001-01-08    1.892841
2001-01-09    1.811240
2001-01-10    1.993268
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-04  1.900647  0.0668 -0.0507
2001-01-05  1.900647  0.0668 -0.0507
2001-01-08  1.892841  0.0668 -0.0507
2001-01-09  1.811240  0.0668 -0.0507
2001-01-10  1.993268  0.0668 -0.0507

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.0844. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01651. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /NOW:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                240.369
Distribution:                  Normal   AIC:                          -472.738
Method:            Maximum Likelihood   BIC:                          -455.419
                                        No. Observations:                  561
Date:                Mon, Oct 14 2024   Df Residuals:                      560
Time:                        14:49:31   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             2.0869  2.869e-03    727.405      0.000 [  2.081,  2.093]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.0289e-03  7.624e-05     13.495  1.663e-41 [8.795e-04,1.178e-03]
alpha[1]       0.5066  2.873e-02     17.632  1.402e-69     [  0.450,  0.563]
beta[1]        0.4328  3.570e-02     12.122  8.060e-34     [  0.363,  0.503]
============================================================================

Covariance estimator: robust
Aligned returns for /NRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NRG: first_obs and last_obs produce in an empty array.
Aligned returns for /NSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NSA: first_obs and last_obs produce in an empty array.
Aligned returns for /NSC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NSC: first_obs and last_obs produce in an empty array.
Aligned returns for /NTAP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NTAP: first_obs and last_obs produce in an empty array.
Aligned returns for /NTNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NTNX: first_obs and last_obs produce in an empty array.
Aligned returns for /NTRA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NTRA: first_obs and last_obs produce in an empty array.
Aligned returns for /NTRS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NTRS: first_obs and last_obs produce in an empty array.
Aligned returns for /NU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NU: first_obs and last_obs produce in an empty array.
Aligned returns for /NUE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NUE: first_obs and last_obs produce in an empty array.
Aligned returns for /NVDA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NVDA: first_obs and last_obs produce in an empty array.
Aligned returns for /NVR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NVR: first_obs and last_obs produce in an empty array.
Aligned returns for /NVST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NVST: first_obs and last_obs produce in an empty array.
Aligned returns for /NVT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NVT: first_obs and last_obs produce in an empty array.
Aligned returns for /NWL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NWL: first_obs and last_obs produce in an empty array.
Aligned returns for /NWS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NWS: first_obs and last_obs produce in an empty array.
Aligned returns for /NWSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NWSA: first_obs and last_obs produce in an empty array.
Aligned returns for /NXST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NXST: first_obs and last_obs produce in an empty array.
Aligned returns for /NYT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /NYT: first_obs and last_obs produce in an empty array.
Aligned returns for /O:
Date
2002-02-06    2.259412
2002-02-07    2.259436
2002-02-15    2.259226
2002-02-20    2.258886
2002-02-21    2.258889
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2002-02-06  2.259412 -0.0101  0.0216
2002-02-07  2.259436 -0.0101  0.0216
2002-02-15  2.259226 -0.0101  0.0216
2002-02-20  2.258886 -0.0101  0.0216
2002-02-21  2.258889 -0.0101  0.0216
Results for /O:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                117.573
Distribution:                  Normal   AIC:                          -227.146
Method:            Maximum Likelihood   BIC:                          -217.984
                                        No. Observations:                   73
Date:                Mon, Oct 14 2024   Df Residuals:                       72
Time:                        14:49:31   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             2.2713  1.926e-03   1179.055      0.000 [  2.267,  2.275]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.8543e-05  2.877e-08    644.507      0.000  [1.849e-05,1.860e-05]
alpha[1]       0.9881      0.150      6.582  4.629e-11      [  0.694,  1.282]
beta[1]    1.9098e-03  7.447e-03      0.256      0.798 [-1.269e-02,1.651e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /OC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OC: first_obs and last_obs produce in an empty array.
Aligned returns for /ODFL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ODFL: first_obs and last_obs produce in an empty array.
Aligned returns for /OGE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OGE: first_obs and last_obs produce in an empty array.
Aligned returns for /OGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OGN: first_obs and last_obs produce in an empty array.
Aligned returns for /OHI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OHI: first_obs and last_obs produce in an empty array.
Aligned returns for /OKE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

Error fitting GARCH model for /OKE: first_obs and last_obs produce in an empty array.
Aligned returns for /OKTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OKTA: first_obs and last_obs produce in an empty array.
Aligned returns for /OLED:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OLED: first_obs and last_obs produce in an empty array.
Aligned returns for /OLLI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OLLI: first_obs and last_obs produce in an empty array.
Aligned returns for /OLN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OLN: first_obs and last_obs produce in an empty array.
Aligned returns for /OMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OMC: first_obs and last_obs produce in an empty array.
Aligned returns for /OMF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OMF: first_obs and last_obs produce in an empty array.
Aligned returns for /ON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ON: first_obs and last_obs produce in an empty array.
Aligned returns for /ONTO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ONTO: first_obs and last_obs produce in an empty array.
Aligned returns for /ORCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ORCL: first_obs and last_obs produce in an empty array.
Aligned returns for /ORI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ORI: first_obs and last_obs produce in an empty array.
Aligned returns for /ORLY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ORLY: first_obs and last_obs produce in an empty array.
Aligned returns for /OSK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OSK: first_obs and last_obs produce in an empty array.
Aligned returns for /OTIS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OTIS: first_obs and last_obs produce in an empty array.
Aligned returns for /OVV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OVV: first_obs and last_obs produce in an empty array.
Aligned returns for /OWL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OWL: first_obs and last_obs produce in an empty array.
Aligned returns for /OXY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OXY: first_obs and last_obs produce in an empty array.
Aligned returns for /OZK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /OZK: first_obs and last_obs produce in an empty array.
Aligned returns for /PAG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PAG: first_obs and last_obs produce in an empty array.
Aligned returns for /PANW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PANW: first_obs and last_obs produce in an empty array.
Aligned returns for /PARA:
Date
2001-01-05    1.970135
2001-01-08    1.969728
2001-01-10    1.968699
2001-01-11    1.971409
2001-01-12    1.973113
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-05  1.970135  0.0668 -0.0507
2001-01-08  1.969728  0.0668 -0.0507
2001-01-10  1.968699  0.0668 -0.0507
2001-01-11  1.971409  0.0668 -0.0507
2001-01-12  1.973113  0.0668 -0.0507
Results for /PARA:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                218.521
Distribution:                  Normal   AIC:                          -429.042
Method:            Maximum Likelihood   BIC:                          -414.663
                                        No. Observations:                  269
Date:                Mon, Oct 14 2024   Df Residuals:                      268
Time:                        14:49:31   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.9805  2.733e-02     72.460      0.000 [  1.927,  2.034]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.1607e-04  1.403e-04      0.827      0.408 [-1.589e-04,3.911e-04]
alpha[1]       1.0000      1.655      0.604      0.546      [ -2.243,  4.243]
beta[1]    9.5923e-14      1.406  6.822e-14      1.000      [ -2.756,  2.756]
=============================================================================

Covariance estimator: robust
Aligned returns for /PARAA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PARAA: first_obs and last_obs produce in an empty array.
Aligned returns for /PATH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PATH: first_obs and last_obs produce in an empty array.
Aligned returns for /PAYC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PAYC: first_obs and last_obs produce in an empty array.
Aligned returns for /PAYX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PAYX: first_obs and last_obs produce in an empty array.
Aligned returns for /PB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PB: first_obs and last_obs produce in an empty array.
Aligned returns for /PCAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PCAR: first_obs and last_obs produce in an empty array.
Aligned returns for /PCG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PCG: first_obs and last_obs produce in an empty array.
Aligned returns for /PCOR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PCOR: first_obs and last_obs produce in an empty array.
Aligned returns for /PCTY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PCTY: first_obs and last_obs produce in an empty array.
Aligned returns for /PEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.03466. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.09816. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /PEG: first_obs and last_obs produce in an empty array.
Aligned returns for /PEGA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PEGA: first_obs and last_obs produce in an empty array.
Aligned returns for /PEN:
Date
2001-01-10    1.969818
2001-01-11    1.766699
2001-01-12    1.766699
2001-01-16    1.766699
2001-01-17    1.813157
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-10  1.969818  0.0668 -0.0507
2001-01-11  1.766699  0.0668 -0.0507
2001-01-12  1.766699  0.0668 -0.0507
2001-01-16  1.766699  0.0668 -0.0507
2001-01-17  1.813157  0.0668 -0.0507
Results for /PEN:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                793.987
Distribution:                  Normal   AIC:                          -1579.97
Method:            Maximum Likelihood   BIC:                          -1557.65
                                        No. Observations:                 1961
Date:                Mon, Oct 14 2024   Df Residuals:                     1960
Time:                        14:49:31   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.0348  5.721e-03    180.876      0.000 [  1.024,  1.046]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.7848e-03  7.438e-05     23.996 3.038e-127 [1.639e-03,1.931e-03]
alpha[1]       0.1858  6.647e-03     27.954 5.865e-172     [  0.173,  0.199]
beta[1]        0.6970  1.380e-02     50.494      0.000     [  0.670,  0.724]
============================================================================

Covariance estimator: robust
Aligned returns for /PENN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PENN: first_obs and last_obs produce in an empty array.
Aligned returns for /PEP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PEP: first_obs and last_obs produce in an empty array.
Aligned returns for /PFE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PFE: first_obs and last_obs produce in an empty array.
Aligned returns for /PFG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PFG: first_obs and last_obs produce in an empty array.
Aligned returns for /PFGC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PFGC: first_obs and last_obs produce in an empty array.
Aligned returns for /PG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PG: first_obs and last_obs produce in an empty array.
Aligned returns for /PGR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PGR: first_obs and last_obs produce in an empty array.
Aligned returns for /PH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PH: first_obs and last_obs produce in an empty array.
Aligned returns for /PHM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PHM: first_obs and last_obs produce in an empty array.
Aligned returns for /PII:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PII: first_obs and last_obs produce in an empty array.
Aligned returns for /PINC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PINC: first_obs and last_obs produce in an empty array.
Aligned returns for /PINS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PINS: first_obs and last_obs produce in an empty array.
Aligned returns for /PK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PK: first_obs and last_obs produce in an empty array.
Aligned returns for /PKG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PKG: first_obs and last_obs produce in an empty array.
Aligned returns for /PLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PLD: first_obs and last_obs produce in an empty array.
Aligned returns for /PLNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PLNT: first_obs and last_obs produce in an empty array.
Aligned returns for /PLTK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PLTK: first_obs and last_obs produce in an empty array.
Aligned returns for /PLTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PLTR: first_obs and last_obs produce in an empty array.
Aligned returns for /PM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PM: first_obs and last_obs produce in an empty array.
Aligned returns for /PNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PNC: first_obs and last_obs produce in an empty array.
Aligned returns for /PNFP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PNFP: first_obs and last_obs produce in an empty array.
Aligned returns for /PNR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PNR: first_obs and last_obs produce in an empty array.
Aligned returns for /PNW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PNW: first_obs and last_obs produce in an empty array.
Aligned returns for /PODD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PODD: first_obs and last_obs produce in an empty array.
Aligned returns for /POOL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /POOL: first_obs and last_obs produce in an empty array.
Aligned returns for /POST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /POST: first_obs and last_obs produce in an empty array.
Duplicates found in returns for /PPC. Resolving...
Aligned returns for /PPC:
Date
2000-05-17    4.113740
2000-07-03    4.101061
2000-07-27    4.084501
2000-11-24    4.037371
2001-01-08    0.713215
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2000-05-17  4.113740 -0.0605  0.0475
2000-07-03  4.101061 -0.0307  0.0831
2000-07-27  4.084501 -0.0307  0.0831
2000-11-24  4.037371 -0.0341  0.1230
2001-01-08  0.713215  0.0668 -0.0507
Results for /PPC:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                3032.65
Distribution:                  Normal   AIC:                          -6057.30
Method:            Maximum Likelihood   BIC:                          -6032.35
                                        No. Observations:                 3781
Date:                Mon, Oct 14 2024   Df Residuals:                     3780
Time:                        14:49:31   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5693  2.500e-03    227.742      0.000 [  0.564,  0.574]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.7250e-03  3.153e-05     54.712      0.000 [1.663e-03,1.787e-03]
alpha[1]       0.3210  9.713e-03     33.047 1.724e-239     [  0.302,  0.340]
beta[1]        0.6619  6.584e-03    100.534      0.000     [  0.649,  0.675]
============================================================================

Covariance estimator: robust
Aligned returns for /PPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PPG: first_obs and last_obs produce in an empty array.
Aligned returns for /PPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PPL: first_obs and last_obs produce in an empty array.
Aligned returns for /PR:
Date
2001-01-02    0.474384
2001-01-03    0.472344
2001-01-04    0.472131
2001-01-05    0.472125
2001-01-08    0.471503
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.474384  0.0668 -0.0507
2001-01-03  0.472344  0.0668 -0.0507
2001-01-04  0.472131  0.0668 -0.0507
2001-01-05  0.472125  0.0668 -0.0507
2001-01-08  0.471503  0.0668 -0.0507
Results for /PR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1753.58
Distribution:                  Normal   AIC:                          -3499.16
Method:            Maximum Likelihood   BIC:                          -3478.12
                                        No. Observations:                 1420
Date:                Mon, Oct 14 2024   Df Residuals:                     1419
Time:                        14:49:31   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.2685  5.220e-03     51.447      0.000 [  0.258,  0.279]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.6582e-04  9.724e-06     17.052  3.386e-65 [1.468e-04,1.849e-04]
alpha[1]       0.2000  1.118e-02     17.890  1.418e-71     [  0.178,  0.222]
beta[1]        0.7800  1.177e-02     66.266      0.000     [  0.757,  0.803]
============================================================================

Covariance estimator: robust
Aligned returns for /PRGO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PRGO: first_obs and last_obs produce in an empty array.
Aligned returns for /PRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PRI: first_obs and last_obs produce in an empty array.
Aligned returns for /PRU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PRU: first_obs and last_obs produce in an empty array.
Aligned returns for /PSA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PSA: first_obs and last_obs produce in an empty array.
Aligned returns for /PSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PSN: first_obs and last_obs produce in an empty array.
Aligned returns for /PSTG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PSTG: first_obs and last_obs produce in an empty array.
Aligned returns for /PSX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06158. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.008236. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /PSX: first_obs and last_obs produce in an empty array.
Aligned returns for /PTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PTC: first_obs and last_obs produce in an empty array.
Aligned returns for /PVH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PVH: first_obs and last_obs produce in an empty array.
Aligned returns for /PWR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PWR: first_obs and last_obs produce in an empty array.
Aligned returns for /PYCR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PYCR: first_obs and last_obs produce in an empty array.
Aligned returns for /PYPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /PYPL: first_obs and last_obs produce in an empty array.
Aligned returns for /QCOM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /QCOM: first_obs and last_obs produce in an empty array.
Aligned returns for /QDEL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /QDEL: first_obs and last_obs produce in an empty array.
Aligned returns for /QGEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /QGEN: first_obs and last_obs produce in an empty array.
Aligned returns for /QRVO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /QRVO: first_obs and last_obs produce in an empty array.
Aligned returns for /QS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /QS: first_obs and last_obs produce in an empty array.
Aligned returns for /R:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /R: first_obs and last_obs produce in an empty array.
Aligned returns for /RARE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RARE: first_obs and last_obs produce in an empty array.
Aligned returns for /RBA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RBA: first_obs and last_obs produce in an empty array.
Aligned returns for /RBC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RBC: first_obs and last_obs produce in an empty array.
Aligned returns for /RBLX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RBLX: first_obs and last_obs produce in an empty array.
Aligned returns for /RCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RCL: first_obs and last_obs produce in an empty array.
Aligned returns for /RCM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RCM: first_obs and last_obs produce in an empty array.
Aligned returns for /REG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /REG: first_obs and last_obs produce in an empty array.
Aligned returns for /REGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /REGN: first_obs and last_obs produce in an empty array.
Aligned returns for /REXR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /REXR: first_obs and last_obs produce in an empty array.
Aligned returns for /REYN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /REYN: first_obs and last_obs produce in an empty array.
Aligned returns for /RF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RF: first_obs and last_obs produce in an empty array.
Aligned returns for /RGA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RGA: first_obs and last_obs produce in an empty array.
Aligned returns for /RGEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RGEN: first_obs and last_obs produce in an empty array.
Aligned returns for /RGLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RGLD: first_obs and last_obs produce in an empty array.
Aligned returns for /RH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RH: first_obs and last_obs produce in an empty array.
Aligned returns for /RHI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RHI: first_obs and last_obs produce in an empty array.
Aligned returns for /RITM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RITM: first_obs and last_obs produce in an empty array.
Aligned returns for /RIVN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RIVN: first_obs and last_obs produce in an empty array.
Aligned returns for /RJF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RJF: first_obs and last_obs produce in an empty array.
Aligned returns for /RKT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RKT: first_obs and last_obs produce in an empty array.
Aligned returns for /RL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RL: first_obs and last_obs produce in an empty array.
Aligned returns for /RLI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RLI: first_obs and last_obs produce in an empty array.
Aligned returns for /RMD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RMD: first_obs and last_obs produce in an empty array.
Aligned returns for /RNG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RNG: first_obs and last_obs produce in an empty array.
Aligned returns for /RNR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RNR: first_obs and last_obs produce in an empty array.
Aligned returns for /ROIV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ROIV: first_obs and last_obs produce in an empty array.
Aligned returns for /ROK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ROK: first_obs and last_obs produce in an empty array.
Aligned returns for /ROKU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ROKU: first_obs and last_obs produce in an empty array.
Aligned returns for /ROL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ROL: first_obs and last_obs produce in an empty array.
Aligned returns for /ROP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ROP: first_obs and last_obs produce in an empty array.
Aligned returns for /ROST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ROST: first_obs and last_obs produce in an empty array.
Aligned returns for /RPM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RPM: first_obs and last_obs produce in an empty array.
Aligned returns for /RPRX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RPRX: first_obs and last_obs produce in an empty array.
Aligned returns for /RRC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

Error fitting GARCH model for /RRC: first_obs and last_obs produce in an empty array.
Aligned returns for /RRX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RRX: first_obs and last_obs produce in an empty array.
Aligned returns for /RS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RS: first_obs and last_obs produce in an empty array.
Aligned returns for /RSG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RSG: first_obs and last_obs produce in an empty array.
Aligned returns for /RTX:
Date
2001-07-10    1.501723
2001-07-11    1.501723
2001-07-12    1.504983
2001-07-13    1.504510
2001-07-16    1.514368
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-07-10  1.501723 -0.0419  0.0521
2001-07-11  1.501723 -0.0419  0.0521
2001-07-12  1.504983 -0.0419  0.0521
2001-07-13  1.504510 -0.0419  0.0521
2001-07-16  1.514368 -0.0419  0.0521
Results for /RTX:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -810.656
Distribution:                  Normal   AIC:                           1629.31
Method:            Maximum Likelihood   BIC:                           1652.75
                                        No. Observations:                 2589
Date:                Mon, Oct 14 2024   Df Residuals:                     2588
Time:                        14:49:32   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.6325  3.572e-03    456.981      0.000 [  1.626,  1.640]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.4148e-03  9.050e-05     15.633  4.314e-55 [1.237e-03,1.592e-03]
alpha[1]       0.7495  3.994e-02     18.765  1.453e-78     [  0.671,  0.828]
beta[1]        0.1305  5.251e-02      2.485  1.297e-02   [2.755e-02,  0.233]
============================================================================

Covariance estimator: robust
Aligned returns for /RVTY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RVTY: first_obs and last_obs produce in an empty array.
Aligned returns for /RYAN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RYAN: first_obs and last_obs produce in an empty array.
Aligned returns for /RYN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /RYN: first_obs and last_obs produce in an empty array.
Aligned returns for /S:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /S: first_obs and last_obs produce in an empty array.
Aligned returns for /SAIA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SAIA: first_obs and last_obs produce in an empty array.
Aligned returns for /SAIC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SAIC: first_obs and last_obs produce in an empty array.
Aligned returns for /SAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SAM: first_obs and last_obs produce in an empty array.
Aligned returns for /SBAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SBAC: first_obs and last_obs produce in an empty array.
Aligned returns for /SBUX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SBUX: first_obs and last_obs produce in an empty array.
Aligned returns for /SCCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SCCO: first_obs and last_obs produce in an empty array.
Aligned returns for /SCHW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SCHW: first_obs and last_obs produce in an empty array.
Aligned returns for /SCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SCI: first_obs and last_obs produce in an empty array.
Aligned returns for /SEB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SEB: first_obs and last_obs produce in an empty array.
Aligned returns for /SEE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SEE: first_obs and last_obs produce in an empty array.
Aligned returns for /SEG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SEG: first_obs and last_obs produce in an empty array.
Aligned returns for /SEIC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SEIC: first_obs and last_obs produce in an empty array.
Aligned returns for /SF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SF: first_obs and last_obs produce in an empty array.
Aligned returns for /SHC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SHC: first_obs and last_obs produce in an empty array.
Aligned returns for /SHW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SHW: first_obs and last_obs produce in an empty array.
Aligned returns for /SIRI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SIRI: first_obs and last_obs produce in an empty array.
Aligned returns for /SITE:
Date
2001-01-02    0.926704
2001-01-03    0.912335
2001-01-04    0.913044
2001-01-05    0.919558
2001-01-08    0.918814
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.926704  0.0668 -0.0507
2001-01-03  0.912335  0.0668 -0.0507
2001-01-04  0.913044  0.0668 -0.0507
2001-01-05  0.919558  0.0668 -0.0507
2001-01-08  0.918814  0.0668 -0.0507
Results for /SITE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:           -1.57059e+06
Distribution:                  Normal   AIC:                       3.14119e+06
Method:            Maximum Likelihood   BIC:                       3.14120e+06
                                        No. Observations:                  476
Date:                Mon, Oct 14 2024   Df Residuals:                      475
Time:                        14:49:32   Df Model:                            1
                                  Mean Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
mu          -708.9071  1.130e+05 -6.272e-03      0.995 [-2.223e+05,2.208e+05]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.3686e-09     22.590  6.059e-11      1.000      [-44.275, 44.275]
alpha[1]       1.0000     94.892  1.054e-02      0.992 [-1.850e+02,1.870e+02]
beta[1]    8.6719e-04    113.532  7.638e-06      1.000 [-2.225e+02,2.225e+02]
=============================================================================

Covariance estimator: robust
WARNING: The optimizer did not indicate successful convergence. The message was Inequality constraints incompatible.
See convergence_flag.

Aligned returns for /SJM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SJM: first_obs and last_obs produce in an empty array.
Aligned returns for /SKX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SKX: first_obs and last_obs produce in an empty array.
Aligned returns for /SLB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SLB: first_obs and last_obs produce in an empty array.
Aligned returns for /SLGN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SLGN: first_obs and last_obs produce in an empty array.
Aligned returns for /SLM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SLM: first_obs and last_obs produce in an empty array.
Aligned returns for /SMAR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SMAR: first_obs and last_obs produce in an empty array.
Aligned returns for /SMCI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SMCI: first_obs and last_obs produce in an empty array.
Aligned returns for /SMG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SMG: first_obs and last_obs produce in an empty array.
Aligned returns for /SN:
Date
2012-12-17    0.421858
2012-12-18    0.422822
2012-12-19    0.423404
2012-12-20    0.422704
2012-12-21    0.422751
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2012-12-17  0.421858  0.0148  0.0351
2012-12-18  0.422822  0.0148  0.0351
2012-12-19  0.423404  0.0148  0.0351
2012-12-20  0.422704  0.0148  0.0351
2012-12-21  0.422751  0.0148  0.0351
Results for /SN:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                803.785
Distribution:                  Normal   AIC:                          -1599.57
Method:            Maximum Likelihood   BIC:                          -1578.18
                                        No. Observations:                 1553
Date:                Mon, Oct 14 2024   Df Residuals:                     1552
Time:                        14:49:32   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7807  2.971e-03    262.800      0.000 [  0.775,  0.787]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.1395e-03  4.827e-05     23.607 3.304e-123 [1.045e-03,1.234e-03]
alpha[1]       0.2000  8.494e-03     23.544 1.457e-122     [  0.183,  0.217]
beta[1]        0.7800  8.247e-03     94.573      0.000     [  0.764,  0.796]
============================================================================

Covariance estimator: robust
Aligned returns for /SNA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SNA: first_obs and last_obs produce in an empty array.
Aligned returns for /SNDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:766: ConvergenceWarning: The optimizer returned code 4. The message is:
Inequality constraints incompatible
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.05606. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /SNDR: first_obs and last_obs produce in an empty array.
Aligned returns for /SNOW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SNOW: first_obs and last_obs produce in an empty array.
Aligned returns for /SNPS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SNPS: first_obs and last_obs produce in an empty array.
Aligned returns for /SNV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SNV: first_obs and last_obs produce in an empty array.
Aligned returns for /SNX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SNX: first_obs and last_obs produce in an empty array.
Aligned returns for /SO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SO: first_obs and last_obs produce in an empty array.
Aligned returns for /SOFI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SOFI: first_obs and last_obs produce in an empty array.
Aligned returns for /SON:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SON: first_obs and last_obs produce in an empty array.
Aligned returns for /SPB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SPB: first_obs and last_obs produce in an empty array.
Aligned returns for /SPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SPG: first_obs and last_obs produce in an empty array.
Aligned returns for /SPGI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SPGI: first_obs and last_obs produce in an empty array.
Aligned returns for /SPOT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SPOT: first_obs and last_obs produce in an empty array.
Aligned returns for /SPR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SPR: first_obs and last_obs produce in an empty array.
Aligned returns for /SQ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SQ: first_obs and last_obs produce in an empty array.
Aligned returns for /SRCL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SRCL: first_obs and last_obs produce in an empty array.
Aligned returns for /SRE:
Date
2001-01-03    0.718646
2001-01-04    0.718749
2001-01-05    0.718651
2001-01-08    0.718282
2001-01-09    0.718295
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-03  0.718646  0.0668 -0.0507
2001-01-04  0.718749  0.0668 -0.0507
2001-01-05  0.718651  0.0668 -0.0507
2001-01-08  0.718282  0.0668 -0.0507
2001-01-09  0.718295  0.0668 -0.0507
Results for /SRE:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                471.210
Distribution:                  Normal   AIC:                          -934.420
Method:            Maximum Likelihood   BIC:                          -917.878
                                        No. Observations:                  462
Date:                Mon, Oct 14 2024   Df Residuals:                      461
Time:                        14:49:32   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5089  2.047e-02     24.859 2.081e-136 [  0.469,  0.549]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.1395e-04  1.285e-04      2.443  1.455e-02 [6.211e-05,5.658e-04]
alpha[1]       0.1998  3.890e-02      5.135  2.824e-07     [  0.124,  0.276]
beta[1]        0.7790  3.884e-02     20.060  1.651e-89     [  0.703,  0.855]
============================================================================

Covariance estimator: robust
Aligned returns for /SRPT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SRPT: first_obs and last_obs produce in an empty array.
Aligned returns for /SSD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SSD: first_obs and last_obs produce in an empty array.
Aligned returns for /SSNC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SSNC: first_obs and last_obs produce in an empty array.
Aligned returns for /ST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ST: first_obs and last_obs produce in an empty array.
Aligned returns for /STAG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /STAG: first_obs and last_obs produce in an empty array.
Aligned returns for /STE:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /STE: first_obs and last_obs produce in an empty array.
Aligned returns for /STLD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /STLD: first_obs and last_obs produce in an empty array.
Aligned returns for /STT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /STT: first_obs and last_obs produce in an empty array.
Aligned returns for /STWD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /STWD: first_obs and last_obs produce in an empty array.
Aligned returns for /STZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /STZ: first_obs and last_obs produce in an empty array.
Aligned returns for /SUI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SUI: first_obs and last_obs produce in an empty array.
Aligned returns for /SW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SW: first_obs and last_obs produce in an empty array.
Aligned returns for /SWK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SWK: first_obs and last_obs produce in an empty array.
Aligned returns for /SWKS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SWKS: first_obs and last_obs produce in an empty array.
Aligned returns for /SWN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SWN: first_obs and last_obs produce in an empty array.
Aligned returns for /SYF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SYF: first_obs and last_obs produce in an empty array.
Aligned returns for /SYK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01551. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Error fitting GARCH model for /SYK: first_obs and last_obs produce in an empty array.
Aligned returns for /SYY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /SYY: first_obs and last_obs produce in an empty array.
Aligned returns for /T:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /T: first_obs and last_obs produce in an empty array.
Aligned returns for /TAP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TAP: first_obs and last_obs produce in an empty array.
Aligned returns for /TDC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TDC: first_obs and last_obs produce in an empty array.
Aligned returns for /TDG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TDG: first_obs and last_obs produce in an empty array.
Aligned returns for /TDY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TDY: first_obs and last_obs produce in an empty array.
Aligned returns for /TEAM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TEAM: first_obs and last_obs produce in an empty array.
Aligned returns for /TECH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TECH: first_obs and last_obs produce in an empty array.
Aligned returns for /TER:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TER: first_obs and last_obs produce in an empty array.
Aligned returns for /TFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TFC: first_obs and last_obs produce in an empty array.
Aligned returns for /TFSL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TFSL: first_obs and last_obs produce in an empty array.
Aligned returns for /TFX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TFX: first_obs and last_obs produce in an empty array.
Aligned returns for /TGT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TGT: first_obs and last_obs produce in an empty array.
Aligned returns for /THC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /THC: first_obs and last_obs produce in an empty array.
Aligned returns for /THG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /THG: first_obs and last_obs produce in an empty array.
Aligned returns for /THO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /THO: first_obs and last_obs produce in an empty array.
Aligned returns for /TJX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TJX: first_obs and last_obs produce in an empty array.
Aligned returns for /TKO:
Date
2005-02-03    0.789030
2005-02-04    0.789033
2005-02-07    0.789043
2005-02-08    0.797335
2005-02-09    0.803711
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2005-02-03  0.789030 -0.0057  0.0154
2005-02-04  0.789033 -0.0057  0.0154
2005-02-07  0.789043 -0.0057  0.0154
2005-02-08  0.797335 -0.0057  0.0154
2005-02-09  0.803711 -0.0057  0.0154
Results for /TKO:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1348.62
Distribution:                  Normal   AIC:                          -2689.24
Method:            Maximum Likelihood   BIC:                          -2668.87
                                        No. Observations:                 1204
Date:                Mon, Oct 14 2024   Df Residuals:                     1203
Time:                        14:49:32   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7472  1.173e-03    636.938      0.000 [  0.745,  0.750]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.7881e-05  8.517e-06      4.448  8.680e-06  [2.119e-05,5.457e-05]
alpha[1]       0.9876  4.906e-02     20.132  3.892e-90      [  0.891,  1.084]
beta[1]    1.7687e-04  4.713e-02  3.753e-03      0.997 [-9.219e-02,9.254e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /TKR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TKR: first_obs and last_obs produce in an empty array.
Aligned returns for /TMO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TMO: first_obs and last_obs produce in an empty array.
Aligned returns for /TMUS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TMUS: first_obs and last_obs produce in an empty array.
Aligned returns for /TNL:
Date
2001-01-02    1.116075
2001-01-03    1.137865
2001-01-04    1.141020
2001-01-05    1.141586
2001-01-08    1.141928
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  1.116075  0.0668 -0.0507
2001-01-03  1.137865  0.0668 -0.0507
2001-01-04  1.141020  0.0668 -0.0507
2001-01-05  1.141586  0.0668 -0.0507
2001-01-08  1.141928  0.0668 -0.0507
Results for /TNL:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -24.7809
Distribution:                  Normal   AIC:                           57.5619
Method:            Maximum Likelihood   BIC:                           82.1684
                                        No. Observations:                 3469
Date:                Mon, Oct 14 2024   Df Residuals:                     3468
Time:                        14:49:33   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.5008  4.410e-03    113.580      0.000 [  0.492,  0.509]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      6.1952e-03  1.415e-04     43.772      0.000 [5.918e-03,6.473e-03]
alpha[1]       0.2000  7.719e-03     25.906 5.636e-148     [  0.185,  0.215]
beta[1]        0.7799  5.146e-03    151.560      0.000     [  0.770,  0.790]
============================================================================

Covariance estimator: robust
Aligned returns for /TOL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TOL: first_obs and last_obs produce in an empty array.
Aligned returns for /TOST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TOST: first_obs and last_obs produce in an empty array.
Aligned returns for /TPG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TPG: first_obs and last_obs produce in an empty array.
Aligned returns for /TPL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TPL: first_obs and last_obs produce in an empty array.
Aligned returns for /TPR:
Date
2001-01-17    0.700532
2001-01-18    0.700275
2001-01-22    0.701426
2001-01-23    0.701514
2001-01-24    0.701488
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-17  0.700532  0.0668 -0.0507
2001-01-18  0.700275  0.0668 -0.0507
2001-01-22  0.701426  0.0668 -0.0507
2001-01-23  0.701514  0.0668 -0.0507
2001-01-24  0.701488  0.0668 -0.0507
Results for /TPR:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                575.394
Distribution:                  Normal   AIC:                          -1142.79
Method:            Maximum Likelihood   BIC:                          -1120.36
                                        No. Observations:                 2013
Date:                Mon, Oct 14 2024   Df Residuals:                     2012
Time:                        14:49:33   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4710  4.661e-03    101.061      0.000 [  0.462,  0.480]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      5.0187e-03  9.790e-05     51.265      0.000 [4.827e-03,5.211e-03]
alpha[1]       0.2000  7.543e-03     26.514 6.729e-155     [  0.185,  0.215]
beta[1]        0.7799  4.651e-03    167.700      0.000     [  0.771,  0.789]
============================================================================

Covariance estimator: robust
Aligned returns for /TPX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TPX: first_obs and last_obs produce in an empty array.
Aligned returns for /TREX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TREX: first_obs and last_obs produce in an empty array.
Aligned returns for /TRGP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TRGP: first_obs and last_obs produce in an empty array.
Aligned returns for /TRIP:
Date
2001-02-01    2.793173
2001-02-02    2.799561
2001-02-05    2.798425
2001-02-06    2.797710
2001-02-07    2.792669
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-02-01  2.793173 -0.0078  0.1247
2001-02-02  2.799561 -0.0078  0.1247
2001-02-05  2.798425 -0.0078  0.1247
2001-02-06  2.797710 -0.0078  0.1247
2001-02-07  2.792669 -0.0078  0.1247
Results for /TRIP:

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.0181. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                48.0196
Distribution:                  Normal   AIC:                          -88.0393
Method:            Maximum Likelihood   BIC:                          -80.9025
                                        No. Observations:                   44
Date:                Mon, Oct 14 2024   Df Residuals:                       43
Time:                        14:49:33   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             3.0433  1.080e-02    281.710      0.000 [  3.022,  3.064]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.6944e-04  1.095e-04      1.548      0.122 [-4.515e-05,3.840e-04]
alpha[1]       0.9907      0.590      1.680  9.294e-02      [ -0.165,  2.146]
beta[1]    1.0267e-16      0.477  2.153e-16      1.000      [ -0.935,  0.935]
=============================================================================

Covariance estimator: robust
Aligned returns for /TRMB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TRMB: first_obs and last_obs produce in an empty array.
Aligned returns for /TROW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TROW: first_obs and last_obs produce in an empty array.
Aligned returns for /TRU:
Date
2001-01-02    0.413527
2001-01-03    0.412442
2001-01-04    0.412493
2001-01-05    0.413122
2001-01-08    0.413155
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.413527  0.0668 -0.0507
2001-01-03  0.412442  0.0668 -0.0507
2001-01-04  0.412493  0.0668 -0.0507
2001-01-05  0.413122  0.0668 -0.0507
2001-01-08  0.413155  0.0668 -0.0507
Results for /TRU:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                573.574
Distribution:                  Normal   AIC:                          -1139.15
Method:            Maximum Likelihood   BIC:                          -1115.08
                                        No. Observations:                 3032
Date:                Mon, Oct 14 2024   Df Residuals:                     3031
Time:                        14:49:33   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.4857  5.854e-03     82.961      0.000 [  0.474,  0.497]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.2467e-03  7.331e-05     44.285      0.000 [3.103e-03,3.390e-03]
alpha[1]       0.2000  5.867e-03     34.089 1.083e-254     [  0.188,  0.211]
beta[1]        0.7800  5.049e-03    154.468      0.000     [  0.770,  0.790]
============================================================================

Covariance estimator: robust
Aligned returns for /TRV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TRV: first_obs and last_obs produce in an empty array.
Aligned returns for /TSCO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TSCO: first_obs and last_obs produce in an empty array.
Aligned returns for /TSLA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TSLA: first_obs and last_obs produce in an empty array.
Aligned returns for /TSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TSN: first_obs and last_obs produce in an empty array.
Aligned returns for /TT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TT: first_obs and last_obs produce in an empty array.
Aligned returns for /TTC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TTC: first_obs and last_obs produce in an empty array.
Aligned returns for /TTD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TTD: first_obs and last_obs produce in an empty array.
Aligned returns for /TTEK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TTEK: first_obs and last_obs produce in an empty array.
Aligned returns for /TTWO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TTWO: first_obs and last_obs produce in an empty array.
Aligned returns for /TW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TW: first_obs and last_obs produce in an empty array.
Aligned returns for /TWLO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TWLO: first_obs and last_obs produce in an empty array.
Aligned returns for /TXG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TXG: first_obs and last_obs produce in an empty array.
Aligned returns for /TXN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TXN: first_obs and last_obs produce in an empty array.
Aligned returns for /TXRH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TXRH: first_obs and last_obs produce in an empty array.
Aligned returns for /TXT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TXT: first_obs and last_obs produce in an empty array.
Aligned returns for /TYL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /TYL: first_obs and last_obs produce in an empty array.
Aligned returns for /U:
Date
2001-01-02    0.849112
2001-01-03    0.848493
2001-01-04    0.848119
2001-01-05    0.847221
2001-01-08    0.853650
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.849112  0.0668 -0.0507
2001-01-03  0.848493  0.0668 -0.0507
2001-01-04  0.848119  0.0668 -0.0507
2001-01-05  0.847221  0.0668 -0.0507
2001-01-08  0.853650  0.0668 -0.0507

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.06715. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /U:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                289.354
Distribution:                  Normal   AIC:                          -570.708
Method:            Maximum Likelihood   BIC:                          -554.732
                                        No. Observations:                  401
Date:                Mon, Oct 14 2024   Df Residuals:                      400
Time:                        14:49:33   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.0763  5.428e-04   1982.734      0.000 [  1.075,  1.077]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      7.4359e-06  3.514e-07     21.164  2.060e-99 [6.747e-06,8.125e-06]
alpha[1]       1.0000      0.118      8.504  1.839e-17     [  0.770,  1.230]
beta[1]    2.3960e-14      0.132  1.820e-13      1.000     [ -0.258,  0.258]
============================================================================

Covariance estimator: robust
Aligned returns for /UA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UA: first_obs and last_obs produce in an empty array.
Aligned returns for /UAA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UAA: first_obs and last_obs produce in an empty array.
Aligned returns for /UAL:
Date
2001-01-02    0.443933
2001-01-03    0.445215
2001-01-04    0.449358
2001-01-05    0.450079
2001-01-08    0.451824
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-02  0.443933  0.0668 -0.0507
2001-01-03  0.445215  0.0668 -0.0507
2001-01-04  0.449358  0.0668 -0.0507
2001-01-05  0.450079  0.0668 -0.0507
2001-01-08  0.451824  0.0668 -0.0507
Results for /UAL:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                142.448
Distribution:                  Normal   AIC:                          -276.897
Method:            Maximum Likelihood   BIC:                          -259.564
                                        No. Observations:                  563
Date:                Mon, Oct 14 2024   Df Residuals:                      562
Time:                        14:49:33   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.7966  3.724e-03    213.936      0.000 [  0.789,  0.804]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      3.9841e-04  9.202e-05      4.330  1.493e-05  [2.181e-04,5.788e-04]
alpha[1]       0.7790  2.231e-02     34.919 3.872e-267      [  0.735,  0.823]
beta[1]    2.0635e-05  4.064e-02  5.077e-04      1.000 [-7.964e-02,7.968e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /UBER:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UBER: first_obs and last_obs produce in an empty array.
Aligned returns for /UDR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UDR: first_obs and last_obs produce in an empty array.
Aligned returns for /UGI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UGI: first_obs and last_obs produce in an empty array.
Aligned returns for /UHAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UHAL: first_obs and last_obs produce in an empty array.
Aligned returns for /UHS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UHS: first_obs and last_obs produce in an empty array.
Aligned returns for /UI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UI: first_obs and last_obs produce in an empty array.
Aligned returns for /ULTA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ULTA: first_obs and last_obs produce in an empty array.
Aligned returns for /UNH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UNH: first_obs and last_obs produce in an empty array.
Aligned returns for /UNM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UNM: first_obs and last_obs produce in an empty array.
Aligned returns for /UNP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UNP: first_obs and last_obs produce in an empty array.
Aligned returns for /UPS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UPS: first_obs and last_obs produce in an empty array.
Aligned returns for /URI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /URI: first_obs and last_obs produce in an empty array.
Aligned returns for /USB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /USB: first_obs and last_obs produce in an empty array.
Aligned returns for /USFD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /USFD: first_obs and last_obs produce in an empty array.
Aligned returns for /UTHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UTHR: first_obs and last_obs produce in an empty array.
Aligned returns for /UWMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /UWMC: first_obs and last_obs produce in an empty array.
Aligned returns for /V:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /V: first_obs and last_obs produce in an empty array.
Aligned returns for /VAC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VAC: first_obs and last_obs produce in an empty array.
Aligned returns for /VEEV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VEEV: first_obs and last_obs produce in an empty array.
Aligned returns for /VFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VFC: first_obs and last_obs produce in an empty array.
Aligned returns for /VICI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VICI: first_obs and last_obs produce in an empty array.
Aligned returns for /VIRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VIRT: first_obs and last_obs produce in an empty array.
Aligned returns for /VKTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VKTX: first_obs and last_obs produce in an empty array.
Aligned returns for /VLO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VLO: first_obs and last_obs produce in an empty array.
Aligned returns for /VLTO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VLTO: first_obs and last_obs produce in an empty array.
Aligned returns for /VMC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VMC: first_obs and last_obs produce in an empty array.
Aligned returns for /VMI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VMI: first_obs and last_obs produce in an empty array.
Aligned returns for /VNO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VNO: first_obs and last_obs produce in an empty array.
Aligned returns for /VNOM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VNOM: first_obs and last_obs produce in an empty array.
Aligned returns for /VNT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VNT: first_obs and last_obs produce in an empty array.
Aligned returns for /VOYA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VOYA: first_obs and last_obs produce in an empty array.
Aligned returns for /VRSK:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VRSK: first_obs and last_obs produce in an empty array.
Aligned returns for /VRSN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VRSN: first_obs and last_obs produce in an empty array.
Aligned returns for /VRT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VRT: first_obs and last_obs produce in an empty array.
Aligned returns for /VRTX:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VRTX: first_obs and last_obs produce in an empty array.
Aligned returns for /VST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VST: first_obs and last_obs produce in an empty array.
Aligned returns for /VSTS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VSTS: first_obs and last_obs produce in an empty array.
Aligned returns for /VTR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VTR: first_obs and last_obs produce in an empty array.
Aligned returns for /VTRS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VTRS: first_obs and last_obs produce in an empty array.
Aligned returns for /VVV:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VVV: first_obs and last_obs produce in an empty array.
Aligned returns for /VZ:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /VZ: first_obs and last_obs produce in an empty array.
Aligned returns for /W:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /W: first_obs and last_obs produce in an empty array.
Aligned returns for /WAB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WAB: first_obs and last_obs produce in an empty array.
Aligned returns for /WAL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WAL: first_obs and last_obs produce in an empty array.
Aligned returns for /WAT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WAT: first_obs and last_obs produce in an empty array.
Aligned returns for /WBA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WBA: first_obs and last_obs produce in an empty array.
Aligned returns for /WBD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WBD: first_obs and last_obs produce in an empty array.
Aligned returns for /WBS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WBS: first_obs and last_obs produce in an empty array.
Aligned returns for /WCC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WCC: first_obs and last_obs produce in an empty array.
Aligned returns for /WDAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WDAY: first_obs and last_obs produce in an empty array.
Aligned returns for /WDC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WDC: first_obs and last_obs produce in an empty array.
Aligned returns for /WEC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []

Error fitting GARCH model for /WEC: first_obs and last_obs produce in an empty array.
Aligned returns for /WEN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WEN: first_obs and last_obs produce in an empty array.
Aligned returns for /WEX:
Date
2001-02-05    0.905441
2001-02-08    0.904978
2001-02-12    0.905666
2001-02-13    0.924575
2001-02-14    0.922923
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-02-05  0.905441 -0.0078  0.1247
2001-02-08  0.904978 -0.0078  0.1247
2001-02-12  0.905666 -0.0078  0.1247
2001-02-13  0.924575 -0.0078  0.1247
2001-02-14  0.922923 -0.0078  0.1247
Results for /WEX:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                1248.74
Distribution:                  Normal   AIC:                          -2489.48
Method:            Maximum Likelihood   BIC:                          -2466.12
                                        No. Observations:                 2544
Date:                Mon, Oct 14 2024   Df Residuals:                     2543
Time:                        14:49:34   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.6750  2.209e-03    305.631      0.000 [  0.671,  0.679]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      1.5302e-03  3.888e-05     39.359      0.000 [1.454e-03,1.606e-03]
alpha[1]       0.2000  5.237e-03     38.190      0.000     [  0.190,  0.210]
beta[1]        0.7800  5.136e-03    151.865      0.000     [  0.770,  0.790]
============================================================================

Covariance estimator: robust
Aligned returns for /WFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WFC: first_obs and last_obs produce in an empty array.
Aligned returns for /WFRD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WFRD: first_obs and last_obs produce in an empty array.
Aligned returns for /WH:
Date
2008-12-05    0.870865
2008-12-08    0.870982
2008-12-09    0.867138
2008-12-10    0.866175
2008-12-11    0.866095
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2008-12-05  0.870865  0.0346  0.0014
2008-12-08  0.870982  0.0346  0.0014
2008-12-09  0.867138  0.0346  0.0014
2008-12-10  0.866175  0.0346  0.0014
2008-12-11  0.866095  0.0346  0.0014
Results for /WH:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                554.169
Distribution:                  Normal   AIC:                          -1100.34
Method:            Maximum Likelihood   BIC:                          -1079.22
                                        No. Observations:                 1451
Date:                Mon, Oct 14 2024   Df Residuals:                     1450
Time:                        14:49:34   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.8527  4.244e-03    200.920      0.000 [  0.844,  0.861]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega      3.8157e-03  8.407e-04      4.539  5.653e-06 [2.168e-03,5.463e-03]
alpha[1]       0.1800  2.725e-02      6.605  3.972e-11     [  0.127,  0.233]
beta[1]        0.7020  5.394e-02     13.015  1.011e-38     [  0.596,  0.808]
============================================================================

Covariance estimator: robust
Aligned returns for /WHR:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WHR: first_obs and last_obs produce in an empty array.
Aligned returns for /WING:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WING: first_obs and last_obs produce in an empty array.
Aligned returns for /WLK:
Date
2001-01-03    1.228217
2001-01-04    1.227794
2001-01-05    1.230767
2001-01-08    1.229229
2001-01-09    1.235559
Name: r_vol, dtype: float64
Aligned Fama-French factors:
               r_vol     smb     hml
Date
2001-01-03  1.228217  0.0668 -0.0507
2001-01-04  1.227794  0.0668 -0.0507
2001-01-05  1.230767  0.0668 -0.0507
2001-01-08  1.229229  0.0668 -0.0507
2001-01-09  1.235559  0.0668 -0.0507

/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.07631. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(
/Users/nasruddinislambinramli/anaconda3/lib/python3.11/site-packages/arch/univariate/base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.01861. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 10 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

Results for /WLK:
                     Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                  r_vol   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:                104.287
Distribution:                  Normal   AIC:                          -200.574
Method:            Maximum Likelihood   BIC:                          -191.251
                                        No. Observations:                   76
Date:                Mon, Oct 14 2024   Df Residuals:                       75
Time:                        14:49:34   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             1.5712  8.564e-04   1834.589      0.000 [  1.570,  1.573]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega      1.5027e-05  1.282e-08   1172.432      0.000  [1.500e-05,1.505e-05]
alpha[1]       1.0000  7.888e-02     12.678  7.807e-37      [  0.845,  1.155]
beta[1]        0.0000  1.660e-02      0.000      1.000 [-3.253e-02,3.253e-02]
=============================================================================

Covariance estimator: robust
Aligned returns for /WM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WM: first_obs and last_obs produce in an empty array.
Aligned returns for /WMB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WMB: first_obs and last_obs produce in an empty array.
Aligned returns for /WMS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WMS: first_obs and last_obs produce in an empty array.
Aligned returns for /WMT:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WMT: first_obs and last_obs produce in an empty array.
Aligned returns for /WOLF:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WOLF: first_obs and last_obs produce in an empty array.
Aligned returns for /WPC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WPC: first_obs and last_obs produce in an empty array.
Aligned returns for /WRB:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WRB: first_obs and last_obs produce in an empty array.
Aligned returns for /WSC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WSC: first_obs and last_obs produce in an empty array.
Aligned returns for /WSM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WSM: first_obs and last_obs produce in an empty array.
Aligned returns for /WSO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WSO: first_obs and last_obs produce in an empty array.
Aligned returns for /WST:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WST: first_obs and last_obs produce in an empty array.
Aligned returns for /WTFC:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WTFC: first_obs and last_obs produce in an empty array.
Aligned returns for /WTM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WTM: first_obs and last_obs produce in an empty array.
Aligned returns for /WTRG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WTRG: first_obs and last_obs produce in an empty array.
Aligned returns for /WTW:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WTW: first_obs and last_obs produce in an empty array.
Aligned returns for /WU:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WU: first_obs and last_obs produce in an empty array.
Aligned returns for /WWD:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WWD: first_obs and last_obs produce in an empty array.
Aligned returns for /WY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WY: first_obs and last_obs produce in an empty array.
Aligned returns for /WYNN:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /WYNN: first_obs and last_obs produce in an empty array.
Aligned returns for /X:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /X: first_obs and last_obs produce in an empty array.
Aligned returns for /XEL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /XEL: first_obs and last_obs produce in an empty array.
Aligned returns for /XOM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /XOM: first_obs and last_obs produce in an empty array.
Aligned returns for /XP:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /XP: first_obs and last_obs produce in an empty array.
Aligned returns for /XPO:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /XPO: first_obs and last_obs produce in an empty array.
Aligned returns for /XRAY:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /XRAY: first_obs and last_obs produce in an empty array.
Aligned returns for /XYL:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /XYL: first_obs and last_obs produce in an empty array.
Aligned returns for /YETI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /YETI: first_obs and last_obs produce in an empty array.
Aligned returns for /YUM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /YUM: first_obs and last_obs produce in an empty array.
Aligned returns for /Z:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /Z: first_obs and last_obs produce in an empty array.
Aligned returns for /ZBH:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZBH: first_obs and last_obs produce in an empty array.
Aligned returns for /ZBRA:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZBRA: first_obs and last_obs produce in an empty array.
Aligned returns for /ZG:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZG: first_obs and last_obs produce in an empty array.
Aligned returns for /ZI:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZI: first_obs and last_obs produce in an empty array.
Aligned returns for /ZION:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZION: first_obs and last_obs produce in an empty array.
Aligned returns for /ZM:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZM: first_obs and last_obs produce in an empty array.
Aligned returns for /ZS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZS: first_obs and last_obs produce in an empty array.
Aligned returns for /ZTS:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /ZTS: first_obs and last_obs produce in an empty array.
Aligned returns for /BRK/B:
Series([], Name: r_vol, dtype: float64)
Aligned Fama-French factors:
Empty DataFrame
Columns: [r_vol, smb, hml]
Index: []
Error fitting GARCH model for /BRK/B: first_obs and last_obs produce in an empty array.