In [26]:
lib = db.list_libraries()
crsp = [x for x in lib if 'crsp' in x]
# print(crsp)
tables = db.list_tables(library='crsp_a_stock')
print(db.describe_table(library='crsp_a_stock', table='dsf'))
print('---')
print(db.describe_table(library='crsp_a_stock', table='dsedelist'))
print('---')
print(db.describe_table(library='crsp_a_stock', table='dse'))
print('---')
# print(tables)

Approximately 105258384 rows in crsp_a_stock.dsf.
       name  nullable              type  \
0     cusip      True        VARCHAR(8)
1    permno      True           INTEGER
2    permco      True           INTEGER
3    issuno      True           INTEGER
4     hexcd      True          SMALLINT
5    hsiccd      True           INTEGER
6      date      True              DATE
7     bidlo      True    NUMERIC(11, 5)
8     askhi      True    NUMERIC(11, 5)
9       prc      True    NUMERIC(11, 5)
10      vol      True    NUMERIC(10, 0)
11      ret      True    NUMERIC(10, 6)
12      bid      True    NUMERIC(11, 5)
13      ask      True    NUMERIC(11, 5)
14   shrout      True  DOUBLE PRECISION
15   cfacpr      True  DOUBLE PRECISION
16  cfacshr      True  DOUBLE PRECISION
17  openprc      True    NUMERIC(11, 5)
18   numtrd      True           INTEGER
19     retx      True    NUMERIC(10, 6)

                                    comment
0                              CUSIP Header
1                 Permanent Security Number
2                  Permanent Company Number
3                       Nasdaq Issue Number
4                      Exchange Code Header
5   Standard Industrial Classification Code
6                       Date of Observation
7                          Bid or Low Price
8                         Ask or High Price
9                  Price or Bid/Ask Average
10                                   Volume
11                                  Returns
12                                      Bid
13                                      Ask
14                       Shares Outstanding
15       Cumulative Factor to Adjust Prices
16   Cumulative Factor to Adjust Shares/Vol
17                          Price Alternate
18                         Number of Trades
19                Returns without Dividends
---
Approximately 37776 rows in crsp_a_stock.dsedelist.
      name  nullable              type  \
0   permno      True           INTEGER
1   dlstdt      True              DATE
2   dlstcd      True          SMALLINT
3   nwperm      True           INTEGER
4   nwcomp      True           INTEGER
5   nextdt      True              DATE
6    dlamt      True    NUMERIC(11, 5)
7   dlretx      True    NUMERIC(10, 6)
8    dlprc      True    NUMERIC(11, 5)
9    dlpdt      True              DATE
10   dlret      True    NUMERIC(10, 6)
11  permco      True           INTEGER
12  compno      True           INTEGER
13  issuno      True           INTEGER
14   hexcd      True          SMALLINT
15  hsiccd      True           INTEGER
16   cusip      True        VARCHAR(8)
17  acperm      True  DOUBLE PRECISION
18  accomp      True  DOUBLE PRECISION

                                    comment
0                                    PERMNO
1                            Delisting Date
2                            Delisting Code
3                                New PERMNO
4                                New PERMCO
5                 Delisting Next Price Date
6                          Delisting Amount
7        Delisting Return Without Dividends
8                           Delisting Price
9                     Delisting Amount Date
10                         Delisting Return
11                                   PERMCO
12                    Nasdaq Company Number
13                      Nasdaq Issue Number
14                     Exchange Code Header
15  Standard Industrial Classification Code
16                             CUSIP Header
17                                     None
18                                     None
---
Approximately 12648999 rows in crsp_a_stock.dse.
        name  nullable              type  \
0      event      True        VARCHAR(8)
1       date      True              DATE
2     hsicmg      True  DOUBLE PRECISION
3     hsicig      True  DOUBLE PRECISION
4     comnam      True       VARCHAR(32)
5      cusip      True        VARCHAR(8)
6     dclrdt      True              DATE
7      dlamt      True    NUMERIC(11, 5)
8      dlpdt      True              DATE
9     dlstcd      True          SMALLINT
10    hsiccd      True           INTEGER
11    issuno      True           INTEGER
12    ncusip      True        VARCHAR(8)
13    nextdt      True              DATE
14     paydt      True              DATE
15    rcrddt      True              DATE
16    shrcls      True        VARCHAR(1)
17    shrflg      True          SMALLINT
18    ticker      True        VARCHAR(5)
19    permno      True           INTEGER
20  nameendt      True              DATE
21     shrcd      True          SMALLINT
22    exchcd      True          SMALLINT
23     siccd      True           INTEGER
24   tsymbol      True       VARCHAR(10)
25     naics      True        VARCHAR(7)
26  primexch      True        VARCHAR(1)
27   trdstat      True        VARCHAR(1)
28   secstat      True        VARCHAR(1)
29    permco      True           INTEGER
30    compno      True           INTEGER
31     hexcd      True          SMALLINT
32    distcd      True          SMALLINT
33    divamt      True    NUMERIC(11, 5)
34     facpr      True    NUMERIC(10, 5)
35    facshr      True    NUMERIC(10, 5)
36    acperm      True           INTEGER
37    accomp      True           INTEGER
38    nwperm      True           INTEGER
39    nwcomp      True           INTEGER
40    dlretx      True    NUMERIC(10, 6)
41     dlprc      True    NUMERIC(11, 5)
42     dlret      True    NUMERIC(10, 6)
43    shrout      True    NUMERIC(10, 0)
44  shrenddt      True              DATE
45    trtscd      True          SMALLINT
46  trtsendt      True              DATE
47    nmsind      True          SMALLINT
48     mmcnt      True          SMALLINT
49    nsdinx      True          SMALLINT

                                              comment
0                                          Event Name
1   Date of Observation. NAMEDT of NAMES events; e...
2                              Header SIC Major Gorup
3                           Header SIC Industry Group
4                                        Company Name
5                                    CUSIP Identifier
6                                    Declaration Date
7                              Amount After Delisting
8                           Date of Delisting Payment
9                                      Delisting Code
10                                     Header SIC Cde
11                            Nasdaq Issue Identifier
12                                        Names CUSIP
13                 Date of Next Available Information
14                                       Payment Date
15                                        Record Date
16                                        Share Class
17                       Number of Shares Outstanding
18                             Exchange Ticker Symbol
19                                             PERMNO
20                                  Names Ending Date
21                                         Share Code
22                                      Exchange Code
23            Standard Industrial Classification Code
24                                     Trading Symbol
25      North American Industry Classification System
26                                   Primary Exchange
27                                     Trading Status
28                                    Security Status
29                                             PERMCO
30                              Nasdaq Company Number
31                               Exchange Code Header
32                                  Distribution Code
33                               Dividend Cash Amount
34                             Factor to Adjust Price
35                            Factor to Adjust Shares
36                                   Acquiring PERMNO
37                                   Acquiring PERMCO
38                                         New PERMNO
39                                         New PERMCO
40                 Delisting Return Without Dividends
41                                    Delisting Price
42                                   Delisting Return
43                                 Shares Outstanding
44                        Shares Observation End Date
45                                 Nasdaq Traits Code
46                             Nasdaq Traits End Date
47                   Nasdaq National Market Indicator
48                                 Market Maker Count
49                                    Nasd Index Code
---

In [52]:
# import wrds
# import pandas as pd
# db = wrds.Connection()

# tickers_df = pd.read_excel("RIY Index Constituents.xlsx")
# unique_tickers = set()
# cols = tickers_df.columns
# for col in cols:
#     tickers_for_year = tickers_df[col].unique()
#     for ticker in tickers_for_year:
#         unique_tickers.add(ticker.split()[0].strip().upper())
# print(f"Unique tickers: {len(unique_tickers)}")

# count = 0
# with pd.HDFStore("all_tickers_time_series.hf5") as store:
#     for ticker in unique_tickers:
#         data = db.raw_sql(f"""
#             SELECT 
#                 c.ticker,
#                 a.date,
#                 a.openprc,
#                 a.askhi,
#                 a.bidlo,
#                 a.prc,
#                 a.vol,
#                 b.dlstdt,
#                 b.dlstcd,
#                 b.nextdt,
#                 b.dlprc
#             FROM crsp_a_stock.dsf a
#             JOIN crsp_a_stock.dsedelist b ON a.permno = b.permno
#             JOIN crsp_a_stock.dse c ON a.permno = c.permno
#             WHERE c.ticker = '{ticker}'
#             AND a.date >= '2000-01-01'
#         """, date_cols=["date", "dlstdt", "nextdt"])
#         data["ticker"] = data["ticker"].astype("category")
#         store.put(ticker, data, format="table")
#         count += 1
#         print(f"Stored {ticker}, count: {count}")

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done
Unique tickers: 1009
Stored WSO, count: 1
Stored JLL, count: 2
Stored FNF, count: 3
Stored LH, count: 4
Stored VTRS, count: 5
Stored IT, count: 6
Stored LINE, count: 7
Stored DLTR, count: 8
Stored HEI/A, count: 9
Stored RGLD, count: 10
Stored KLAC, count: 11
Stored RGA, count: 12
Stored CPT, count: 13
Stored PK, count: 14
Stored DOCU, count: 15
Stored MEDP, count: 16
Stored STWD, count: 17
Stored SUI, count: 18
Stored OHI, count: 19
Stored TSCO, count: 20
Stored BEN, count: 21
Stored PLD, count: 22
Stored LYB, count: 23
Stored CMI, count: 24
Stored LUV, count: 25
Stored DAR, count: 26
Stored DXCM, count: 27
Stored DOV, count: 28
Stored HES, count: 29
Stored LYV, count: 30
Stored ROKU, count: 31
Stored SYY, count: 32
Stored UNP, count: 33
Stored REGN, count: 34
Stored ANSS, count: 35
Stored PEGA, count: 36
Stored HUN, count: 37
Stored DLR, count: 38
Stored CART, count: 39
Stored OVV, count: 40
Stored BOKF, count: 41
Stored FSLR, count: 42
Stored BYD, count: 43
Stored RBC, count: 44
Stored SBAC, count: 45
Stored ZTS, count: 46
Stored LPX, count: 47
Stored AMAT, count: 48
Stored SOFI, count: 49
Stored SNDR, count: 50
Stored DAY, count: 51
Stored MDU, count: 52
Stored TDC, count: 53
Stored EXPD, count: 54
Stored UHAL/B, count: 55
Stored VFC, count: 56
Stored WDAY, count: 57
Stored X, count: 58
Stored EEFT, count: 59
Stored EQH, count: 60
Stored ZS, count: 61
Stored VLO, count: 62
Stored TECH, count: 63
Stored MRO, count: 64
Stored LDOS, count: 65
Stored PFG, count: 66
Stored BG, count: 67
Stored CL, count: 68
Stored CMA, count: 69
Stored NOW, count: 70
Stored TEAM, count: 71
Stored ORLY, count: 72
Stored BRK/B, count: 73
Stored EMN, count: 74
Stored V, count: 75
Stored AMGN, count: 76
Stored VTR, count: 77
Stored HD, count: 78
Stored XRAY, count: 79
Stored GEN, count: 80
Stored MSA, count: 81
Stored EOG, count: 82
Stored KIM, count: 83
Stored HLI, count: 84
Stored INTU, count: 85
Stored HUBB, count: 86
Stored OLED, count: 87
Stored AEP, count: 88
Stored FNB, count: 89
Stored MNST, count: 90
Stored THO, count: 91
Stored USFD, count: 92
Stored XP, count: 93
Stored CFR, count: 94
Stored EWBC, count: 95
Stored SAM, count: 96
Stored AGCO, count: 97
Stored GWRE, count: 98
Stored NKE, count: 99
Stored LLY, count: 100
Stored DTM, count: 101
Stored WEN, count: 102
Stored EXP, count: 103
Stored NWS, count: 104
Stored AWK, count: 105
Stored RHI, count: 106
Stored SNOW, count: 107
Stored ATO, count: 108
Stored CRL, count: 109
Stored EXAS, count: 110
Stored KVUE, count: 111
Stored REXR, count: 112
Stored HIW, count: 113
Stored IPGP, count: 114
Stored GEV, count: 115
Stored PRGO, count: 116
Stored CBRE, count: 117
Stored UPS, count: 118
Stored SNV, count: 119
Stored ENPH, count: 120
Stored NTRA, count: 121
Stored O, count: 122
Stored CNA, count: 123
Stored MMM, count: 124
Stored TTWO, count: 125
Stored FTNT, count: 126
Stored CRWD, count: 127
Stored PENN, count: 128
Stored NSA, count: 129
Stored FERG, count: 130
Stored TJX, count: 131
Stored CMCSA, count: 132
Stored SEE, count: 133
Stored TMO, count: 134
Stored F, count: 135
Stored ILMN, count: 136
Stored ITT, count: 137
Stored CBOE, count: 138
Stored VNOM, count: 139
Stored MTDR, count: 140
Stored AIZ, count: 141
Stored CEG, count: 142
Stored DV, count: 143
Stored FLS, count: 144
Stored MSTR, count: 145
Stored COST, count: 146
Stored CNXC, count: 147
Stored ZBH, count: 148
Stored LYFT, count: 149
Stored FTV, count: 150
Stored ADP, count: 151
Stored LEG, count: 152
Stored PANW, count: 153
Stored WST, count: 154
Stored EXC, count: 155
Stored STZ, count: 156
Stored GOOG, count: 157
Stored LCID, count: 158
Stored AGO, count: 159
Stored BROS, count: 160
Stored OC, count: 161
Stored PB, count: 162
Stored RH, count: 163
Stored BSY, count: 164
Stored FRPT, count: 165
Stored APLS, count: 166
Stored WAL, count: 167
Stored WRB, count: 168
Stored GGG, count: 169
Stored ATI, count: 170
Stored CRBG, count: 171
Stored LEN/B, count: 172
Stored PII, count: 173
Stored GLPI, count: 174
Stored MSCI, count: 175
Stored MAT, count: 176
Stored CSGP, count: 177
Stored EG, count: 178
Stored IBKR, count: 179
Stored JCI, count: 180
Stored NUE, count: 181
Stored NVDA, count: 182
Stored BIO, count: 183
Stored SMAR, count: 184
Stored RMD, count: 185
Stored TSLA, count: 186
Stored ACI, count: 187
Stored BRO, count: 188
Stored CRM, count: 189
Stored MRK, count: 190
Stored DFS, count: 191
Stored LSTR, count: 192
Stored PEN, count: 193
Stored GTES, count: 194
Stored REG, count: 195
Stored UHS, count: 196
Stored EVR, count: 197
Stored PEG, count: 198
Stored COP, count: 199
Stored CBSH, count: 200
Stored WTM, count: 201
Stored ACGL, count: 202
Stored FAST, count: 203
Stored MCO, count: 204
Stored SOLV, count: 205
Stored VAC, count: 206
Stored LRCX, count: 207
Stored HOG, count: 208
Stored ARW, count: 209
Stored RTX, count: 210
Stored AON, count: 211
Stored FIS, count: 212
Stored T, count: 213
Stored WFC, count: 214
Stored PCG, count: 215
Stored GLW, count: 216
Stored LOPE, count: 217
Stored ISRG, count: 218
Stored BAC, count: 219
Stored HIG, count: 220
Stored EVRG, count: 221
Stored NDSN, count: 222
Stored S, count: 223
Stored AXTA, count: 224
Stored HAL, count: 225
Stored CAG, count: 226
Stored PPG, count: 227
Stored SCI, count: 228
Stored STE, count: 229
Stored FOXA, count: 230
Stored APP, count: 231
Stored GM, count: 232
Stored WAT, count: 233
Stored PYPL, count: 234
Stored GRMN, count: 235
Stored MA, count: 236
Stored HRL, count: 237
Stored LPLA, count: 238
Stored RCM, count: 239
Stored WBS, count: 240
Stored SPB, count: 241
Stored PYCR, count: 242
Stored ALAB, count: 243
Stored AZPN, count: 244
Stored NFG, count: 245
Stored AMG, count: 246
Stored TT, count: 247
Stored WU, count: 248
Stored BC, count: 249
Stored OMC, count: 250
Stored WSC, count: 251
Stored ELS, count: 252
Stored MP, count: 253
Stored REYN, count: 254
Stored FTRE, count: 255
Stored IR, count: 256
Stored CGNX, count: 257
Stored NYT, count: 258
Stored SQ, count: 259
Stored SSNC, count: 260
Stored DNB, count: 261
Stored EQT, count: 262
Stored PNR, count: 263
Stored SLGN, count: 264
Stored SYF, count: 265
Stored ZM, count: 266
Stored NLY, count: 267
Stored UNH, count: 268
Stored MPC, count: 269
Stored HPQ, count: 270
Stored VKTX, count: 271
Stored LITE, count: 272
Stored DELL, count: 273
Stored AXON, count: 274
Stored CHRW, count: 275
Stored PLTR, count: 276
Stored AOS, count: 277
Stored OKE, count: 278
Stored BRKR, count: 279
Stored TPL, count: 280
Stored DOW, count: 281
Stored SCHW, count: 282
Stored COTY, count: 283
Stored ELF, count: 284
Stored APD, count: 285
Stored GPN, count: 286
Stored QCOM, count: 287
Stored SLM, count: 288
Stored RIVN, count: 289
Stored ABNB, count: 290
Stored PATH, count: 291
Stored TRU, count: 292
Stored UTHR, count: 293
Stored BF/B, count: 294
Stored CPB, count: 295
Stored MAR, count: 296
Stored SLB, count: 297
Stored QDEL, count: 298
Stored AAP, count: 299
Stored ACHC, count: 300
Stored WY, count: 301
Stored WTRG, count: 302
Stored CVNA, count: 303
Stored NDAQ, count: 304
Stored KBR, count: 305
Stored PNFP, count: 306
Stored BDX, count: 307
Stored ELV, count: 308
Stored MET, count: 309
Stored DTE, count: 310
Stored DVN, count: 311
Stored SEG, count: 312
Stored QS, count: 313
Stored AMT, count: 314
Stored TDG, count: 315
Stored GXO, count: 316
Stored XYL, count: 317
Stored ZBRA, count: 318
Stored AA, count: 319
Stored FIX, count: 320
Stored FITB, count: 321
Stored BRBR, count: 322
Stored AZO, count: 323
Stored CTSH, count: 324
Stored QGEN, count: 325
Stored WWD, count: 326
Stored SEIC, count: 327
Stored ALL, count: 328
Stored MSFT, count: 329
Stored CNH, count: 330
Stored GD, count: 331
Stored C, count: 332
Stored JBHT, count: 333
Stored LLYVA, count: 334
Stored EA, count: 335
Stored ADBE, count: 336
Stored SPOT, count: 337
Stored POST, count: 338
Stored LNT, count: 339
Stored MPWR, count: 340
Stored ALK, count: 341
Stored AYI, count: 342
Stored HHH, count: 343
Stored PNW, count: 344
Stored TRGP, count: 345
Stored DINO, count: 346
Stored NCNO, count: 347
Stored SWKS, count: 348
Stored FYBR, count: 349
Stored HON, count: 350
Stored JEF, count: 351
Stored BIRK, count: 352
Stored IDXX, count: 353
Stored BBY, count: 354
Stored AXS, count: 355
Stored ASH, count: 356
Stored GTLB, count: 357
Stored CCI, count: 358
Stored PEP, count: 359
Stored SBUX, count: 360
Stored BFAM, count: 361
Stored RS, count: 362
Stored DIS, count: 363
Stored PCOR, count: 364
Stored ESTC, count: 365
Stored HAYW, count: 366
Stored WM, count: 367
Stored AR, count: 368
Stored CAVA, count: 369
Stored SN, count: 370
Stored UHAL, count: 371
Stored FCNCA, count: 372
Stored KHC, count: 373
Stored NU, count: 374
Stored VLTO, count: 375
Stored ODFL, count: 376
Stored ORI, count: 377
Stored ETN, count: 378
Stored DPZ, count: 379
Stored CFLT, count: 380
Stored MSI, count: 381
Stored LNG, count: 382
Stored PVH, count: 383
Stored MS, count: 384
Stored R, count: 385
Stored NTAP, count: 386
Stored INFA, count: 387
Stored VNO, count: 388
Stored NTRS, count: 389
Stored DKS, count: 390
Stored VNT, count: 391
Stored BLD, count: 392
Stored EXPE, count: 393
Stored BRX, count: 394
Stored FIVE, count: 395
Stored INVH, count: 396
Stored NXST, count: 397
Stored PINC, count: 398
Stored AL, count: 399
Stored WYNN, count: 400
Stored YETI, count: 401
Stored TXG, count: 402
Stored TKO, count: 403
Stored CB, count: 404
Stored CRH, count: 405
Stored GPK, count: 406
Stored OXY, count: 407
Stored POOL, count: 408
Stored RPRX, count: 409
Stored KMI, count: 410
Stored ARES, count: 411
Stored BK, count: 412
Stored AKAM, count: 413
Stored BALL, count: 414
Stored CMS, count: 415
Stored EQIX, count: 416
Stored SPGI, count: 417
Stored FBIN, count: 418
Stored VMI, count: 419
Stored WMS, count: 420
Stored DJT, count: 421
Stored CE, count: 422
Stored LW, count: 423
Stored MOH, count: 424
Stored HSY, count: 425
Stored LKQ, count: 426
Stored ABT, count: 427
Stored CRI, count: 428
Stored MANH, count: 429
Stored G, count: 430
Stored DKNG, count: 431
Stored ACN, count: 432
Stored SRPT, count: 433
Stored TTEK, count: 434
Stored ORCL, count: 435
Stored AMD, count: 436
Stored DRI, count: 437
Stored AGR, count: 438
Stored TDY, count: 439
Stored ROST, count: 440
Stored HBAN, count: 441
Stored RVTY, count: 442
Stored INCY, count: 443
Stored MMC, count: 444
Stored APA, count: 445
Stored ETR, count: 446
Stored ED, count: 447
Stored TYL, count: 448
Stored ECL, count: 449
Stored ANET, count: 450
Stored IPG, count: 451
Stored PLTK, count: 452
Stored PWR, count: 453
Stored ROK, count: 454
Stored UNM, count: 455
Stored VRTX, count: 456
Stored WCC, count: 457
Stored CG, count: 458
Stored DASH, count: 459
Stored DE, count: 460
Stored COLM, count: 461
Stored MRNA, count: 462
Stored OLLI, count: 463
Stored DVA, count: 464
Stored CWEN/A, count: 465
Stored GLOB, count: 466
Stored WMT, count: 467
Stored KR, count: 468
Stored CC, count: 469
Stored H, count: 470
Stored ADM, count: 471
Stored KDP, count: 472
Stored AWI, count: 473
Stored SSD, count: 474
Stored JBL, count: 475
Stored PAYX, count: 476
Stored IQV, count: 477
Stored SCCO, count: 478
Stored APTV, count: 479
Stored AS, count: 480
Stored BERY, count: 481
Stored OGE, count: 482
Stored EXR, count: 483
Stored HUM, count: 484
Stored TOST, count: 485
Stored CDW, count: 486
Stored HR, count: 487
Stored CLH, count: 488
Stored GNRC, count: 489
Stored U, count: 490
Stored GME, count: 491
Stored HAS, count: 492
Stored NEM, count: 493
Stored PSN, count: 494
Stored NCLH, count: 495
Stored HWM, count: 496
Stored M, count: 497
Stored NTNX, count: 498
Stored CLF, count: 499
Stored DOCS, count: 500
Stored DOC, count: 501
Stored IP, count: 502
Stored BAH, count: 503
Stored EPR, count: 504
Stored JWN, count: 505
Stored TTD, count: 506
Stored GRAL, count: 507
Stored VIRT, count: 508
Stored AZEK, count: 509
Stored ELAN, count: 510
Stored CAR, count: 511
Stored ETSY, count: 512
Stored PSA, count: 513
Stored MKL, count: 514
Stored MDB, count: 515
Stored ITW, count: 516
Stored PRI, count: 517
Stored PG, count: 518
Stored ROL, count: 519
Stored SON, count: 520
Stored GIS, count: 521
Stored DHI, count: 522
Stored QRVO, count: 523
Stored KEY, count: 524
Stored DDS, count: 525
Stored FCX, count: 526
Stored CSCO, count: 527
Stored CAT, count: 528
Stored CCCS, count: 529
Stored CHE, count: 530
Stored HOLX, count: 531
Stored ONTO, count: 532
Stored TXRH, count: 533
Stored RARE, count: 534
Stored VOYA, count: 535
Stored FI, count: 536
Stored JPM, count: 537
Stored CCL, count: 538
Stored SKX, count: 539
Stored PH, count: 540
Stored APO, count: 541
Stored COLD, count: 542
Stored WBD, count: 543
Stored LMT, count: 544
Stored OMF, count: 545
Stored CROX, count: 546
Stored BILL, count: 547
Stored K, count: 548
Stored MAS, count: 549
Stored XPO, count: 550
Stored CLVT, count: 551
Stored CASY, count: 552
Stored GPC, count: 553
Stored PHM, count: 554
Stored SPG, count: 555
Stored PPC, count: 556
Stored AMZN, count: 557
Stored GILD, count: 558
Stored SITE, count: 559
Stored RNR, count: 560
Stored ES, count: 561
Stored WTW, count: 562
Stored AIG, count: 563
Stored RBA, count: 564
Stored TPX, count: 565
Stored BJ, count: 566
Stored ICE, count: 567
Stored TSN, count: 568
Stored BX, count: 569
Stored EIX, count: 570
Stored PAG, count: 571
Stored YUM, count: 572
Stored PR, count: 573
Stored FHN, count: 574
Stored JKHY, count: 575
Stored PM, count: 576
Stored STT, count: 577
Stored IONS, count: 578
Stored AEE, count: 579
Stored PPL, count: 580
Stored EW, count: 581
Stored VEEV, count: 582
Stored VRSK, count: 583
Stored ZION, count: 584
Stored CI, count: 585
Stored ROP, count: 586
Stored GO, count: 587
Stored NOC, count: 588
Stored PCAR, count: 589
Stored BMY, count: 590
Stored FE, count: 591
Stored BWA, count: 592
Stored ABBV, count: 593
Stored SIRI, count: 594
Stored VRT, count: 595
Stored ADT, count: 596
Stored IBM, count: 597
Stored FICO, count: 598
Stored GWW, count: 599
Stored RBLX, count: 600
Stored BAX, count: 601
Stored AVT, count: 602
Stored LLYVK, count: 603
Stored IRM, count: 604
Stored FANG, count: 605
Stored EHC, count: 606
Stored ROIV, count: 607
Stored SO, count: 608
Stored CPNG, count: 609
Stored MTB, count: 610
Stored MGM, count: 611
Stored WEC, count: 612
Stored EBAY, count: 613
Stored NEE, count: 614
Stored AMP, count: 615
Stored CSX, count: 616
Stored HCP, count: 617
Stored HSIC, count: 618
Stored NFLX, count: 619
Stored OSK, count: 620
Stored ALB, count: 621
Stored TRIP, count: 622
Stored CCK, count: 623
Stored AZTA, count: 624
Stored AJG, count: 625
Stored MCHP, count: 626
Stored UI, count: 627
Stored UAL, count: 628
Stored CTLT, count: 629
Stored IFF, count: 630
Stored DUK, count: 631
Stored PNC, count: 632
Stored GFS, count: 633
Stored NRG, count: 634
Stored NOV, count: 635
Stored SRE, count: 636
Stored MTD, count: 637
Stored CTVA, count: 638
Stored FHB, count: 639
Stored GOOGL, count: 640
Stored OGN, count: 641
Stored AFL, count: 642
Stored MCD, count: 643
Stored PFE, count: 644
Stored WPC, count: 645
Stored MUSA, count: 646
Stored OKTA, count: 647
Stored SHC, count: 648
Stored BF/A, count: 649
Stored APG, count: 650
Stored COKE, count: 651
Stored INTC, count: 652
Stored PTC, count: 653
Stored VZ, count: 654
Stored COLB, count: 655
Stored TOL, count: 656
Stored CERT, count: 657
Stored HUBS, count: 658
Stored WING, count: 659
Stored LNC, count: 660
Stored DCI, count: 661
Stored CIEN, count: 662
Stored AES, count: 663
Stored EME, count: 664
Stored CF, count: 665
Stored GL, count: 666
Stored GNTX, count: 667
Stored MKC, count: 668
Stored BLK, count: 669
Stored ULTA, count: 670
Stored CHDN, count: 671
Stored FAF, count: 672
Stored IEX, count: 673
Stored URI, count: 674
Stored UAA, count: 675
Stored TPR, count: 676
Stored TRV, count: 677
Stored TKR, count: 678
Stored GAP, count: 679
Stored CARR, count: 680
Stored CPRI, count: 681
Stored CUZ, count: 682
Stored ON, count: 683
Stored EQR, count: 684
Stored VST, count: 685
Stored CHTR, count: 686
Stored EPAM, count: 687
Stored TRMB, count: 688
Stored HST, count: 689
Stored PODD, count: 690
Stored EMR, count: 691
Stored HXL, count: 692
Stored WDC, count: 693
Stored CXT, count: 694
Stored KMB, count: 695
Stored BR, count: 696
Stored NET, count: 697
Stored KRC, count: 698
Stored AFRM, count: 699
Stored LULU, count: 700
Stored WMB, count: 701
Stored BPOP, count: 702
Stored FTI, count: 703
Stored LBTYK, count: 704
Stored CZR, count: 705
Stored ZI, count: 706
Stored SEB, count: 707
Stored SWK, count: 708
Stored ESI, count: 709
Stored CUBE, count: 710
Stored TW, count: 711
Stored UDR, count: 712
Stored SW, count: 713
Stored CMG, count: 714
Stored NNN, count: 715
Stored ALSN, count: 716
Stored NVR, count: 717
Stored MDLZ, count: 718
Stored EGP, count: 719
Stored PARA, count: 720
Stored XEL, count: 721
Stored HEI, count: 722
Stored BLDR, count: 723
Stored APPF, count: 724
Stored COF, count: 725
Stored NSC, count: 726
Stored LBRDK, count: 727
Stored KO, count: 728
Stored PAYC, count: 729
Stored BSX, count: 730
Stored CDNS, count: 731
Stored RYN, count: 732
Stored W, count: 733
Stored CACI, count: 734
Stored GE, count: 735
Stored AMH, count: 736
Stored CIVI, count: 737
Stored LIN, count: 738
Stored AM, count: 739
Stored ACM, count: 740
Stored MOS, count: 741
Stored MSM, count: 742
Stored AVGO, count: 743
Stored STLD, count: 744
Stored LAZ, count: 745
Stored GMED, count: 746
Stored SMCI, count: 747
Stored WTFC, count: 748
Stored BEPC, count: 749
Stored KEYS, count: 750
Stored INGR, count: 751
Stored VICI, count: 752
Stored UWMC, count: 753
Stored OLN, count: 754
Stored JAZZ, count: 755
Stored SNA, count: 756
Stored TER, count: 757
Stored INSP, count: 758
Stored SPR, count: 759
Stored GS, count: 760
Stored DECK, count: 761
Stored CINF, count: 762
Stored SRCL, count: 763
Stored TGT, count: 764
Stored WLK, count: 765
Stored BA, count: 766
Stored ZG, count: 767
Stored ENTG, count: 768
Stored L, count: 769
Stored Z, count: 770
Stored AMED, count: 771
Stored ESAB, count: 772
Stored AVB, count: 773
Stored MHK, count: 774
Stored RL, count: 775
Stored HCA, count: 776
Stored OWL, count: 777
Stored RYAN, count: 778
Stored ALGM, count: 779
Stored MTSI, count: 780
Stored RITM, count: 781
Stored AAPL, count: 782
Stored J, count: 783
Stored MTG, count: 784
Stored MU, count: 785
Stored TNL, count: 786
Stored UA, count: 787
Stored VRSN, count: 788
Stored EFX, count: 789
Stored VSTS, count: 790
Stored DLB, count: 791
Stored DHR, count: 792
Stored AMCR, count: 793
Stored FIVN, count: 794
Stored HPE, count: 795
Stored SMG, count: 796
Stored AAL, count: 797
Stored DDOG, count: 798
Stored MIDD, count: 799
Stored LEN, count: 800
Stored DBX, count: 801
Stored LOW, count: 802
Stored AVY, count: 803
Stored DD, count: 804
Stored THG, count: 805
Stored CNM, count: 806
Stored RSG, count: 807
Stored KMPR, count: 808
Stored NWL, count: 809
Stored RRC, count: 810
Stored WAB, count: 811
Stored DAL, count: 812
Stored CHD, count: 813
Stored AME, count: 814
Stored COIN, count: 815
Stored SYK, count: 816
Stored RF, count: 817
Stored RKT, count: 818
Stored RLI, count: 819
Stored CNP, count: 820
Stored MAA, count: 821
Stored PRU, count: 822
Stored NEU, count: 823
Stored ALLY, count: 824
Stored ALNY, count: 825
Stored SAIC, count: 826
Stored IDA, count: 827
Stored LBTYA, count: 828
Stored SNX, count: 829
Stored CRUS, count: 830
Stored TROW, count: 831
Stored NVST, count: 832
Stored APH, count: 833
Stored CTRA, count: 834
Stored AMKR, count: 835
Stored CHH, count: 836
Stored RGEN, count: 837
Stored CR, count: 838
Stored VVV, count: 839
Stored CVS, count: 840
Stored LVS, count: 841
Stored PGR, count: 842
Stored RPM, count: 843
Stored COO, count: 844
Stored CWEN, count: 845
Stored TFX, count: 846
Stored PSX, count: 847
Stored XOM, count: 848
Stored OZK, count: 849
Stored FDX, count: 850
Stored TXT, count: 851
Stored CFG, count: 852
Stored FND, count: 853
Stored CNC, count: 854
Stored FDS, count: 855

In [54]:
with pd.HDFStore("all_tickers_time_series.hf5") as store:
    df_aapl = store['AAPL']  # Load specific ticker's data

df_aapl

,ticker,date,openprc,askhi,bidlo,prc,vol,dlstdt,dlstcd,nextdt,dlprc
0,AAPL,2000-01-03,104.87500,112.50000,101.68750,111.93750,4833736.0,2023-12-29,100,NaT,0.0
1,AAPL,2000-01-04,108.25000,110.62500,101.18750,102.50000,4646120.0,2023-12-29,100,NaT,0.0
2,AAPL,2000-01-05,103.75000,110.56250,103.00000,104.00000,7060334.0,2023-12-29,100,NaT,0.0
3,AAPL,2000-01-06,106.12500,107.00000,95.00000,95.00000,6917851.0,2023-12-29,100,NaT,0.0
4,AAPL,2000-01-07,96.50000,101.00000,95.50000,99.50000,4180715.0,2023-12-29,100,NaT,0.0
...,...,...,...,...,...,...,...,...,...,...,...
30180,AAPL,2023-12-22,195.17999,195.41000,192.97000,193.60001,36702455.0,2023-12-29,100,NaT,0.0
30181,AAPL,2023-12-26,193.61000,193.89000,192.83000,193.05000,28541150.0,2023-12-29,100,NaT,0.0
30182,AAPL,2023-12-27,192.49001,193.50000,191.09000,193.14999,47538658.0,2023-12-29,100,NaT,0.0
30183,AAPL,2023-12-28,194.14000,194.66000,193.17000,193.58000,33691704.0,2023-12-29,100,NaT,0.0
30184,AAPL,2023-12-29,193.89999,194.39999,191.72501,192.53000,42120662.0,2023-12-29,100,NaT,0.0

In [41]:
# For visualising of df

# data = db.raw_sql(f"""
#     SELECT 
#         c.ticker,
#         a.date,
#         a.openprc,
#         a.askhi,
#         a.bidlo,
#         a.prc,
#         a.vol,
#         b.dlstdt,
#         b.dlstcd,
#         b.nextdt,
#         b.dlprc,
#     FROM crsp_a_stock.dsf a
#     JOIN crsp_a_stock.dsedelist b ON a.permno = b.permno
#     JOIN crsp_a_stock.dse c ON a.permno = c.permno
#     WHERE c.ticker = 'PATI'
#     AND a.date >= '2000-01-01'
# """)
# data

,ticker,date,openprc,askhi,bidlo,prc,vol,dlstdt,dlstcd,nextdt,dlprc,dlprc
0,PATI,2015-02-02,18.00000,24.00000,18.0000,23.00000,4573.0,2023-12-21,233,None,0.0000,None
1,PATI,2015-02-03,22.00000,25.99000,21.6500,25.00000,7225.0,2023-12-21,233,None,0.0000,None
2,PATI,2015-02-04,24.95000,26.22000,23.6500,24.00000,7208.0,2023-12-21,233,None,0.0000,None
3,PATI,2015-02-05,26.50000,27.00000,24.5200,24.70000,12633.0,2023-12-21,233,None,0.0000,None
4,PATI,2015-02-06,25.00000,25.00000,22.5600,24.05000,6234.0,2023-12-21,233,None,0.0000,None
...,...,...,...,...,...,...,...,...,...,...,...,...
7066,PATI,2000-09-07,0.57813,0.57813,0.5000,0.50000,36755.0,2000-09-13,561,2000-09-14,-0.5469,None
7067,PATI,2000-09-08,NaN,0.59375,0.5000,-0.54688,0.0,2000-09-13,561,2000-09-14,-0.5469,None
7068,PATI,2000-09-11,0.59375,0.59375,0.5625,0.56250,12800.0,2000-09-13,561,2000-09-14,-0.5469,None
7069,PATI,2000-09-12,0.50000,0.50000,0.5000,0.50000,5910.0,2000-09-13,561,2000-09-14,-0.5469,None
7070,PATI,2000-09-13,0.59375,0.59375,0.5000,0.50000,17200.0,2000-09-13,561,2000-09-14,-0.5469,None

In [38]:
import wrds
import pandas as pd
db = wrds.Connection()

tickers_df = pd.read_excel("RIY Index Constituents.xlsx")
unique_tickers = set()
cols = tickers_df.columns
for col in cols:
    tickers_for_year = tickers_df[col].unique()
    for ticker in tickers_for_year:
        unique_tickers.add(ticker.split()[0].strip().upper())
print(f"Unique tickers: {len(unique_tickers)}")

years = [x for x in range(2000, 2024)]

count = 0
empty_tickers = []
with pd.HDFStore("all_options_data.h5") as store:
    for ticker in unique_tickers:
        ticker_data = []
        for year in years:
            data = db.raw_sql(
                f"""
                select 
                    b.ticker,
                    a.date, 
                    a.exdate,
                    a.cp_flag,
                    a.strike_price,
                    a.best_bid,
                    a.best_offer,
                    a.open_interest,
                    a.impl_volatility,
                    a.delta,
                    a.gamma,
                    a.theta,
                    a.vega,
                    a.volume
                from optionm_all.opprcd{year} a, optionm.securd b
                where a.secid = b.secid
                and b.ticker = '{ticker}'
                and a.exdate - a.date <= 14
                """, date_cols=["date", "exdate"])
            if not data.empty:
                ticker_data.append(data)
        
        count += 1
        if ticker_data:
            full_data = pd.concat(ticker_data, ignore_index=True)
            full_data.sort_values(by=["date"], inplace=True)
            full_data["ticker"] = full_data["ticker"].astype("category")
            store.put(ticker, full_data, format="table")
            print(f"Stored {ticker}, count: {count}")
        else:
            print(f"No data: {ticker}, count: {count}")
            empty_tickers.append(ticker)

print("Completed")

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done
Unique tickers: 1009
Stored IDA, count: 1
Stored WTFC, count: 2
Stored Z, count: 3
Stored W, count: 4
Stored MDB, count: 5
Stored RGA, count: 6
Stored MSTR, count: 7
Stored GNTX, count: 8
Stored SAIA, count: 9
Stored TRGP, count: 10
Stored AFRM, count: 11
Stored PYCR, count: 12
Stored R, count: 13
Stored HUBS, count: 14
Stored RGLD, count: 15
Stored MPC, count: 16
Stored BRX, count: 17
Stored HAS, count: 18
Stored COO, count: 19
Stored FRPT, count: 20
Stored MASI, count: 21
Stored LSCC, count: 22
Stored SAM, count: 23
Stored COST, count: 24
Stored DNB, count: 25
Stored NTNX, count: 26
No data: CNH, count: 27
Stored AES, count: 28
Stored ETSY, count: 29
Stored DUK, count: 30
Stored CPB, count: 31
Stored COIN, count: 32
Stored GFS, count: 33
Stored SMCI, count: 34
Stored BERY, count: 35
Stored WLK, count: 36
Stored EXC, count: 37
Stored KVUE, count: 38
Stored COLM, count: 39
Stored PFE, count: 40
Stored VTRS, count: 41
Stored GL, count: 42
Stored DVA, count: 43
Stored HPQ, count: 44
Stored PLD, count: 45
Stored PPG, count: 46
Stored LMT, count: 47
Stored DT, count: 48
Stored UTHR, count: 49
Stored PARA, count: 50
Stored AVGO, count: 51
Stored TEAM, count: 52
Stored CBOE, count: 53
Stored FHB, count: 54
Stored TOST, count: 55
Stored ARES, count: 56
Stored AN, count: 57
Stored GIS, count: 58
Stored FITB, count: 59
Stored PPC, count: 60
Stored NI, count: 61
Stored NSA, count: 62
Stored ENOV, count: 63
Stored HII, count: 64
Stored MTD, count: 65
Stored KMI, count: 66
Stored SNOW, count: 67
Stored LNT, count: 68
Stored LEG, count: 69
Stored OC, count: 70
Stored ADC, count: 71
Stored ORLY, count: 72
Stored IFF, count: 73
Stored STZ, count: 74
Stored DPZ, count: 75
Stored SEG, count: 76
Stored REGN, count: 77
Stored RRX, count: 78
Stored AIG, count: 79
No data: VSTS, count: 80
Stored BFAM, count: 81
Stored VTR, count: 82
Stored ANET, count: 83
Stored GD, count: 84
Stored MORN, count: 85
Stored VMI, count: 86
No data: SN, count: 87
Stored TREX, count: 88
Stored DLR, count: 89
Stored GGG, count: 90
Stored JBHT, count: 91
Stored CCI, count: 92
Stored DHR, count: 93
Stored LULU, count: 94
Stored CRBG, count: 95
Stored PEG, count: 96
Stored TMUS, count: 97
Stored WAT, count: 98
Stored WFRD, count: 99
Stored AWI, count: 100
Stored EQH, count: 101
Stored CMG, count: 102
Stored INSP, count: 103
Stored ALL, count: 104
Stored MSFT, count: 105
Stored ACGL, count: 106
Stored SYY, count: 107
Stored WDAY, count: 108
Stored TDG, count: 109
Stored NDSN, count: 110
Stored KMB, count: 111
Stored BRBR, count: 112
Stored MRVL, count: 113
Stored DOX, count: 114
Stored NEE, count: 115
Stored ARE, count: 116
Stored CAH, count: 117
Stored ONTO, count: 118
Stored PSTG, count: 119
Stored VEEV, count: 120
Stored SSNC, count: 121
Stored INTC, count: 122
Stored OTIS, count: 123
Stored RIVN, count: 124
Stored CEG, count: 125
Stored ITW, count: 126
Stored ODFL, count: 127
Stored STLD, count: 128
Stored AFG, count: 129
Stored AFL, count: 130
Stored ENTG, count: 131
Stored MDLZ, count: 132
Stored CCK, count: 133
Stored JPM, count: 134
Stored RSG, count: 135
Stored XRAY, count: 136
Stored MCK, count: 137
Stored DFS, count: 138
Stored FIX, count: 139
Stored APP, count: 140
Stored BBWI, count: 141
Stored SPGI, count: 142
Stored LII, count: 143
Stored NEU, count: 144
Stored DOV, count: 145
Stored ESS, count: 146
Stored IEX, count: 147
Stored AXON, count: 148
Stored EME, count: 149
Stored ITCI, count: 150
Stored AMT, count: 151
Stored GNRC, count: 152
Stored RCL, count: 153
Stored PWR, count: 154
Stored TTWO, count: 155
Stored SLB, count: 156
Stored LRCX, count: 157
Stored IP, count: 158
Stored LH, count: 159
Stored FCX, count: 160
Stored ZTS, count: 161

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored EHC, count: 162
Stored HLI, count: 163
Stored EIX, count: 164
Stored JAZZ, count: 165
Stored ALLY, count: 166
Stored ACI, count: 167
Stored APH, count: 168
Stored CFG, count: 169
No data: BRK/B, count: 170
Stored ETN, count: 171
Stored ST, count: 172
Stored SAIC, count: 173
Stored UGI, count: 174
Stored XP, count: 175
Stored WEC, count: 176
Stored CCCS, count: 177
Stored RITM, count: 178
Stored NET, count: 179
Stored CG, count: 180
Stored GLW, count: 181
Stored MGM, count: 182
Stored TGT, count: 183
Stored ZBH, count: 184
Stored VRSK, count: 185
Stored ACHC, count: 186
Stored EXAS, count: 187
No data: CWEN/A, count: 188
Stored CNA, count: 189

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored CXT, count: 190
Stored ZM, count: 191
Stored ED, count: 192
Stored LAD, count: 193
Stored RCM, count: 194
Stored TAP, count: 195
No data: SOLV, count: 196
Stored SMAR, count: 197
Stored EA, count: 198
Stored CSL, count: 199
Stored ELS, count: 200
Stored PSX, count: 201
Stored CTVA, count: 202
Stored DASH, count: 203
Stored MDT, count: 204
Stored NU, count: 205
Stored TSCO, count: 206
Stored TWLO, count: 207
Stored ALK, count: 208
Stored AEP, count: 209
Stored DOCS, count: 210
Stored WSO, count: 211
Stored TDY, count: 212
Stored UNH, count: 213
Stored DIS, count: 214
No data: BF/B, count: 215

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored CHDN, count: 216
Stored OXY, count: 217
Stored OZK, count: 218
No data: DAY, count: 219
Stored CINF, count: 220
No data: BF/A, count: 221
Stored LYFT, count: 222
Stored MTCH, count: 223
Stored AXS, count: 224
Stored LFUS, count: 225
Stored INVH, count: 226
Stored SPOT, count: 227
No data: HEI/A, count: 228
Stored MEDP, count: 229
Stored BAH, count: 230
Stored TPR, count: 231
Stored SNX, count: 232
Stored CPRI, count: 233
Stored FDX, count: 234
Stored PPL, count: 235
Stored XOM, count: 236
Stored KRC, count: 237
Stored PEN, count: 238
Stored LKQ, count: 239
Stored OLED, count: 240
Stored CLVT, count: 241
Stored CHD, count: 242
Stored KR, count: 243
Stored PARAA, count: 244
Stored MET, count: 245
Stored AZTA, count: 246
Stored CL, count: 247
Stored SKX, count: 248
Stored J, count: 249
Stored ULTA, count: 250

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored OKE, count: 251
Stored MHK, count: 252
No data: LOAR, count: 253
No data: UHAL/B, count: 254
Stored TXN, count: 255
Stored QDEL, count: 256
Stored YUM, count: 257
Stored SPR, count: 258
Stored VLO, count: 259
Stored KD, count: 260
Stored RVTY, count: 261
Stored HIW, count: 262
Stored NFLX, count: 263

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored DELL, count: 264
Stored DUOL, count: 265
Stored APG, count: 266
Stored NVST, count: 267
Stored THC, count: 268
Stored THG, count: 269
No data: GEV, count: 270
Stored COLB, count: 271
Stored RJF, count: 272
Stored TECH, count: 273
Stored AA, count: 274
Stored WAL, count: 275
Stored CSGP, count: 276
Stored ORCL, count: 277
Stored BURL, count: 278
Stored ALSN, count: 279
Stored BIIB, count: 280
Stored POST, count: 281
Stored TNL, count: 282
Stored CNC, count: 283
Stored EXR, count: 284
Stored RPM, count: 285
Stored SON, count: 286
Stored STE, count: 287
Stored ALLE, count: 288
Stored PNFP, count: 289
Stored HIG, count: 290
Stored CTSH, count: 291
Stored HUM, count: 292

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored VNO, count: 293
Stored CAG, count: 294
No data: LLYVA, count: 295
Stored HCP, count: 296
Stored MO, count: 297
Stored VVV, count: 298
Stored HRL, count: 299
Stored ABBV, count: 300
Stored HRB, count: 301
Stored AZO, count: 302
Stored CHTR, count: 303
Stored EXPD, count: 304
No data: AS, count: 305
Stored LEA, count: 306
Stored F, count: 307
Stored GOOG, count: 308
Stored LDOS, count: 309
Stored AXP, count: 310
Stored ESTC, count: 311
Stored LBRDA, count: 312
Stored NFG, count: 313
Stored EBAY, count: 314
Stored BXP, count: 315
Stored CPNG, count: 316
Stored EGP, count: 317
Stored FHN, count: 318
Stored MSCI, count: 319
Stored PGR, count: 320
Stored DGX, count: 321
Stored REXR, count: 322
Stored WBD, count: 323
Stored LECO, count: 324
Stored LOPE, count: 325
Stored GXO, count: 326
Stored ASH, count: 327
Stored HUN, count: 328
Stored INFA, count: 329
Stored LPLA, count: 330
Stored OLN, count: 331
Stored TRMB, count: 332
Stored CMCSA, count: 333
Stored GME, count: 334
Stored PATH, count: 335
Stored FOUR, count: 336
Stored TFSL, count: 337
Stored LEN, count: 338
Stored SWK, count: 339
Stored FANG, count: 340
Stored SNPS, count: 341
Stored FI, count: 342
No data: SEB, count: 343
Stored RBC, count: 344
Stored LBRDK, count: 345
Stored APA, count: 346
Stored DAL, count: 347
Stored GO, count: 348
Stored CVNA, count: 349
Stored NNN, count: 350
Stored CARR, count: 351
Stored LNC, count: 352
Stored RH, count: 353
Stored AMD, count: 354
Stored FERG, count: 355
Stored SWKS, count: 356
Stored BAX, count: 357
Stored LW, count: 358
Stored MOS, count: 359
Stored TKR, count: 360
Stored FTV, count: 361
Stored SMG, count: 362
Stored ADT, count: 363
Stored JLL, count: 364
Stored COF, count: 365
Stored APO, count: 366
Stored NLY, count: 367
Stored MKC, count: 368
Stored AWK, count: 369
Stored MMM, count: 370
Stored MKL, count: 371
Stored TER, count: 372
Stored EVRG, count: 373
Stored HAL, count: 374
Stored IBM, count: 375
Stored FTRE, count: 376
Stored MLM, count: 377
Stored OMF, count: 378
Stored SITE, count: 379
Stored AMH, count: 380
Stored CIVI, count: 381
Stored DVN, count: 382
Stored TRU, count: 383
Stored BLDR, count: 384
Stored NDAQ, count: 385
Stored AEE, count: 386
Stored AKAM, count: 387
Stored BOKF, count: 388
Stored CFLT, count: 389
Stored FIS, count: 390
Stored WYNN, count: 391
Stored PRU, count: 392

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored CZR, count: 393
Stored IT, count: 394
Stored VZ, count: 395
Stored MRO, count: 396
Stored ANSS, count: 397
No data: ALAB, count: 398
Stored DOW, count: 399
Stored PINC, count: 400
Stored REYN, count: 401
Stored CRUS, count: 402
Stored PAG, count: 403
Stored VKTX, count: 404
Stored DD, count: 405
Stored ORI, count: 406
Stored RMD, count: 407
Stored VNOM, count: 408
Stored CMI, count: 409
Stored EVR, count: 410
Stored WING, count: 411
Stored XPO, count: 412
Stored DTE, count: 413
Stored INGR, count: 414
Stored AVB, count: 415
Stored CFR, count: 416
Stored PNR, count: 417
No data: COKE, count: 418
Stored MRK, count: 419
Stored CTRA, count: 420
Stored XYL, count: 421
Stored C, count: 422
Stored WH, count: 423
Stored JBL, count: 424
Stored S, count: 425
Stored ROP, count: 426
Stored GTLB, count: 427
Stored PAYC, count: 428
Stored GMED, count: 429
Stored SCI, count: 430
Stored BA, count: 431
Stored FAST, count: 432
Stored SF, count: 433
Stored DDOG, count: 434
Stored PNW, count: 435
Stored VFC, count: 436
Stored UA, count: 437
Stored BWXT, count: 438
No data: GAP, count: 439
Stored KO, count: 440
Stored TFX, count: 441
Stored X, count: 442
Stored MA, count: 443
Stored NEM, count: 444
Stored TT, count: 445
Stored EPR, count: 446
Stored KNSL, count: 447
Stored TYL, count: 448
Stored PHM, count: 449
Stored NUE, count: 450
Stored STAG, count: 451
Stored EL, count: 452
Stored AGR, count: 453
Stored DV, count: 454
Stored AAP, count: 455
Stored SYK, count: 456
Stored WU, count: 457
Stored MTB, count: 458
Stored RARE, count: 459
Stored NVT, count: 460
Stored BILL, count: 461
Stored AR, count: 462
Stored MS, count: 463
Stored NWSA, count: 464
Stored JEF, count: 465
Stored ATR, count: 466
Stored LOW, count: 467
Stored OSK, count: 468
Stored VOYA, count: 469
Stored WSM, count: 470
Stored BBY, count: 471
Stored CHRW, count: 472
Stored GPC, count: 473
Stored WEX, count: 474
Stored VRT, count: 475
Stored GM, count: 476
Stored WWD, count: 477
Stored FCNCA, count: 478
Stored GEN, count: 479
Stored PSA, count: 480
Stored AMED, count: 481
Stored TDC, count: 482
Stored CSCO, count: 483
Stored AME, count: 484
Stored MP, count: 485
Stored DDS, count: 486
Stored CRH, count: 487
Stored CHE, count: 488
Stored PAYX, count: 489
Stored ON, count: 490
Stored PODD, count: 491
Stored A, count: 492
Stored FWONK, count: 493
Stored FYBR, count: 494
Stored QRVO, count: 495
Stored GEHC, count: 496
Stored PG, count: 497
Stored JNPR, count: 498
Stored TPG, count: 499
Stored AVY, count: 500
Stored PNC, count: 501
Stored EW, count: 502
Stored HOLX, count: 503
Stored EXEL, count: 504
Stored IAC, count: 505
Stored PEGA, count: 506
Stored AMGN, count: 507
Stored EQIX, count: 508
Stored MDU, count: 509
Stored RYAN, count: 510
Stored KEYS, count: 511
Stored NRG, count: 512
Stored PENN, count: 513
Stored FAF, count: 514
Stored FE, count: 515
Stored BAC, count: 516
Stored GOOGL, count: 517
Stored DKS, count: 518
Stored GPN, count: 519
Stored ELF, count: 520
Stored PVH, count: 521
Stored CR, count: 522
Stored CACI, count: 523
Stored WMS, count: 524
Stored TRIP, count: 525
No data: BIRK, count: 526
Stored NYT, count: 527
Stored NOW, count: 528
Stored CVX, count: 529
Stored ECL, count: 530
Stored AMCR, count: 531
Stored BMRN, count: 532
Stored MAT, count: 533
Stored BJ, count: 534
Stored LVS, count: 535
Stored TTD, count: 536
Stored HOG, count: 537
Stored WDC, count: 538
Stored STWD, count: 539
Stored TPX, count: 540
Stored SLM, count: 541
Stored CB, count: 542
Stored SBAC, count: 543
Stored ABT, count: 544
Stored UAA, count: 545
Stored RS, count: 546
No data: SW, count: 547

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored MRNA, count: 548
Stored OGN, count: 549
Stored VMC, count: 550
Stored KEY, count: 551
Stored LCID, count: 552
Stored RHI, count: 553
Stored NTRA, count: 554
Stored META, count: 555
No data: DJT, count: 556
Stored ZS, count: 557
Stored POOL, count: 558
Stored SYF, count: 559
Stored HCA, count: 560
Stored CF, count: 561
Stored NXST, count: 562
Stored HXL, count: 563
Stored CROX, count: 564
Stored AAPL, count: 565
Stored CNXC, count: 566
Stored HOOD, count: 567
Stored MCO, count: 568
Stored NWL, count: 569
Stored TXRH, count: 570
Stored WM, count: 571
Stored TOL, count: 572
Stored CASY, count: 573
Stored CHK, count: 574
Stored BRKR, count: 575
No data: CPAY, count: 576
Stored IVZ, count: 577
Stored PLNT, count: 578
Stored DOCU, count: 579
Stored NOC, count: 580
Stored OWL, count: 581
Stored CCL, count: 582
Stored GTES, count: 583
Stored EPAM, count: 584
Stored MIDD, count: 585
Stored PCTY, count: 586
Stored MNST, count: 587
Stored KHC, count: 588
Stored PFGC, count: 589
No data: GRAL, count: 590
Stored ATI, count: 591
Stored TW, count: 592
Stored OLLI, count: 593
Stored TSN, count: 594
No data: LINE, count: 595
Stored BRO, count: 596
Stored LYB, count: 597
Stored LBTYA, count: 598
Stored MMC, count: 599
Stored AVT, count: 600
Stored MTN, count: 601
Stored ESI, count: 602
Stored MTDR, count: 603
Stored FLS, count: 604
Stored QS, count: 605
Stored TFC, count: 606
Stored WEN, count: 607
Stored WTW, count: 608
Stored U, count: 609
Stored PM, count: 610
Stored GRMN, count: 611
No data: TKO, count: 612
Stored UI, count: 613
Stored PSN, count: 614
Stored CDNS, count: 615
Stored HPE, count: 616
Stored K, count: 617
Stored CNP, count: 618
Stored HR, count: 619
Stored NWS, count: 620
Stored TROW, count: 621
Stored CDW, count: 622
Stored ICE, count: 623
Stored LHX, count: 624
Stored MSI, count: 625
Stored SPB, count: 626
Stored CE, count: 627
Stored LUV, count: 628
Stored SCHW, count: 629
Stored RF, count: 630
No data: TPL, count: 631
Stored BR, count: 632
Stored AMZN, count: 633
Stored AVTR, count: 634
Stored BPOP, count: 635
Stored BHF, count: 636
Stored FSLR, count: 637
Stored CLX, count: 638
Stored HLT, count: 639
Stored IR, count: 640
Stored HEI, count: 641
Stored SHC, count: 642
Stored COTY, count: 643
Stored FTNT, count: 644
Stored WBA, count: 645
Stored FMC, count: 646
Stored SCCO, count: 647
Stored SNV, count: 648
Stored PINS, count: 649
Stored MKTX, count: 650
Stored HAYW, count: 651
Stored IONS, count: 652
Stored ADM, count: 653
Stored CHH, count: 654
Stored HD, count: 655
Stored NBIX, count: 656
Stored SHW, count: 657
Stored ZBRA, count: 658
Stored GILD, count: 659
Stored EXPE, count: 660
Stored DHI, count: 661
Stored VNT, count: 662
Stored AAL, count: 663
Stored ACM, count: 664
Stored RGEN, count: 665
Stored VST, count: 666
Stored INCY, count: 667
Stored RBLX, count: 668
Stored SQ, count: 669
Stored MPW, count: 670
Stored KDP, count: 671
Stored NOV, count: 672
Stored WFC, count: 673
Stored BKR, count: 674
Stored FFIV, count: 675
Stored EQT, count: 676
Stored BSX, count: 677
Stored STT, count: 678
Stored CPT, count: 679
Stored PCOR, count: 680
Stored ABNB, count: 681
Stored CRL, count: 682
Stored CRI, count: 683
Stored DAR, count: 684
Stored HST, count: 685
Stored DLTR, count: 686
Stored SLGN, count: 687
Stored CRM, count: 688
Stored MAN, count: 689
Stored CPRT, count: 690
Stored ROIV, count: 691
Stored AXTA, count: 692
Stored GPK, count: 693
Stored ARW, count: 694
Stored LAMR, count: 695
Stored ROL, count: 696
Stored WPC, count: 697
Stored CUZ, count: 698
Stored CVS, count: 699
Stored CLH, count: 700
Stored SBUX, count: 701
Stored UHS, count: 702
Stored GWRE, count: 703
Stored WMT, count: 704
Stored CLF, count: 705
Stored DXC, count: 706
Stored ITT, count: 707
Stored PRGO, count: 708
Stored WELL, count: 709
Stored CAVA, count: 710
Stored HWM, count: 711
Stored KBR, count: 712
Stored MU, count: 713
Stored TXT, count: 714
Stored PLTK, count: 715
Stored ATO, count: 716
Stored CNM, count: 717
Stored EEFT, count: 718
Stored WSC, count: 719
Stored WTRG, count: 720
Stored PH, count: 721
Stored HSY, count: 722
Stored RRC, count: 723
Stored FOXA, count: 724
Stored ESAB, count: 725
Stored ROKU, count: 726
Stored MCD, count: 727
Stored WCC, count: 728
Stored WBS, count: 729
Stored DTM, count: 730
Stored MAA, count: 731
Stored WST, count: 732
Stored FRT, count: 733
Stored LITE, count: 734
Stored INTU, count: 735
Stored MANH, count: 736
Stored SRCL, count: 737
Stored CC, count: 738
Stored DKNG, count: 739
Stored M, count: 740
Stored ALGN, count: 741
Stored KEX, count: 742
Stored ROST, count: 743
Stored SEE, count: 744
Stored AJG, count: 745
Stored IBKR, count: 746
Stored IQV, count: 747
Stored EOG, count: 748
Stored OHI, count: 749
Stored PRI, count: 750
Stored D, count: 751
Stored APTV, count: 752
Stored BROS, count: 753
Stored IRDM, count: 754
Stored IPGP, count: 755
Stored BDX, count: 756
Stored USB, count: 757
Stored EMR, count: 758
Stored UPS, count: 759
Stored CW, count: 760
Stored BK, count: 761
Stored TTC, count: 762
Stored FNF, count: 763
Stored WY, count: 764
Stored AIZ, count: 765
Stored CAR, count: 766
Stored IDXX, count: 767
Stored COP, count: 768
Stored G, count: 769
Stored UNP, count: 770
Stored RKT, count: 771
Stored FDS, count: 772
Stored NTRS, count: 773
Stored ALB, count: 774
Stored BYD, count: 775
Stored ROK, count: 776
Stored IPG, count: 777
Stored YETI, count: 778
Stored AMP, count: 779
Stored PLTR, count: 780
Stored WHR, count: 781
Stored ADSK, count: 782
Stored RLI, count: 783
Stored NTAP, count: 784
Stored AL, count: 785
Stored GWW, count: 786
Stored NKE, count: 787
Stored CRWD, count: 788
Stored MCHP, count: 789
No data: VLTO, count: 790
Stored COR, count: 791
Stored FIVN, count: 792
Stored BEN, count: 793
Stored AGO, count: 794
Stored APPF, count: 795
Stored BSY, count: 796
Stored COHR, count: 797
Stored PK, count: 798
Stored KSS, count: 799
Stored RL, count: 800
No data: NVR, count: 801
Stored HUBB, count: 802
Stored UHAL, count: 803
Stored UDR, count: 804
Stored KLAC, count: 805
Stored CTLT, count: 806
Stored NSC, count: 807
Stored ES, count: 808
Stored PCAR, count: 809
Stored RYN, count: 810
Stored TTEK, count: 811

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored AYI, count: 812
Stored KNX, count: 813
Stored MAS, count: 814
Stored CAT, count: 815
Stored DXCM, count: 816
Stored AZEK, count: 817
Stored AZPN, count: 818
No data: LEN/B, count: 819
Stored EG, count: 820
Stored O, count: 821
Stored ELV, count: 822
Stored TRV, count: 823
Stored CTAS, count: 824
Stored FND, count: 825
Stored CELH, count: 826
Stored MKSI, count: 827
Stored MSGS, count: 828
Stored AGNC, count: 829
Stored SPG, count: 830
Stored FTI, count: 831
Stored DBX, count: 832
Stored ILMN, count: 833
Stored MSA, count: 834
Stored BG, count: 835
Stored MPWR, count: 836
Stored MTZ, count: 837
Stored NVDA, count: 838
Stored PYPL, count: 839
Stored COLD, count: 840
Stored VIRT, count: 841
Stored SIRI, count: 842
Stored NCNO, count: 843
Stored HBAN, count: 844
Stored BEPC, count: 845
Stored BLD, count: 846
Stored ADBE, count: 847
Stored SNA, count: 848
Stored CSX, count: 849
Stored RNR, count: 850
Stored USFD, count: 851
Stored TMO, count: 852
Stored LSTR, count: 853
Stored FR, count: 854
Stored AMAT, count: 855
Stored DG, count: 856
Stored FLO, count: 857
Stored URI, count: 858
Stored MTG, count: 859
Stored TSLA, count: 860
Stored FWONA, count: 861
Stored CI, count: 862
Stored SUI, count: 863
Stored JNJ, count: 864
Stored MOH, count: 865
Stored BALL, count: 866
Stored CGNX, count: 867
Stored EMN, count: 868
Stored QGEN, count: 869
Stored OGE, count: 870
Stored PTC, count: 871
Stored ZG, count: 872
Stored UWMC, count: 873
Stored BWA, count: 874
Stored CUBE, count: 875
Stored ARMK, count: 876
Stored APD, count: 877
Stored SO, count: 878
Stored BLK, count: 879
Stored QCOM, count: 880
Stored RNG, count: 881
Stored ELAN, count: 882
Stored T, count: 883
Stored AAON, count: 884
Stored MAR, count: 885
Stored EFX, count: 886
Stored NFE, count: 887
Stored HES, count: 888
Stored FNB, count: 889
Stored VRTX, count: 890
Stored SOFI, count: 891
Stored SNDR, count: 892
Stored GDDY, count: 893
No data: LLYVK, count: 894
Stored IRM, count: 895
No data: CART, count: 896
Stored PR, count: 897
Stored VICI, count: 898
Stored LPX, count: 899
Stored ALNY, count: 900
Stored CIEN, count: 901
Stored ENPH, count: 902
Stored EQR, count: 903
Stored L, count: 904
Stored THO, count: 905
Stored VRSN, count: 906
Stored PII, count: 907
Stored DRI, count: 908

C:\Users\Gavin\AppData\Local\Temp\ipykernel_12000\1341200476.py:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_data = pd.concat(ticker_data, ignore_index=True)

Stored WAB, count: 909
Stored LLY, count: 910
Stored V, count: 911
Stored UNM, count: 912
Stored ALGM, count: 913
Stored HON, count: 914
Stored KKR, count: 915
Stored WRB, count: 916
Stored REG, count: 917
Stored ETR, count: 918
Stored SJM, count: 919
Stored WMB, count: 920
Stored CHRD, count: 921
Stored ACN, count: 922
Stored GLOB, count: 923
Stored GLPI, count: 924
Stored CME, count: 925
Stored LYV, count: 926
Stored GS, count: 927
Stored AOS, count: 928
Stored FBIN, count: 929
Stored DCI, count: 930
Stored TXG, count: 931
No data: WTM, count: 932
Stored UAL, count: 933
Stored AM, count: 934
Stored NCLH, count: 935
Stored CWEN, count: 936
Stored DE, count: 937
Stored MTSI, count: 938
Stored FIVE, count: 939
Stored H, count: 940
Stored SWN, count: 941
Stored EWBC, count: 942
Stored KIM, count: 943
Stored FCN, count: 944
Stored CBSH, count: 945
Stored WOLF, count: 946
Stored AMG, count: 947
Stored BIO, count: 948
Stored SEIC, count: 949
Stored AGCO, count: 950
Stored AON, count: 951
Stored DLB, count: 952
Stored MUSA, count: 953
Stored OMC, count: 954
Stored UBER, count: 955
Stored LNW, count: 956
Stored RPRX, count: 957
Stored AMKR, count: 958
Stored BC, count: 959
Stored CACC, count: 960
Stored BMY, count: 961
Stored DINO, count: 962
Stored DOC, count: 963
Stored LAZ, count: 964
Stored JCI, count: 965
Stored PEP, count: 966
Stored CMA, count: 967
Stored CBRE, count: 968
Stored ISRG, count: 969
Stored SRE, count: 970
Stored VAC, count: 971
Stored EXP, count: 972
Stored JKHY, count: 973
Stored HSIC, count: 974
Stored JHG, count: 975
Stored LIN, count: 976
Stored LNG, count: 977
Stored FICO, count: 978
Stored MSM, count: 979
Stored RTX, count: 980
Stored BX, count: 981
Stored GE, count: 982
Stored KMPR, count: 983
Stored PANW, count: 984
Stored RBA, count: 985
Stored TJX, count: 986
Stored DECK, count: 987
Stored PB, count: 988
Stored HHH, count: 989
Stored APLS, count: 990
Stored CMS, count: 991
Stored ZI, count: 992
Stored PFG, count: 993
Stored XEL, count: 994
Stored BKNG, count: 995
Stored OVV, count: 996
Stored FOX, count: 997
Stored PCG, count: 998
Stored ADP, count: 999
Stored CERT, count: 1000
Stored JWN, count: 1001
Stored PKG, count: 1002
Stored ZION, count: 1003
Stored SRPT, count: 1004
Stored SSD, count: 1005
Stored KMX, count: 1006
Stored LBTYK, count: 1007
Stored OKTA, count: 1008
Stored ADI, count: 1009
Completed

In [46]:
with pd.HDFStore("all_options_data.h5") as store:
    df_aapl = store['AAPL']  # Load specific ticker's data
df_aapl

,ticker,date,exdate,cp_flag,strike_price,best_bid,best_offer,open_interest,impl_volatility,delta,gamma,theta,vega,volume
59,AAPL,2000-01-10,2000-01-22,P,100000.0,7.2500,7.500,4063.0,0.879421,-0.521674,0.025665,-91.488500,7.057306,48.0
34,AAPL,2000-01-10,2000-01-22,P,85000.0,1.5625,1.625,2668.0,0.902814,-0.172116,0.015953,-61.066300,4.522867,175.0
35,AAPL,2000-01-10,2000-01-22,P,47500.0,0.0000,0.250,941.0,1.850817,-0.010046,0.000817,-13.311650,0.475041,0.0
36,AAPL,2000-01-10,2000-01-22,C,40000.0,57.6250,58.125,1104.0,2.002907,0.995955,0.000338,-8.733804,0.212873,7.0
37,AAPL,2000-01-10,2000-01-22,C,90000.0,10.7500,11.250,2273.0,0.924280,0.721622,0.020485,-87.013050,5.950613,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989781,AAPL,2023-08-31,2023-09-01,P,180000.0,0.0200,0.030,23962.0,0.392160,-0.017771,0.011368,-30.684100,0.431584,13432.0
989782,AAPL,2023-08-31,2023-09-01,P,182500.0,0.0400,0.050,20410.0,0.312088,-0.036579,0.026129,-44.564220,0.787846,9587.0
989783,AAPL,2023-08-31,2023-09-01,P,185000.0,0.1200,0.130,21667.0,0.241647,-0.108708,0.078512,-79.875690,1.832929,34341.0
989772,AAPL,2023-08-31,2023-09-01,P,157500.0,0.0000,0.010,1234.0,1.149845,-0.001524,0.000438,-10.215860,0.048766,0.0
989925,AAPL,2023-08-31,2023-09-08,P,95000.0,0.0000,0.010,0.0,1.437048,-0.000455,0.000041,-1.481475,0.045153,0.0

In [35]:
# year = 2000
# ticker = "NVDA"
# data = db.raw_sql(
#     f"""
#     select 
#         b.ticker,
#         a.date, 
#         a.exdate,
#         a.cp_flag,
#         a.strike_price,
#         a.best_bid,
#         a.best_offer,
#         a.open_interest,
#         a.impl_volatility,
#         a.delta,
#         a.gamma,
#         a.theta,
#         a.vega,
#         a.volume
#     from optionm_all.opprcd{year} a, optionm.securd b
#     where a.secid = b.secid
#     and b.ticker = '{ticker}'
#     and a.exdate - a.date <= 14
# """)
# data.sort_values(by=["date"], inplace=True)

In [36]:
data

,ticker,date,exdate,cp_flag,strike_price,best_bid,best_offer,open_interest,impl_volatility,delta,gamma,theta,vega,volume
13,NVDA,2000-01-10,2000-01-22,P,30000.0,0.0625,0.2500,201.0,1.203742,-0.038031,0.008760,-12.01046,0.648941,0.0
16,NVDA,2000-01-10,2000-01-22,C,40000.0,4.6250,4.8750,4280.0,0.972414,0.696744,0.046152,-37.83539,2.718517,8.0
15,NVDA,2000-01-10,2000-01-22,P,45000.0,3.8750,4.1250,180.0,0.934630,-0.563456,0.053407,-45.59533,3.070799,0.0
14,NVDA,2000-01-10,2000-01-22,C,45000.0,1.9375,2.0625,794.0,0.891674,0.427070,0.056164,-39.98973,3.065653,150.0
12,NVDA,2000-01-10,2000-01-22,P,35000.0,0.3750,0.5000,203.0,1.002013,-0.107104,0.023447,-22.40909,1.442500,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4684,NVDA,2000-12-15,2000-12-16,P,62500.0,24.6250,25.1250,244.0,NaN,NaN,NaN,NaN,NaN,2.0
4685,NVDA,2000-12-15,2000-12-16,P,60000.0,22.2500,22.6250,700.0,NaN,NaN,NaN,NaN,NaN,4.0
4686,NVDA,2000-12-15,2000-12-16,P,65000.0,27.1250,27.6250,374.0,NaN,NaN,NaN,NaN,NaN,9.0
4688,NVDA,2000-12-15,2000-12-16,P,75000.0,37.1250,37.6250,138.0,NaN,NaN,NaN,NaN,NaN,0.0
4717,NVDA,2000-12-15,2000-12-16,P,52500.0,14.7500,15.1250,163.0,NaN,NaN,NaN,NaN,NaN,0.0